"""
Village-level worldbuilding data.
"""

# ---- VILLAGE LEVEL ----
village_terrains = [
    ("hills", "ore"),
    ("water", "fish and fowl"),
    ("grassland", "grain and livestock"),
    ("forest", "lumber")
]

village_templates = {
    "hills": [
        "A hardy hill village where miners hum prayers into stone.",
        "A wind-scoured settlement clinging to the slopes, stained in dust and sweat.",
        "A cliffside hamlet whose dwellings burrow into the rock like wary animals.",
        "A mining camp grown permanent, roofs sagging with age and ore dust.",
        "A village etched into terraces, each level holding another rumor.",
        "A stony settlement where every path slopes and every back bends.",
        "A hillside cluster of homes, their chimneys coughing out iron-scented smoke.",
        "A settlement perched above abandoned shafts and unanswered questions.",
        "A hamlet that creaks when the mountain shifts in its sleep.",
        "A village where tools and tempers are equally worn.",
        "A rugged place whose lights at night resemble scattered embers on stone.",
        "A settlement where the clang of metal is the village heartbeat.",
        "A cramped community hugging a single vein of stubborn ore.",
        "A hilltop cluster of huts, ringed by piles of discarded rock and weary jokes.",
        "A village carved into ledges, always one misstep from the long fall.",
        "A place where even the goats look exhausted by the climb.",
        "A settlement that woke one morning to find a new fissure splitting its main street.",
        "A hamlet that swears the mountain grumbles approval after each good haul.",
        "A hillside warren of families and shafts, indistinguishable from above.",
        "A village whose elders can read the stone like scripture.",
        "A cliffside settlement clinging to stone like moss.",
        "A terrace-cut village echoing with the clang of chisels and hammers.",
        "A rugged hamlet whose forges glow long after sunset.",
        "A mining village where children play with shards of quartz as toys.",
        "A highland hold whose people talk to echoes as if they answer.",
        "A hillside town crowned with cairns of those who never returned.",
        "A gray-walled community where ore veins are named like saints.",
        "A plateau hamlet that worships endurance as the highest art.",
        "A crag-perched village whose goats are wiser than most lords.",
        "A settlement whose people believe avalanches are the mountain's applause.",
        "A stone-ringed cluster of huts lit by the orange breath of furnaces.",
        "A high path hamlet where miners sleep with pickaxes for company.",
        "A wind-battered outpost where cliffs speak in moans and murmurs.",
        "A rugged place where the mountain occasionally takes back its dead.",
        "A village where miners carve prayers into every support beam.",
        "A ridge-top community that celebrates each new crack in the earth as a blessing.",
        "A quarry-town whose dust paints every face the same color.",
        "A settlement where the forge fires never dim, even in mourning.",
        "A hamlet where the ringing of steel doubles as a lullaby.",
        "A hill village whose wells are lined with the names of the fallen.",
        "A slope-hugging hamlet where chimneys lean like weary sentries.",
        "A quarry hollow where dust coats lungs and legends alike.",
        "A high ridge settlement where bells warn more often than they celebrate.",
        "A stone-stack village that echoes with the thrum of hidden forges.",
        "A goat-path cluster of homes built stubbornly into the wind.",
        "A mining hollow that glows at night with forge-fire prayers.",
        "A cliff village where ropes serve as roads and gossip travels faster uphill.",
        "A windswept plateau of slate roofs and harder faces.",
        "A hamlet clinging to basalt cliffs, proud of surviving gravity.",
        "A hill market whose stalls vanish beneath fog and reappear richer.",
        "A limestone ring of huts whose fires are fed by song.",
        "A shale-pit community where even the children smell of iron.",
        "A settlement that marks seasons by rockfall and rumor.",
        "A watch-hill village where dawn begins with hammer strikes.",
        "A granite outpost carved from stubborn faith.",
        "A hollow that measures its worth in ore, not oaths.",
        "A peak-road hamlet where donkeys outvote men.",
        "A highland crossroads haunted by echoes of marching feet.",
        "A terrace town that plants vines in stone and hope in rain.",
        "A canyon-edge hold where laughter carries farther than law.",
        "A terraced hamlet whose stones sweat at dawn and freeze by dusk.",
        "A cliff-rim village where echoes outlast apologies.",
        "A shale-pit town whose people claim the wind speaks their surnames.",
        "A hillfort reduced to hearths, proud of its surrender to peace.",
        "A hollow cut so deep the sun arrives late and leaves early.",
        "A ridge of smoke and goat bells where arguments roll downhill.",
        "A slate-quarry settlement that paints the sky gray on purpose.",
        "A mountain-lip hamlet where miners recite poetry for air.",
        "A frost-gnawed village that believes avalanches are blessings misplaced.",
        "A granite stair of huts rising toward clouds that never answer.",
        "A ridge market where donkeys and priests share the same patience.",
        "A bowl-valley hamlet whose roofs glitter with embedded ore.",
        "A slope village where moss grows faster than forgiveness.",
        "A stoneline of homes mortared with rumor and resilience.",
        "A highfield cluster where widows light forge fires to guide miners home.",
        "A wind-cuffed town that counts seasons by the angle of its shadows.",
        "A mining hamlet where laughter echoes louder underground.",
        "A watch-peak outpost built for vigilance and re-used for gossip.",
        "A barren crest where cairns mark victories no one recalls.",
        "A shale road hamlet that sells both stone and superstition.",
        "A storm-ledge hamlet where roofs are chained to cliffs with iron hope.",
        "A shale-road market whose echoes carry gossip halfway to the capital.",
        "A hollow whose miners carve prayers into the mountain's ribs.",
        "A wind-burned ridge where goats, gods, and gossip share a diet.",
        "A stair-cut village that climbs toward clouds and never catches them.",
        "A quarry mouth settlement that glitters faintly with mica and ambition.",
        "A granite shelf of huts that treats avalanches as seasonal guests.",
        "A barren crest where mothers sing to keep the stones awake.",
        "A smoke-ridge hamlet where even the anvil keeps secrets.",
        "A steep-trail haven where laughter must be shouted upward.",
        "A scree-slide community rebuilt every spring as a ritual of defiance.",
        "A shale-pit hollow where time and ore are measured by scars.",
        "A hillside market whose bells ring in minor keys to placate the slopes.",
        "A frost-bent row of houses that whistle when storms approach.",
        "A cliff-spine hamlet that worships endurance more than mercy.",
        "A ridge-road town that hosts races against thunderclouds.",
        "A valley lip of homes painted red to shame the rock into blooming.",
        "A crag-bound hollow that keeps an empty chair for lost climbers.",
        "A tunnel-mouth hamlet where every wall bears a miner's mark.",
        "A plateau forge village that calls lightning a co-worker."
    ],
        "A stony rise where families pass down echoes instead of heirlooms.",
        "A mountain-step village that paints its doors red for luck and forgiveness.",
        "A frost-leaning town whose sheep wear bells tuned to grief.",
        "A cliff-brow hamlet that lights torches so the stars won't feel lonely.",
        "A slate-path hollow that greets strangers with riddles instead of names.",
        "A mine-entrance village where every newborn is given a lump of ore to keep them grounded.",
        "A wind-bent ridge where laughter is the only thing that travels uphill.",
        "A shale-cliff town whose oldest house refuses to die, no matter the storm.",
        "A ridge-hollow hamlet where elders claim thunder is ancestral applause.",
        "A limestone terrace village that marks births with stones instead of candles.",
        "A ridge of shepherd huts that creak like violins in the cold.",
        "A hollowed crest where walls hum faintly when secrets are told.",
        "A mountainside hamlet where goats are considered partial reincarnations.",
        "A quarry lip settlement that still remembers the sound of its first hammer.",
        "A windy pass where voices echo three times for truth, twice for lies.",
        "A terrace-line town where houses grow taller as the families shrink.",
        "A shale hollow whose people carve poetry into mining shafts.",
        "A hilltop commune that prays facing opposite directions just in case.",
        "A crest hamlet whose wells are warmed by old arguments.",
        "A slope town where blacksmiths double as marriage counselors.",
        "A frostfield cluster that names avalanches like old friends.",
        "A storm-face hamlet whose roofs are scarred from years of musical rain.",
        "A ridge hollow that never stops building cairns for reasons forgotten.",
        "A limestone shelf town where tea is brewed with patience and regret.",
        "A goatpath village whose songs keep avalanches asleep.",
        "A hollow forged from two arguments that finally agreed to stay.",
        "A windswept crest where prayers are shouted so heaven won't feel superior.",
        "A hilltown where the anvil rings louder than bells or faith.",
        "A granite slope hamlet that believes every wound heals better at altitude.",
        "A frost-shadow hollow where the sun lingers reluctantly.",
        "A mountain pass outpost where every wall has ears—and an opinion.",
        "A ridge of ruins rebuilt every generation as an act of stubborn pride.",
        "A stone-cross settlement that marks seasons by the sound of sheep.",
        "A shale-crown hamlet where mirrors are banned for fear of hubris.",
        "A terrace forge-town where even silence sounds metallic.",
        "A windbite village that teaches children to curse kindly.",
        "A granite path hamlet where the ghosts pay taxes.",
        "A mountain hall where the air is thin and the politics thicker.",
        "A hillshadow cluster where snow melts in patterns that predict luck.",
        "A mining town that lost its vein but kept its songs.",
        "A rocky slope where the church bells ring only for fog.",
        "A crest hamlet that measures wealth in echoes returned.",
        "A hillfort town that pretends peace was its idea.",
        "A quarry hollow where goats and gods argue for ownership.",
        "A cliff hamlet where people wave to shadows instead of neighbors.",
        "A frostfold village where laughter keeps the snow from falling.",
        "A ridge commune that carves its laws into bedrock.",
        "A stone-road town where the wheelwright doubles as mayor by tradition.",
        "A hillside town where ghosts serve as night watch.",
        "A highfield hamlet that greets sunrise with bells of bone.",
        "A mountain face of homes clinging like faith to the rock.",
        "A slate-veined ridge where color itself is mined for paint.",
        "A lonely pass where even the wind must ask permission.",
        "A stone arch village whose walls remember each visitor's true name.",
        "A frost-peaked ridge where legends are as common as frostbite.",
        "A valley edge where rainbows are rationed like wine.",
        "A ridge road town where the smith and the priest are the same person.",
        "A scree field commune that swears at the sun and apologizes to the moon.",
        "A shale terrace whose bells toll for balance, not death.",
        "A mining hollow where birds refuse to sing until shift change.",
        "A misted ridge where roofs drip blessings all winter.",
        "A hill-mirror town where strangers are greeted as omens.",
        "A stone spine settlement that believes dreams cause earthquakes.",
        "A ridge market where goats outvote people in local elections.",
        "A quarry line town that buries its dead standing up.",
        "A slope commune where every family keeps one window open for the wind.",
        "A frostway hamlet that worships the echo more than the word.",
        "A hollow-built town where architecture is mostly apology.",
        "A hill-shadow hamlet that hosts an annual silence contest.",
        "A shale-trail commune that carves memorials for still-living neighbors.",
        "A ridgekeep town that pays taxes in song.",
        "A high path village where walking downhill is considered lazy.",
        "A terrace crossroads where goats have right of way by law.",
        "A mining camp turned monastery by accident and stubbornness.",
        "A mountain flank where children build windmills from bone.",
        "A frostfall village whose hearths are said to whisper names at dusk.",
        "A stone face hamlet that smiles only in summer.",
        "A ridgewell town where miners debate theology underground.",
        "A clifflight commune where every lantern burns a different sin.",
        "A scree-slope town whose elders carry hammers instead of canes.",
        "A hillpath hamlet where coins are shaped like prayers.",
        "A shale ring settlement where people speak in proverbs and sighs.",
        "A quarry drop town where only outsiders fear the cliffs.",
        "A highwind village that refuses to teach the word 'retreat.'",
        "A ridgebell hamlet where the bells are tuned to missing loved ones.",
        "A frostfold commune that hosts feasts in the blizzards.",
        "A cliff rim town where the loudest family wins the harvest blessing.",
        "A hollow ridge where homes are carved like punctuation marks.",
        "A wind trail town where hats and gossip fly freely.",
        "A quarry bench settlement where the sunset is treated as theater.",
        "A mountainside hamlet that believes every cough is a prophecy.",
        "A ridge hearth cluster that saves its warmth for strangers.",
        "A frost ridge where footprints never melt until debts are paid.",
        "A stone tooth hamlet that names storms after sinners."
    ],
    "water": [
        "A mist-wrapped fishing village that feeds on tide and rumor.",
        "A modest shore hamlet where nets and lies tangle alike.",
        "A damp settlement of creaking docks and patient eyes.",
        "A waterside village whose houses lean as if listening to the waves.",
        "A spray-kissed hamlet that smells of salt, smoke, and second chances.",
        "A village built around slips and boats instead of streets and carts.",
        "A low, weathered settlement where storms are both enemy and elder.",
        "A cluster of huts on stilts, rising and falling with the tide of fortune.",
        "A village that measures time by the shrieks of gulls and the groan of mooring lines.",
        "A marsh-fringed community that knows every channel by heart.",
        "A windswept settlement where every family keeps a boat and a story.",
        "A hamlet whose lanterns bob like captive stars over dark water.",
        "A village where the docks outnumber the streets.",
        "A water-brushed settlement that never fully dries.",
        "A shoreline cluster of buildings lashed together by rope and stubbornness.",
        "A village that smells of brine, tar, and quiet desperation.",
        "A settlement where children learn to swim before they can walk straight.",
        "A hamlet whose elders can read waves better than words.",
        "A village that sings to the horizon each dawn.",
        "A place where boats are mended more carefully than hearts.",
        "A coastal hamlet where nets are mended to songs of drowned sailors.",
        "A fog-heavy fishing village where boats vanish into mist without farewells.",
        "A reed-choked settlement that smells of salt and secrets.",
        "A jetty-bound village that burns lanterns for the lost.",
        "A shoreline hamlet where every wave brings both gifts and guilt.",
        "A waterline village that swears by the moon and the tide equally.",
        "A settlement of stilt-houses swaying like drunks in a breeze.",
        "A salt-streaked cluster of homes whose floors creak like ship decks.",
        "A wave-washed hamlet where children learn to curse storms before speech.",
        "A docktown where nets, gossip, and debts all tangle together.",
        "A seaside village where laughter is rarer than fish.",
        "A tidal hamlet that drowns and resurfaces with each moon.",
        "A small wharf community that keeps empty chairs for the sea's return.",
        "A fishing enclave that burns incense for good catch and easy ghosts.",
        "A pier town where driftwood is carved into saints and monsters alike.",
        "A wetland hamlet where herons outnumber humans.",
        "A fog-wreathed community whose bells ring underwater on calm nights.",
        "A floating market of boats tethered by rope, trade, and rumor.",
        "A cold bay settlement where waves sound suspiciously like whispers.",
        "A fisher's cove whose dead are buried at low tide to rise again at high.",
        "A tide-shifting hamlet whose nets catch more stories than fish.",
        "A marsh village afloat on wooden rafts, drifting but never lost.",
        "A delta settlement where children learn to swim before they can walk.",
        "A salt-sprayed hamlet where every boat bears a saint's name and a curse.",
        "A lagoon town whose markets float, moving with the tide's gossip.",
        "A wharf-line of shacks painted in the colors of past storms.",
        "A sea-mist village where bells warn of ghosts, not ships.",
        "A fishing pier that doubles as a courthouse when the tide's low.",
        "A brine-reek settlement that trades pearls for patience.",
        "A reed-roof cluster of homes where frogs out-sing drunks nightly.",
        "A coast-curve village where lanterns never go out—nor the debts.",
        "A boathouse borough that prays before voyages and after rumors.",
        "A fog-wrapped dockside where the dead still pay rent on time.",
        "A fishing hollow whose catch is rumored to whisper secrets.",
        "A tide-flat settlement where each plank was stolen from the same ship.",
        "A harborlet where storms are scheduled like festivals.",
        "A tidal island hamlet that forgets the mainland gladly twice a day.",
        "A jetty-bound outpost that treats drownings as apprenticeships.",
        "A floodplain community that has rebuilt so often the ghosts help.",
        "A driftwood enclave that sells both fish and forgiveness.",
        "A pier-ringed village that smells of salt, sin, and smoked eel.",
        "A bay-curve hamlet where boats are named for regrets.",
        "A fog-born settlement where the tide tells time better than bells.",
        "A harbor hollow that feeds its ghosts to the gulls.",
        "A sea-edge sprawl whose children whistle storms to sleep.",
        "A dock-line of huts raised higher each flood, like stubborn prayers.",
        "A lagoon-chain market where oaths are sealed with saltwater.",
        "A wetland town that brews liquor potent enough to drown memory.",
        "A tidepool hamlet whose fisherfolk swear by silence and salt.",
        "A kelp-smelling hollow that barters pearls for patience.",
        "A brackish cluster of houses painted blue against envy.",
        "A sand-bar village rebuilt after every tide as a test of faith.",
        "A mooring of rafts bound by rope and rumor.",
        "A gull-haunted harbor where news arrives faster than ships.",
        "A canal-cut hamlet whose reflections always arrive first.",
        "A tidal dock village that worships the moon as tax collector.",
        "A water-bend settlement built on drowned foundations and denial.",
        "A salt-flats commune that measures honesty by evaporation.",
        "A fish-stink borough where every roof bears a tale of rescue.",
        "A jetty town whose laughter sounds suspiciously rehearsed.",
        "A tide-flat market that sells fish, fortune, and forgiveness in equal weight.",
        "A mist-born port whose bells toll only for debts repaid.",
        "A marsh hamlet whose stilts groan like tired priests.",
        "A sand-spit settlement that moves with the moon's mood.",
        "A jetty of driftwood bound by rope and rumor.",
        "A lagoon of painted boats tethered to gossip instead of anchors.",
        "A bay village that lights three lanterns: one for trade, one for travel, one for return.",
        "A flood-plain commune rebuilt so often it celebrates collapse as renewal.",
        "A fog-pier town whose whistles are prayers for patience.",
        "A salt-reed hamlet that brews spirits strong enough to burn sea-demons.",
        "A wharf-line of shanties whose nets catch secrets as often as fish.",
        "A river-mouth village that keeps a shrine to every drowned traveler.",
        "A tidal hollow where roofs sway like sails in slow surrender.",
        "A brine-mist community that dyes fabrics with seawater and myth.",
        "A dockland of plank bridges that creak in perfect rhythm with the heart.",
        "A water-ring town where reflections whisper different answers.",
        "A bog-edge hamlet where will-o-wisps are treated as regular neighbors.",
        "A kelp-bay village whose currency is shells and well-kept rumors.",
        "A harbor hollow that closes each tide with a roll call of the living.",
        "A stilt-road market where seagulls act as tax collectors."
    ],
    "grassland": [
        "A sun-warmed grassland village whose herds wander freer than its people.",
        "A wind-swept hamlet of grain, gossip, and generational grudges.",
        "A broad, low settlement where fields are endless and patience is thin.",
        "A village ringed by fences that never quite hold.",
        "A plain-dwelling community that reads clouds like omens.",
        "A settlement where barns loom larger than homes.",
        "A hamlet that smells of cut hay, wet earth, and anxiety about the next harvest.",
        "A village spread lazily across gentle rises, as if it might nap between seasons.",
        "A place where the granaries are guarded like temples.",
        "A settlement that hears every distant hoofbeat as a question.",
        "A grassland village whose wells are deeper than its feuds.",
        "A hamlet where children chase chickens and gossip with equal fervor.",
        "A village that counts wealth in hooves and harvests.",
        "A thin line of homes along a dirt road, framed by endless fields.",
        "A settlement where scarecrows outnumber watchmen.",
        "A grassland hamlet where songs are sung mostly to the sky.",
        "A village that throws festivals whenever the weather cooperates.",
        "A community where bread is plentiful and sleep is rare.",
        "A hamlet that names every new calf and most of the wildflowers.",
        "A village that can smell rain hours before it appears.",
        "A plain hamlet where children chase dust devils for luck.",
        "A settlement that believes wind carries blessings if caught in cloth.",
        "A sprawling village whose pastures hum with unseen insects.",
        "A grassland community where fields sway like congregations.",
        "A windswept hamlet that celebrates every storm as an old friend.",
        "A settlement where shepherds whistle to stars instead of dogs.",
        "A plains village whose fences mark stories, not property.",
        "A sunny place that hides grief beneath easy smiles and grain.",
        "A road-hugging hamlet where carts never stop rolling.",
        "A fieldstead where harvest festivals last longer than marriages.",
        "A sun-dappled village where every loaf of bread has a name.",
        "A plainstead where clouds drift lazily and tempers quickly.",
        "A meadow settlement that counts blessings by bushels.",
        "A grassy expanse dotted with windmills creaking like old gods.",
        "A broad hamlet where every family knows the weight of drought.",
        "A granary village where generosity and gossip share tables.",
        "A settlement that swears the soil remembers good hands.",
        "A prairie hamlet that toasts each dawn in defiance of frost.",
        "A field village that buries its dead beneath rows of barley.",
        "A place where even the scarecrows seem to keep watch with purpose.",
        "A windsong hamlet whose fences hum when storms approach.",
        "A grain-sea village where harvests are measured in laughter.",
        "A shepherd's scatter of cottages linked by shared whistles.",
        "A road-touch settlement where every traveler leaves a proverb.",
        "A threshing-field town where barns double as theaters at dusk.",
        "A hay-scented community where the air itself seems half-asleep.",
        "A meadowstead where even scarecrows gossip.",
        "A sunny expanse of thatch and argument.",
        "A wagon-road hamlet that counts distance in broken wheels.",
        "A golden-field cluster that swears the soil itself sings.",
        "A pastoral ring where sheep and children stray equally.",
        "A grain-hill settlement that worships both plow and pint.",
        "A plaincross town whose wells reflect only the honest.",
        "A reaper's village that toasts the dead before the harvest.",
        "A roadside inn-hamlet that became a family and forgot travel.",
        "A fieldstead that dances every midsummer until dawn forgets itself.",
        "A grain-belt community ruled by elders and rainfall.",
        "A gentle hollow where bread smells sweeter than peace.",
        "A barley-road hamlet that stores gossip in granaries.",
        "A plainwatch village whose roosters crow in four dialects.",
        "A wind-bright hamlet where children race clouds for chores.",
        "A hay-meadow town that smells of sun, sweat, and mild deceit.",
        "A wagon-loop settlement born of caravans that forgot to leave.",
        "A hill-plain village that prays to both rain and restraint.",
        "A barley-rim town where every loaf hides a proverb.",
        "A threshing-barn commune that measures joy by echo length.",
        "A roadside haven whose fields bloom in alternating courage and fear.",
        "A wide-sky village where birds announce gossip.",
        "A prairiestead that whistles all night through its thatch.",
        "A plow-cut cluster where laughter grows faster than weeds.",
        "A low-ridge farmtown that swears storms choose it out of habit.",
        "A cross-field hamlet whose fences outline old feuds.",
        "A grain-gate outpost where generosity and hunger trade shifts.",
        "A meadow-road village that celebrates the color of dust.",
        "A plain-cross where travelers forget why they stopped.",
        "A cattle-line settlement that names its herds after saints and sins.",
        "A sun-baked fieldstead where faith is measured in furrows.",
        "A sheaf-stack hamlet proud of surviving without reason.",
        "A grass-hush borough that hides secrets in the rhythm of scythes.",
        "A high-pasture village where the wind keeps better records than scribes.",
        "A prairie crossroad whose signposts are carved from family trees.",
        "A hay-stacked hamlet where barns double as ballrooms after harvest.",
        "A grain-sea village whose laughter ripples like wind through wheat.",
        "A roadside cluster that trades bread, stories, and borrowed children.",
        "A shepherd's ring where flocks outnumber dreams.",
        "A sun-stung fieldstead that prays for rain and silence in equal measure.",
        "A plow-furrow community that names every blade of grass after ancestors.",
        "A plain-bend hamlet that toasts every sunrise as a small victory.",
        "A wagon-loop town where festivals circle endlessly without start or end.",
        "A scarecrow-line village whose effigies have opinions.",
        "A hill-meadow hollow that measures love in loaves shared.",
        "A wind-flute town whose fences hum all night in contentment.",
        "A harvest-turn hamlet where even shadows bend politely.",
        "A grain-road settlement that keeps a communal oven and collective memory.",
        "A wide-sky borough that greets thunder with applause.",
        "A seed-market town whose elders can predict frost by smell alone.",
        "A low-ridge community where windmills and gossip never stop turning.",
        "A shepherd's steppe hamlet that teaches patience as inheritance.",
        "A barley-plain hollow that drinks more stories than ale.",
        "A grass-swell cluster that throws feasts for migrating birds."
    ],
    "forest": [
        "A shaded forest hamlet where the trees keep older counsel than any elder.",
        "A lumber village that treats each felled tree as a quiet argument.",
        "A woodland settlement whose houses blend with trunks and shadow.",
        "A clearing-bound village surrounded by watchful branches.",
        "A moss-draped hamlet where lanterns glow like captive fireflies.",
        "A settlement where paths move subtly between visits.",
        "A forest village where every log bears a carved apology.",
        "A place where roots crack stone foundations in slow patience.",
        "A hamlet whose people walk softer than the falling leaves.",
        "A village that smells of sap, smoke, and secrets.",
        "A settlement whose dogs refuse to bark at the tree line.",
        "A community that hangs charms and bones from every eave.",
        "A forest-fringed village that listens more than it speaks.",
        "A hamlet where even the fences are woven from living branches.",
        "A village that glows faintly green at dusk.",
        "A settlement where birds carry messages no one admits sending.",
        "A woodland hamlet that swears the forest rearranges itself at night.",
        "A village that burns its dead with carefully chosen timber.",
        "A place where axes are sharpened reluctantly.",
        "A forest village where children grow up knowing which trees to greet by name.",
        "A canopy village lit by shards of filtered light and superstition.",
        "A glade settlement where mushrooms grow in perfect circles around secrets.",
        "A shadowed hamlet where footsteps fade faster than names.",
        "A woodland community that hums softly at dusk to appease unseen neighbors.",
        "A moss-hung village where whispers sound like wind in leaves.",
        "A forest hollow where trees bend protectively over rooftops.",
        "A root-tangled hamlet where paths shift under moonlight.",
        "A deepwood settlement whose hunters never whistle past dusk.",
        "A shaded village that measures time by birdsong instead of bells.",
        "A timberline hamlet where dreams wander farther than feet.",
        "A settlement whose fires burn green on festival nights.",
        "A sylvan hamlet where trees seem to lean closer to listen.",
        "A hidden glade town where tools are carved to resemble prayers.",
        "A settlement where elders swear the forest sighs in languages older than speech.",
        "A woodland village where every stump tells a story if you listen long enough.",
        "A deep forest hamlet where laughter sounds like trespass.",
        "A settlement stitched from roots and resolve.",
        "A grove community that paints charms on bark to keep spirits polite.",
        "A glenstead that smells of rain, soil, and quiet guilt.",
        "A woodland place where even birds pause mid-song to eavesdrop.",
        "A moss-soft village whose paths move when unobserved.",
        "A canopy hollow where birds teach prayers to children.",
        "A fern-ring hamlet hidden by design and superstition.",
        "A glenstead where roots break through every threshold.",
        "A deepwood town where hunters barter with shadows.",
        "A grove-built circle of cabins bound by vines and promises.",
        "A bark-carved settlement whose trees remember names aloud.",
        "A twilight hollow where even the fires burn quietly.",
        "A cedar-crowned hamlet that smells of rain and resin.",
        "A hollow-trunk refuge where light filters like judgment.",
        "A hidden glade where paths weave themselves anew each moon.",
        "A woodland refuge guarded by ravens and riddles.",
        "A root-path cluster where mushrooms mark sacred ground.",
        "A dimlight settlement that measures time by dewfall.",
        "A timber-knot hamlet that keeps a council of owls.",
        "A shadow-line village where laughter startles the trees.",
        "A briar-bordered community that paints its doors with warding runes.",
        "A green-fog village where songs are whispered leaf to leaf.",
        "A thicket settlement whose children vanish only to return wiser.",
        "A forest-edge town that leaves offerings for unseen listeners.",
        "A twilight glen where lanterns swing from patient branches.",
        "A cedar-heart hamlet perfumed with secrecy and sap.",
        "A fern-floor settlement where no one walks the same path twice.",
        "A hollow-root village that trades honey, herbs, and half-truths.",
        "A birch-ring town that claims to hear the forest dreaming.",
        "A bark-sheltered commune where dawn arrives in whispers.",
        "A moss-glow cluster that hosts feasts for unseen guests.",
        "A thorn-hedge hamlet whose laughter startles the wildlife.",
        "A green-shaded settlement where even shadows seem polite.",
        "A root-woven village that hums softly after rainfall.",
        "A forest-bend hamlet where children vanish to play with spirits.",
        "A canopy-niche town whose roofs are stitched from leaves and lore.",
        "A glen-road outpost that pays tolls to ancient trees.",
        "A lichen-stone hamlet where doors grow tighter each winter.",
        "A hollow-oak borough that glows faintly with remembered fire.",
        "A sylvan refuge whose watchmen speak only in gestures.",
        "A fog-bound glade where memory thickens like sap.",
        "A twilight settlement built around a fallen star's crater.",
        "A pine-crest hamlet where snow melts reluctantly and stories linger.",
        "A forest-edge village that swears the wind sings names at dusk.",
        "A root-bound hamlet where trees hum lullabies after rain.",
        "A fern-curtain village hidden so well even maps whisper.",
        "A canopy-step commune where children learn silence before speech.",
        "A glade-ring town that feeds its dead to the soil as thanks.",
        "A hollow-trunk borough that glows faintly with foxfire.",
        "A vine-bridge settlement whose boundaries sway like morals.",
        "A moss-bloom hamlet where the air tastes of honey and caution.",
        "A leaf-crowned hollow that celebrates twilight as its true dawn.",
        "A timber-nest village where roofs are grown, not built.",
        "A briar-gate town whose watchmen prune as often as they fight.",
        "A grove-road cluster where elders speak with their backs to the trees.",
        "A pine-hush borough that counts snowfall instead of time.",
        "A fog-thread hamlet where no one has seen the same deer twice.",
        "A shadow-glade community that trades mushrooms for news.",
        "A twilight-ring town that hosts bonfires only under full moons.",
        "A cedar-scented commune that measures virtue by the quiet kept.",
        "A forest-bend hamlet whose hunters swear the woods listen back.",
        "A glen-shadow village where lanterns float instead of hang.",
        "A hollow-oak settlement that stores songs in knots of wood.",
        "A bark-etched town that tattoos its history directly into trees."
    ]
}

village_templates["hills"].extend([
    "A ridge-line hamlet that speaks to clouds before each harvest.",
    "A stony rise where families pass down echoes instead of heirlooms.",
    "A mountain-step village that paints its doors red for luck and forgiveness.",
    "A frost-leaning town whose sheep wear bells tuned to grief.",
    "A cliff-brow hamlet that lights torches so the stars won't feel lonely.",
    "A slate-path hollow that greets strangers with riddles instead of names.",
    "A mine-entrance village where every newborn is given a lump of ore to keep them grounded.",
    "A wind-bent ridge where laughter is the only thing that travels uphill.",
    "A shale-cliff town whose oldest house refuses to die, no matter the storm.",
    "A ridge-hollow hamlet where elders claim thunder is ancestral applause.",
    "A limestone terrace village that marks births with stones instead of candles.",
    "A ridge of shepherd huts that creak like violins in the cold.",
    "A hollowed crest where walls hum faintly when secrets are told.",
    "A mountainside hamlet where goats are considered partial reincarnations.",
    "A quarry lip settlement that still remembers the sound of its first hammer.",
    "A windy pass where voices echo three times for truth, twice for lies.",
    "A terrace-line town where houses grow taller as the families shrink.",
    "A shale hollow whose people carve poetry into mining shafts.",
    "A hilltop commune that prays facing opposite directions just in case.",
    "A crest hamlet whose wells are warmed by old arguments.",
    "A slope town where blacksmiths double as marriage counselors.",
    "A frostfield cluster that names avalanches like old friends.",
    "A storm-face hamlet whose roofs are scarred from years of musical rain.",
    "A ridge hollow that never stops building cairns for reasons forgotten.",
    "A limestone shelf town where tea is brewed with patience and regret.",
    "A goatpath village whose songs keep avalanches asleep.",
    "A hollow forged from two arguments that finally agreed to stay.",
    "A windswept crest where prayers are shouted so heaven won't feel superior.",
    "A hilltown where the anvil rings louder than bells or faith.",
    "A granite slope hamlet that believes every wound heals better at altitude.",
    "A frost-shadow hollow where the sun lingers reluctantly.",
    "A mountain pass outpost where every wall has ears—and an opinion.",
    "A ridge of ruins rebuilt every generation as an act of stubborn pride.",
    "A stone-cross settlement that marks seasons by the sound of sheep.",
    "A shale-crown hamlet where mirrors are banned for fear of hubris.",
    "A terrace forge-town where even silence sounds metallic.",
    "A windbite village that teaches children to curse kindly.",
    "A granite path hamlet where the ghosts pay taxes.",
    "A mountain hall where the air is thin and the politics thicker.",
    "A hillshadow cluster where snow melts in patterns that predict luck.",
    "A mining town that lost its vein but kept its songs.",
    "A rocky slope where the church bells ring only for fog.",
    "A crest hamlet that measures wealth in echoes returned.",
    "A hillfort town that pretends peace was its idea.",
    "A quarry hollow where goats and gods argue for ownership.",
    "A cliff hamlet where people wave to shadows instead of neighbors.",
    "A frostfold village where laughter keeps the snow from falling.",
    "A ridge commune that carves its laws into bedrock.",
    "A stone-road town where the wheelwright doubles as mayor by tradition.",
    "A hillside town where ghosts serve as night watch.",
    "A highfield hamlet that greets sunrise with bells of bone.",
    "A mountain face of homes clinging like faith to the rock.",
    "A slate-veined ridge where color itself is mined for paint.",
    "A lonely pass where even the wind must ask permission.",
    "A stone arch village whose walls remember each visitor's true name.",
    "A frost-peaked ridge where legends are as common as frostbite.",
    "A valley edge where rainbows are rationed like wine.",
    "A ridge road town where the smith and the priest are the same person.",
    "A scree field commune that swears at the sun and apologizes to the moon.",
    "A shale terrace whose bells toll for balance, not death.",
    "A mining hollow where birds refuse to sing until shift change.",
    "A misted ridge where roofs drip blessings all winter.",
    "A hill-mirror town where strangers are greeted as omens.",
    "A stone spine settlement that believes dreams cause earthquakes.",
    "A ridge market where goats outvote people in local elections.",
    "A quarry line town that buries its dead standing up.",
    "A slope commune where every family keeps one window open for the wind.",
    "A frostway hamlet that worships the echo more than the word.",
    "A hollow-built town where architecture is mostly apology.",
    "A hill-shadow hamlet that hosts an annual silence contest.",
    "A shale-trail commune that carves memorials for still-living neighbors.",
    "A ridgekeep town that pays taxes in song.",
    "A high path village where walking downhill is considered lazy.",
    "A terrace crossroads where goats have right of way by law.",
    "A mining camp turned monastery by accident and stubbornness.",
    "A mountain flank where children build windmills from bone.",
    "A frostfall village whose hearths are said to whisper names at dusk.",
    "A stone face hamlet that smiles only in summer.",
    "A ridgewell town where miners debate theology underground.",
    "A clifflight commune where every lantern burns a different sin.",
    "A scree-slope town whose elders carry hammers instead of canes.",
    "A hillpath hamlet where coins are shaped like prayers.",
    "A shale ring settlement where people speak in proverbs and sighs.",
    "A quarry drop town where only outsiders fear the cliffs.",
    "A highwind village that refuses to teach the word 'retreat.'",
    "A ridgebell hamlet where the bells are tuned to missing loved ones.",
    "A frostfold commune that hosts feasts in the blizzards.",
    "A cliff rim town where the loudest family wins the harvest blessing.",
    "A hollow ridge where homes are carved like punctuation marks.",
    "A wind trail town where hats and gossip fly freely.",
    "A quarry bench settlement where the sunset is treated as theater.",
    "A mountainside hamlet that believes every cough is a prophecy.",
    "A ridge hearth cluster that saves its warmth for strangers.",
    "A frost ridge where footprints never melt until debts are paid.",
    "A stone tooth hamlet that names storms after sinners."
])

village_templates["water"].extend([
    "A tide-bend hamlet whose prayers are whispered between waves.",
    "A salt-marsh village that keeps its dead tied to the docks until the next tide.",
    "A fog-drift town where gulls carry gossip faster than rumor.",
    "A reed-hut community that swears every ripple is a soul returned.",
    "A lantern-lined pier that measures time by tides and tempers.",
    "A brine-soaked borough that baptizes all newcomers unwillingly.",
    "A tide-flip town where boats outnumber children three to one.",
    "A jetty-end hamlet whose coins rust faster than memories.",
    "A fisher's cove where nets catch both fish and omens.",
    "A lagoon-edge cluster that trades shells like currency and silence like gold.",
    "A sand-bar settlement rebuilt nightly with resigned joy.",
    "A shanty port where sailors swear the moon owes back rent.",
    "A wave-break village that worships calm seas the way others fear gods.",
    "A tidal market whose goods are stamped with seaweed and regret.",
    "A kelp-harbor hamlet that paints every door blue against envy.",
    "A dock-run town where drunks double as prophets.",
    "A wharf-row commune where lanterns float away carrying apologies.",
    "A coastal hollow where children learn to swim before they can lie.",
    "A sea-wind borough whose houses creak lullabies to the tide.",
    "A mist-port village that charges for shelter but not forgiveness.",
    "A shipyard hamlet where broken masts are turned into memorials.",
    "A river-mouth outpost that feeds the capital its salt and stories.",
    "A boat-chain community that drifts as one organism of gossip.",
    "A marshline hamlet whose people eat fish seasoned with philosophy.",
    "A flood-plain settlement where memory is measured in mud.",
    "A sandspit town where fishermen sing dirges as work songs.",
    "A storm-toss port that celebrates the day after every disaster.",
    "A lighthouse village that never built a lighthouse — superstition forbids it.",
    "A wetland commune where eels are considered omens of wealth and warning.",
    "A coral-edge hamlet that keeps its myths under water pressure.",
    "A tidal flat where crab-shells serve as currency and confessionals.",
    "A pier-end shanty where lost sailors come home only in fog.",
    "A waterway town that swears its river has moods and opinions.",
    "A harbor hollow where time and tide are worshiped as twins.",
    "A sea-rim town where shipwrecks are recycled into shrines.",
    "A dockside village whose oldest family is descended from the current.",
    "A coastal bend commune that paints murals directly on the surfboards of saints.",
    "A tide-road town that trades pearls for patience and salt for secrets.",
    "A mangrove hamlet that feeds its ancestors through the roots.",
    "A wind-wave port where fishing and fortune-telling are the same profession.",
    "A raft-borne town that drifts closer to land every year but never arrives.",
    "A harbor step village where every lantern burns the name of a lost ship.",
    "A bay-mouth settlement whose streets flood daily by design.",
    "A canal-city miniature where bridges gossip louder than people.",
    "A salt-river commune where the tides sing their own hymns.",
    "A delta-hollow hamlet that measures honesty in the clarity of water.",
    "A fisher's stretch that marks borders with bottles and bones.",
    "A beach-row town where the tide collects taxes more fairly than kings.",
    "A wharfline hollow that smells of ale, fish oil, and half-kept promises.",
    "A driftwood commune that treats storms as visiting cousins.",
    "A tide-sleep town where the sea sings lullabies louder than mothers.",
    "A brine hollow village where barrels are coffins reused and blessed.",
    "A low-coast commune whose roofs grow barnacles from long neglect.",
    "A saltspun hamlet whose elders navigate by scent alone.",
    "A sea-wrack town that honors the moon as its only true mayor.",
    "A dock-hollow village that welcomes storms with open cellars.",
    "A tide-spill borough where ropes and prayers are knotted the same way.",
    "A sandbar commune where even laughter is rationed by the tide.",
    "A reeffront town that counts its children by the waves that returned them.",
    "A pierstep hamlet where every home has a map of shipwrecks as family tree.",
    "A shell-line settlement that tells fortunes by listening to empty conches.",
    "A fogwhisper port whose church bells only ring underwater.",
    "A marsh-bridge town that barters frogs, rumor, and old boots.",
    "A kelp-forest harbor whose citizens sleep on swinging hammocks of weed.",
    "A tide-rest settlement where every departing boat receives a blessing and a curse.",
    "A brackish-port village that salutes the sunset like an old captain.",
    "A sea-glass commune that collects broken bottles as offerings.",
    "A lagoon-run borough that hosts duels between rival poets at dawn.",
    "A mist-corner hamlet where children wear seaweed wreaths for courage.",
    "A driftport settlement that floats just far enough to avoid taxes.",
    "A gull-call town whose council meets only during low tide.",
    "A fishing chain community that counts its history in storms survived.",
    "A waterline hamlet whose church sits perpetually half-drowned.",
    "A tideplain village where every doorframe is painted against curses.",
    "A ferry-pass town that swears every crossing changes fate slightly.",
    "A shipbone borough built from wreckage and determination.",
    "A dockland ring that celebrates the tide's return like a lover forgiven.",
    "A seafoam commune where laughter is considered good luck for storms.",
    "A harbor-step hamlet where merchants weigh goods by heartbeats.",
    "A salt-trade town whose fishwives settle disputes with riddles.",
    "A flood-rim settlement whose bridges double as stages for confession.",
    "A brine-swept port where everyone hums the same song without knowing why.",
    "A channel-bend village that collects driftwood shaped like saints.",
    "A lighthouse bay town that rings bells when the fog dreams too loudly.",
    "A dockhill settlement whose seawalls are carved with love letters.",
    "A tidewatch hamlet whose clocks are all set by moonlight.",
    "A seabed community that surfaces only for festivals and funerals.",
    "A sea-arch hamlet that swears whales carry their ancestors' names.",
    "A beachshadow village where ghosts walk at dawn to gather shells.",
    "A gull-shade port whose inns serve memory stronger than wine.",
    "A pierfront hamlet that worships both storm and stillness equally.",
    "A kelp-ring commune where each marriage is blessed with saltwater tears.",
    "A riverdelta settlement that keeps journals written in tide lines.",
    "A stormwharf village whose mayor is chosen by lottery and lightning.",
    "A foamcrest borough where each newborn is given a shell and a warning.",
    "A sandtrail town that pretends the sea has never taken anything.",
    "A reefroad hamlet that mends its nets and its hearts with the same knot.",
    "A floodbank commune that carves charms from driftwood saints.",
    "A mistshore town where no one whistles after dark.",
    "A harborway hamlet where sailors tattoo each other's mistakes.",
    "A jettybend settlement that argues daily with seagulls for space.",
    "A tidebeam village that glows faintly blue when storms approach.",
    "A brinewall commune whose children learn to read the foam's handwriting.",
    "A seaeye hamlet that believes pearls form from tears of forgiven lies.",
    "A dockbloom town where gardens grow in barrels and blessings.",
    "A tidewreath community that rings laughter bells after funerals.",
    "A wave-edge borough whose watchmen sing to measure windspeed.",
    "A shellwalk hamlet where every pebble is painted for luck.",
    "A surfshadow village that carves oaths into boat keels.",
    "A tidebranch town where traders speak in whistles over waves.",
    "A mistveil hamlet whose fishermen swear the fog follows orders.",
    "A breakerfront village where driftwood is used as scripture.",
    "A saltmark commune where candles float each night for unreturned sailors.",
    "A reefgate hamlet that marks years by coral growth instead of calendars.",
    "A brineveil town whose elders carve faces into seaweed knots.",
    "A surfrest borough that hears thunder before it's born.",
    "A tidecrest commune that uses mirrors to greet the moon.",
    "A washstrand town where water writes its own laws on the sand.",
    "A sea-turn hamlet that toasts the dead with stormwater.",
    "A dockshrine settlement where bells toll backward for mercy.",
    "A coralspan village that trades songs for seawater cures.",
    "A sandglow town whose walls shimmer with salt like jewels.",
    "A netweaver hamlet that braids dreams into rope for safety.",
    "A fogmouth port that tastes like memory and molasses.",
    "A tidehush commune whose priests can calm waves with silence.",
    "A pierdrift village where seagulls act as omens for traders.",
    "A wharfshadow hamlet whose alleys smell like regret and rum.",
    "A surfveil town where the wind tells fortunes through shutters.",
    "A seafoam hamlet where the fishermen name every storm lovingly.",
    "A tidegrove commune built around mangroves older than legend.",
    "A jettycurve village that measures luck by how long laughter lasts.",
    "A mistgate hamlet whose children learn to speak fog-language.",
    "A tidewalk town that throws coins to the waves before each meal.",
    "A brinecross village that brews liquor strong enough to bargain with gods.",
    "A reefspoke commune that calls the ocean 'Grandmother Debt.'",
    "A saltfen town whose pigs are rumored to dream of swimming.",
    "A wavebend village where every family keeps a bucket 'just in case.'",
    "A dockpost hamlet where seagulls steal bread and letters alike.",
    "A foamveil port whose mayor hasn't spoken since the last shipwreck.",
    "A tidechant community that teaches children to curse politely at storms.",
    "A sea-trace hamlet where the horizon feels closer after dark.",
    "A wavepath village whose inns smell of pepper, tar, and memory.",
    "A dockveil town where bells only ring when ships go missing.",
    "A tidalroot commune that believes mud can remember kindness.",
    "A floodline settlement whose every lantern has a name.",
    "A tidebloom village whose salt marsh glows faintly in moonlight."
])

village_templates["grassland"].extend([
    "A wheat-ring hamlet that counts years by the depth of laughter in barns.",
    "A wind-plain village where the dogs outthink the shepherds.",
    "A crossroads town that holds three festivals and one argument every week.",
    "A hayfield commune that blesses travelers with dust and directions.",
    "A wagon-circle market where rumors and bread rise together.",
    "A stubble-plain village that swears the wind carries advice from the dead.",
    "A field-path hamlet whose fences lean inward from too much listening.",
    "A barley-crest town where songs are taxes paid in rhythm.",
    "A thresher's ridge where grain and gossip are measured by the bushel.",
    "A meadow-road borough that trades silence for shade.",
    "A pastureline hamlet where children chase mirages for sport.",
    "A sun-track commune that forgives drought faster than deceit.",
    "A plow-bend village that swears its soil remembers every promise.",
    "A hay-scent town that dreams of oceans it will never see.",
    "A shepherd's rest settlement where sheep outvote people on holy days.",
    "A wind-trail hamlet where rooftops hum hymns to approaching rain.",
    "A grain-loop town that toasts lightning for good harvest.",
    "A dust-ridge village whose wells taste faintly of hope.",
    "A meadow-cross commune that prays to both sun and seed equally.",
    "A chaff-road hamlet that names every scarecrow after saints.",
    "A harvest-gate village that greets travelers with pie and interrogation.",
    "A steppe-line town where horses are taught politics early.",
    "A long-furrow settlement whose only crime is boredom and bread theft.",
    "A plain-crest commune that judges honesty by handshake weight.",
    "A wheat-sweep hamlet that hosts races between storms.",
    "A farm-lane borough whose barns double as ballrooms after dusk.",
    "A sheaf-road town that sells sunrise in jars for luck.",
    "A low-plain settlement where every well has its own joke.",
    "A fence-row hamlet that weaves disputes into wicker baskets.",
    "A horizon-edge town that toasts sunsets with reckless gratitude.",
    "A dust-mile hamlet that marks its dead with windmills.",
    "A field-bend commune that never mows the grass where lovers argued.",
    "A harvest-drift village that smells of ale and absolution.",
    "A wind-brim town where songs are harvested alongside grain.",
    "A cattle-trail settlement that believes hoofbeats ward off loneliness.",
    "A hay-bale hamlet that hides its grief in humor.",
    "A corn-path village that treats scarecrows as minor officials.",
    "A wheat-meadow commune where barns whisper when no one watches.",
    "A grass-hush hamlet whose prayers are shouted only into the wind.",
    "A low-hill settlement that sees rainbows as divine signatures.",
    "A wide-plain borough where laughter is the main export.",
    "A straw-stack town whose fires start and end every legend.",
    "A plow-row hamlet that thanks its tools by name each winter.",
    "A steppe-bend commune that sings to clouds as they pass judgment.",
    "A wind-bend village where roofs creak arguments to the sky.",
    "A pasture-gate town that teaches patience through drought.",
    "A hay-ridge hamlet that paints barns red for vanity, white for mourning.",
    "A farm-bend settlement that pays taxes in flour and folk tales.",
    "A sun-trail village where shadows work the night shift.",
    "A plain-run town where each household keeps a sacred loaf from the last harvest.",
    "A grain-bend commune that celebrates storms as free irrigation.",
    "A pasture-song hamlet where fiddles are considered medical instruments.",
    "A wind-turn settlement that whistles prophecies through cracks in fences.",
    "A straw-road village whose barns double as archives of gossip.",
    "A meadow-bend town that plants flowers on every fence post for luck.",
    "A field-ring commune that greets thunder as a beloved drunk uncle.",
    "A dust-trail hamlet where even the horses know all the jokes.",
    "A wagon-way village that bakes bread shaped like the horizon.",
    "A thresh-bend town whose barns sway like drunk giants in the wind.",
    "A plow-cross hamlet where every furrow points home.",
    "A prairie-bend commune that names winds instead of children.",
    "A straw-ridge village where the only theft is time.",
    "A field-line town that holds arguments during harvest for efficiency.",
    "A sun-road borough where every window frame is a poem about endurance.",
    "A grain-path hamlet that swears moonlight helps wheat grow.",
    "A wide-meadow commune that throws its weddings at noon to shame the sun.",
    "A hay-lane village where gossip moves faster than wind.",
    "A dirt-road town that remembers rain like religion.",
    "A pasture-ring hamlet that thanks storms before cursing them.",
    "A low-plain commune that writes wills in seed script.",
    "A wind-hollow village whose scarecrows are rumored to sing in moonlight.",
    "A field-crest town where honesty and hunger share the same proverb.",
    "A barley-trail hamlet that blesses strangers with dusted bread.",
    "A grain-line commune where every generation builds one more windmill.",
    "A plain-bend town that believes kindness grows wild if watered with patience.",
    "A meadow-rest hamlet that marks birthdays by crop height.",
    "A field-span commune that teaches generosity through leftovers.",
    "A wheat-road borough where weddings are paid in song.",
    "A dust-bend town that praises blisters as proof of prayer.",
    "A hay-swell village that considers lightning a personal compliment.",
    "A pasture-bend commune whose fences keep more ghosts than animals.",
    "A wind-crest hamlet that toasts frost as if it were a guest.",
    "A grain-bridge town whose elders smell rain before clouds arrive.",
    "A plow-ridge village that greets drought with stubborn laughter.",
    "A straw-hill commune that holds festivals in thunder season.",
    "A field-gate town that names each furrow after an ancestor.",
    "A horizon-bend hamlet that hosts moonlit markets for wandering spirits.",
    "A wheat-trail commune that mends its roofs with patience and prayer.",
    "A prairie-lane village where song replaces law.",
    "A pasture-ridge settlement that waves at passing storms for luck.",
    "A meadow-span hamlet whose inns serve nostalgia instead of ale.",
    "A dust-path commune that refuses to admit defeat even to the wind.",
    "A field-bend borough where faith is measured in furrows kept straight.",
    "A hay-plain village where children compete to name the clouds.",
    "A grain-trail commune that hosts annual debates between farmers and philosophers.",
    "A wind-line hamlet that greets every dawn like a reunion.",
    "A pasture-crest town that thanks every tool before storage.",
    "A plow-bend commune that tracks love affairs by harvest yield.",
    "A wheat-ridge hamlet that paints the sunrise on barn doors for courage.",
    "A meadow-hush town that considers silence a crop worth tending.",
    "A straw-plain settlement whose scarecrows are rumored to dream.",
    "A grain-crest commune where every roof beam hums during storms.",
    "A prairie-trail hamlet that holds fairs for wind-sculptures made of straw.",
    "A dust-line town where all directions eventually lead to laughter.",
    "A pasture-bend hamlet that trades recipes for forgiveness.",
    "A wheat-ring commune that marks seasons with festivals of gratitude.",
    "A hay-ridge village that writes its history in chalk on barn doors.",
    "A field-crest hamlet whose wells taste faintly of optimism.",
    "A grain-bend settlement that treats patience as its primary export.",
    "A plain-span commune where even the cats nap facing the sun.",
    "A straw-trail hamlet whose church is built from old plows.",
    "A dust-bend town where the mayor is always a retired farmer.",
    "A hay-path commune that hosts lullabies instead of sermons.",
    "A meadow-ridge settlement that swears each sunrise is unique.",
    "A wheat-line hamlet that thanks strangers with pies instead of prayers.",
    "A pasture-bend commune where storms and weddings share musicians.",
    "A grain-sweep town that sells wind-tamed whistles as souvenirs.",
    "A field-crest hamlet that measures honesty in calluses.",
    "A dust-trail village that treats laughter as sacred noise.",
    "A hay-road commune where rainbows are considered IOUs from heaven.",
    "A plain-path borough where every heart knows at least one lullaby.",
    "A plow-ridge hamlet that forgives its mistakes by sunrise.",
    "A pasture-plain commune where no one locks doors but everyone shares bread."
])

village_templates["forest"].extend([
    "A moss-hush hamlet whose children are taught to bow before new saplings.",
    "A glen-wrapped village where laughter echoes softer than leaves.",
    "A root-bound commune that claims the trees remember kindness longer than people.",
    "A barklight town whose lanterns are fed with sap and patience.",
    "A fern-shadow hamlet that never burns wood from its own forest.",
    "A grove-step settlement where owls deliver messages of apology.",
    "A hollow-light village that carves prayers into acorns before planting them.",
    "A dewveil hamlet that greets every sunrise in whispered gratitude.",
    "A bramblegate town whose fences are alive and growing still.",
    "A canopy-ring village that celebrates twilight like a wedding feast.",
    "A rootpath commune that swears mushrooms are the forest's punctuation.",
    "A lichenwall hamlet where stories are painted in bioluminescence.",
    "A mistleaf village that marks time by how fast moss climbs its roofs.",
    "A greenveil borough where silence is considered the highest form of art.",
    "A woodshade town whose elders speak only when the wind approves.",
    "A hollowrest village where no axe has been lifted in living memory.",
    "A pinebloom commune that bakes bread flavored with resin and reverence.",
    "A glenroad hamlet where strangers are welcomed with cups of rainwater.",
    "A forestbend town whose people leave food at crossroads for unseen travelers.",
    "A leafgate village where even the paths have opinions about gossip.",
    "A mistwoven hamlet where fog is treated like an old relative.",
    "A bramblefold borough whose roofs are thatched with caution and pride.",
    "A twigpath village where every fallen branch is given a name.",
    "A cedarway commune that burns incense of gratitude before storms.",
    "A grovehold hamlet where the night watch are accompanied by wolves.",
    "A barkveil town whose residents sing lullabies to the soil.",
    "A hollowvine village where the vines themselves seem to listen.",
    "A fernpath commune that believes all echoes belong to ghosts.",
    "A treeshade hamlet that grows gardens only in moonlight.",
    "A mossbend borough that buries promises under oak roots.",
    "A forestlane town where candles are replaced by jars of fireflies.",
    "A hollowoak village that never tells the same story twice.",
    "A pinecrest commune where snow is treated as visiting royalty.",
    "A glenveil hamlet where every house has its own spirit tree.",
    "A branchroad village that measures distance in bird calls.",
    "A cedarcrest town where woodcarvers are regarded as priests.",
    "A mossroad hamlet that believes sleep is a sacred act of trust.",
    "A fernridge commune that plants a tree for every broken heart.",
    "A glenbend town that celebrates silence with feast and flute.",
    "A treeroot hamlet where letters are carried by squirrels trained on almonds.",
    "A woodtrail village that paints doors green for good luck and guilt.",
    "A hollowstem commune whose harvest is measured in wild honey.",
    "A pineveil borough where it is rude to walk louder than rain.",
    "A bramblepath hamlet that celebrates birthdays under fallen logs.",
    "A mossgate village where shoes are removed before entering the forest proper.",
    "A shadowbend commune that believes whispers travel faster in leaflight.",
    "A lichenveil town whose wells are fed by patience and dew.",
    "A grovepath hamlet where bonfires are lit in silence.",
    "A woodhollow borough that hosts night markets for wandering dreams.",
    "A treelight commune that believes trees choose their own caretakers.",
    "A rootbend hamlet where even the tools are carved to sing.",
    "A glenmist town where no one speaks the same name twice.",
    "A forestheart hamlet that hosts festivals for forgotten gods.",
    "A ferncrest commune where each harvest begins with a moment of mourning.",
    "A barkbend town where paper is outlawed and memory revered.",
    "A brambleveil hamlet that teaches songs older than language.",
    "A woodbloom village where nightingales act as judges for disputes.",
    "A mossveil commune that weaves its roofs from vines that bloom at dusk.",
    "A treebend hamlet where strangers must gift a seed to enter.",
    "A hollowbranch village that buries its dead in hollow logs facing sunrise.",
    "A pinepath town that leaves offerings of salt for winter spirits.",
    "A groveveil commune that records history by tattooing tree bark.",
    "A forestrest hamlet that regards dreams as communal property.",
    "A mistpath town where travelers leave a hair for luck.",
    "A barkshadow borough that uses tree rings to measure memory.",
    "A treerest hamlet where children carve toys for forest sprites.",
    "A fernvale commune that lights candles to lure wandering stories home.",
    "A glencrest village that hides one empty chair for the unseen listener.",
    "A pinebend hamlet where silence is broken only by flute or fox.",
    "A bramblebend borough that hosts weddings by owl-call.",
    "A rootveil town that believes illness is cured by forest apology.",
    "A woodveil hamlet where every rain is a kind of baptism.",
    "A treefold commune where carpenters build instruments, not furniture.",
    "A hollowveil village where water flows uphill on certain days.",
    "A grovebend hamlet where all the roads are kind but confusing.",
    "A lichenrest commune that writes love poems in moss script.",
    "A glenpath town where harvests are weighed in laughter and patience.",
    "A barkcrest hamlet that swears its shadows hum with memory.",
    "A fernveil borough that trades mushrooms for poetry.",
    "A mistgrove hamlet where foxes are treated as envoys of gods.",
    "A treeshade commune that names fires as if they were guests.",
    "A rootgate village where children are forbidden to lie under old oaks.",
    "A hollowpath hamlet whose midwife is said to speak fluent bird.",
    "A grovebend town that marks time with migrating deer.",
    "A pineveil hamlet that treats thunder as distant applause.",
    "A woodroad commune where no tree has ever been cut twice.",
    "A ferncrest hamlet where they paint prayers on spider silk.",
    "A mosslane town that mends roofs with patience and ivy.",
    "A rootveil commune where night is measured in owl calls.",
    "A treeroad hamlet that forbids metal after sundown.",
    "A hollowbend village that sings its news each morning.",
    "A barkveil borough that carves blessings into mushrooms for visitors.",
    "A grovecrest hamlet that lights fires only with ancient permission.",
    "A fernshade commune where every home keeps a secret root beneath the hearth.",
    "A mosspath hamlet whose hunters apologize to their arrows.",
    "A hollowroot town where the trees glow faintly when people tell the truth.",
    "A pinebend commune where strangers are addressed as cousins.",
    "A forestgate village that trades dew as currency.",
    "A glenveil hamlet that speaks in songs instead of goodbyes.",
    "A treehollow borough that believes each child has a guardian leaf.",
    "A fernbend hamlet where laughter is forbidden during eclipse.",
    "A woodveil commune that stores dreams in glass jars under beds.",
    "A barktrail village where every meal begins with a toast to the forest.",
    "A mossshadow hamlet that counts time by cicada song.",
    "A glenveil commune that paints its doors with sap and intention.",
    "A rootbend town that celebrates storms as the forest's heartbeat.",
    "A treeveil hamlet where light bends around elders respectfully.",
    "A brambleveil borough that trades honey for secrets.",
    "A woodrest hamlet that greets each dawn with bells made of shells.",
    "A pinehollow commune that never cuts down trees—only waits for volunteers.",
    "A mossveil village that forgives everything except axes.",
    "A groveveil hamlet whose wells reflect only honesty.",
    "A fernpath borough that hosts silent dances in moonlight.",
    "A treeridge hamlet that names the wind as a god's messenger.",
    "A barkveil commune that rewards children for stillness.",
    "A hollowbend town whose elders claim trees dream louder after rain.",
    "A forestveil village that builds bridges from fallen branches as memorials.",
    "A lichenveil hamlet that measures time by sap flow.",
    "A glenpath commune that plants flowers on the graves of forgotten stories.",
    "A pinecrest hamlet where thunder is translated into riddles.",
    "A fernveil town that guards its paths with candle jars instead of soldiers.",
    "A rootveil borough that counts blessings by shade, not sunlight.",
    "A treecrest village that gives names to winds before they arrive.",
    "A mossveil hamlet that teaches patience as the forest's first rule."
])

village_flavor = {
    "hills": [
        "They say the mountain remembers who takes without thanks.",
        "No one whistles in the mines; that's how spirits answer.",
        "The rocks hum before a cave-in, if anyone is listening.",
        "Children learn to fear silence underground more than any noise.",
        "Old miners insist the stone shifts to protect those it favors.",
        "They leave offerings at the shaft mouths for luck and forgiveness.",
        "Stories circulate of tunnels that appear only when truly needed.",
        "The elders can tell tomorrow's yield by tonight's echoes.",
        "A curse here is always thrown downward into the dark.",
        "They swear some veins pulse like living things when struck."
    ],
    "water": [
        "They pour ale to the water before drinking themselves.",
        "Fishers swear some nets pull memories instead of fish.",
        "They bury their dead facing the horizon, waiting for one last tide.",
        "The gulls cry names that no one has used in years.",
        "Storms are greeted with muttered apologies and nailed shutters.",
        "Children learn early which waves are friendly.",
        "They say the water keeps every secret dropped into it.",
        "Boats are patched as lovingly as wounds.",
        "No one turns their back on the sea when speaking of it.",
        "They swear that once, the tide went out and never fully came back."
    ],
    "grassland": [
        "They still bless their fields with ash from the hearth.",
        "Stories travel faster than the wind here.",
        "Everyone knows everyone's business, and most wish they didn't.",
        "They keep one barn empty, just in case a miracle needs storage.",
        "They say the grass carries whispers as far as the eye can see.",
        "Old songs are sung to keep the storms polite.",
        "They watch the horizon the way others watch the sky.",
        "Children learn to read tracks before letters.",
        "They swear the soil tastes sweeter after every good harvest.",
        "Feasts are thrown more for defiance than abundance."
    ],
    "forest": [
        "Axes rust faster here than anywhere.",
        "They speak softly, as if the trees eavesdrop.",
        "Lanterns hang from branches to keep shadows loyal.",
        "No one counts the stumps—they might count back.",
        "Children are told not to name the darkest trees.",
        "They leave bowls of milk for things that are not quite animals.",
        "Sometimes the forest returns tools left in its shade, changed.",
        "They say the woods keep a ledger of every life it shelters.",
        "Wind here sounds like words if you stand very still.",
        "They swear the moss grows thicker over forgotten paths."
    ]
}

village_titles = [
    "Eldress", "Headman", "Headwoman", "Herdmaster", "Foreman", "Warden",
    "Speaker", "Matron", "Patron", "Reeve", "Caretaker", "Elder", "Keeper",
    "Steward", "Firewarden", "Rootmother", "Stonehand", "Mariner", "Harvester",
    "Pathfinder", "Trail Warden", "Hearthkeeper", "Wellwatcher", "Grain Reeve",
    "Woodward", "Hillwarden", "Netmaster", "Flockwarden"
]

village_names = [
    "Abernael", "Aelbrook", "Aelmore", "Aerdan", "Aeswyn", "Aithen", "Aldeth", "Alnora", "Alwyn", "Ambrin",
    "Ansael", "Arbeth", "Ardena", "Arlorn", "Armath", "Arwyn", "Ashvale", "Astair", "Atheren", "Avorwyn",
    "Baelcairn", "Baelora", "Bairen", "Balglen", "Ballara", "Balric", "Banwen", "Barrowmere", "Bastel", "Beolwyn",
    "Bereth", "Bethlin", "Blaethan", "Blencairn", "Blenwyn", "Blyra", "Boern", "Bracklow", "Branmere", "Braewood",
    "Breccan", "Brenmor", "Bridlen", "Brinvale", "Brisca", "Broen", "Brynsaeth", "Brynteg", "Brynor", "Brynwen",
    "Caer Aelion", "Caer Bren", "Caer Dovren", "Caer Lira", "Caer Tor", "Caerwyn", "Caldor", "Callen", "Calmor", "Cambril",
    "Carfen", "Carreg", "Carren", "Cassel", "Cathair", "Cavryn", "Cenric", "Cerwen", "Cindel", "Clandor",
    "Claren", "Clenwych", "Clonmere", "Clywen", "Coerlan", "Colwyn", "Comber", "Corbridge", "Corlan", "Corthen",
    "Craeg", "Craelin", "Craewood", "Cranfael", "Crathen", "Cresthaven", "Crevan", "Croen", "Cynfael", "Cynric",
    "Daelwyn", "Dalraith", "Damar", "Darin", "Darrowmere", "Darsen", "Daewin", "Dawren", "Delwyn", "Denbar",
    "Derlen", "Derra", "Deswyn", "Devra", "Diren", "Dornhal", "Dorwyn", "Dovra", "Draylen", "Droswin",
    "Ealdor", "Ealric", "Earen", "Eberin", "Edra", "Elbeth", "Elglen", "Ellan", "Elric", "Elswyth",
    "Emlyn", "Ennis", "Eowen", "Eryn", "Ethra", "Evanor", "Evarn", "Evren", "Eydon", "Eyrin",
    "Faerwyn", "Falken", "Fallowmere", "Fandor", "Farwyn", "Fenlen", "Fenra", "Fenric", "Ferndale", "Ferran",
    "Feyra", "Fildan", "Finmere", "Finnora", "Fion", "Firwen", "Flintor", "Forwyn", "Fynor", "Fynric",
    "Gaelen", "Gareth", "Garwyn", "Gavren", "Gethan", "Gilden", "Glanwyn", "Glenfael", "Glyndor", "Goran",
    "Gorwen", "Granwick", "Graymere", "Grendor", "Grithen", "Gryndal", "Gwenlen", "Gwenth", "Gwyra", "Gwyric",
    "Haeric", "Halwen", "Harfael", "Harthor", "Havric", "Hedwyn", "Helem", "Helnor", "Henwyn", "Hethen",
    "Hollan", "Holwyn", "Horric", "Horthen", "Howen", "Hunric", "Hyrwen", "Hythe", "Idra", "Ilwyn",
    "Imbre", "Imric", "Inveric", "Iona", "Irlen", "Isen", "Iswyn", "Ithor", "Iven", "Ivric",
    "Jaelwyn", "Jareth", "Jorlen", "Kaedric", "Kaelwyn", "Kairen", "Kallor", "Karven", "Keldar", "Kellen",
    "Kelric", "Kendra", "Kenwyn", "Kereth", "Keswick", "Kethen", "Kildar", "Kilwen", "Korin", "Korrin",
    "Laenor", "Lairen", "Lannor", "Lareth", "Leithen", "Lenwyn", "Lethor", "Lindale", "Lioren", "Liswyn",
    "Llynfael", "Locrin", "Lorwyn", "Loryn", "Lothen", "Lowen", "Luren", "Lyric", "Lyrwen", "Lyssan",
    "Maelric", "Maerwyn", "Mairen", "Malor", "Malwen", "Mandra", "Marlen", "Marwyn", "Mavric", "Melwen",
    "Menor", "Meran", "Merris", "Merryn", "Methen", "Miraen", "Miric", "Modwen", "Morlen", "Morwyn",
    "Muren", "Myric", "Myrren", "Naelwyn", "Nairen", "Nallor", "Nathen", "Navric", "Neiren", "Nelwyn",
    "Nethor", "Nivra", "Noeric", "Norwyn", "Noryn", "Nothen", "Nuren", "Nytha", "Odaric", "Odwyn",
    "Olric", "Onwen", "Orath", "Orlen", "Orric", "Orryn", "Oswin", "Othen", "Owric", "Oxen",
    "Paelric", "Padrin", "Parwyn", "Pellor", "Penric", "Perryn", "Pethen", "Plenwyn", "Porthen", "Powen",
    "Quenric", "Quorwyn", "Raelwyn", "Rairen", "Rallen", "Rathen", "Ravric", "Redwyn", "Renfael", "Rethor",
    "Rewyn", "Rhothen", "Rhydel", "Rhydon", "Rhyric", "Rhonfael", "Rhuen", "Rillen", "Rion", "Rithen",
    "Roen", "Roethen", "Rolen", "Rolyn", "Romric", "Ronwyn", "Rowen", "Ruthen", "Rydan", "Ryric",
    "Saelwyn", "Sairen", "Sallor", "Sarnen", "Saeric", "Seithen", "Selwyn", "Senric", "Seren", "Sethel",
    "Shaen", "Shaeric", "Shalwen", "Shelyn", "Shenric", "Sianwyn", "Sildar", "Silwen", "Sinric", "Sionfael",
    "Sorlen", "Sorwyn", "Sothen", "Suren", "Sytha", "Taelwyn", "Tairen", "Tallor", "Tannen", "Tarren",
    "Tathen", "Tavric", "Tenwyn", "Terraen", "Thalen", "Tharic", "Thelwyn", "Thoren", "Thurwyn", "Tieric",
    "Torwyn", "Tothen", "Trenwyn", "Trisfael", "Trynric", "Tynric", "Tyrwen", "Uldar", "Ulric", "Umren",
    "Unric", "Urwyn", "Uthric", "Vaerwyn", "Vairen", "Valric", "Varwyn", "Vaylen", "Vennor", "Verric",
    "Vethen", "Veyric", "Volwen", "Vyrwen", "Waldric", "Wenric", "Werthyn", "Wethen", "Wilric", "Wynfael",
    "Xaric", "Xenwyn", "Yalric", "Yaren", "Ydris", "Yfen", "Yorwen", "Yrlen", "Ysric", "Ythra",
    "Zadric", "Zelwen", "Zennor", "Zethen", "Zorwyn", "Zyric",
    "Aldwyn", "Aelbreach", "Ardfen", "Brennac", "Brisfael", "Brunhallow", "Brynsaeth", "Cairn Dovren",
    "Caldragh", "Carrigwyn", "Cennloch", "Clannuir", "Clydew", "Corlan", "Cothairn", "Craegmor",
    "Creffan", "Croeswen", "Daerwyn", "Dalmoor", "Derragh", "Dinastra", "Donvell", "Druithen",
    "Dun Fara", "Dun Lir", "Dunmoreth", "Eldfaen", "Elnor", "Erynvale", "Faerloch", "Faranach",
    "Farnach", "Feldor", "Fenwyll", "Ferndun", "Fianna's Rest", "Fintra", "Fynmoor", "Galbrey",
    "Galmere", "Garan's Ford", "Garwyn", "Gleannmor", "Glynfael", "Gormach", "Grathen", "Grelloch",
    "Gwairen", "Gwenhal", "Gwythir", "Haelwick", "Haldrin", "Harfael", "Hennach", "Hollowmere",
    "Inverfae", "Islach", "Kaerth", "Kellanach", "Kilfael", "Kilmora", "Kynbrae", "Lachwen",
    "Lairdholm", "Lanval", "Larron", "Leagh", "Lirwen", "Llandra", "Llynfell", "Lochbryn",
    "Maelcor", "Mairen", "Malwyn", "Mardenfael", "Marloch", "Meirion", "Miraen", "Moydir",
    "Naerloch", "Nairnfael", "Nanthor", "Nelan", "Nethryn", "Nevraen", "Nolwen", "Norfae",
    "Orren", "Ossbrae", "Padern", "Penhal", "Pendreg", "Penwyn", "Porthen", "Pryden",
    "Quarnach", "Rathfael", "Rhosgar", "Rhydan", "Rynfael", "Sarnwick", "Selach", "Senwyn",
    "Shalen", "Siabrae", "Silfaen", "Skeldor", "Sorlen", "Strathen", "Swyndel", "Talbryn",
    "Tarnach", "Tarrenfae", "Tarrin", "Tavren", "Tethwyn", "Thalnor", "Tharnen", "Tirfael",
    "Torren", "Trebaen", "Treflan", "Trefwyn", "Trelorn", "Tremarch", "Trenmor", "Tressan",
    "Trilfae", "Troswick", "Trynmoor", "Tuathen", "Ulfraen", "Urlen", "Varwen", "Vennloch",
    "Verran", "Wenloch", "Wynbrae", "Wyndhal", "Yarfen", "Yrfael", "Ysgar", "Ysmir",
    "Abershall", "Aelwyn", "Airan", "Alphrig", "Anwarth", "Ardal", "Arwenmor", "Ashenfael",
    "Baelric", "Balwen", "Bannoch", "Barfael", "Beddin", "Belrach", "Benfae", "Berwyn",
    "Blaren", "Bodric", "Boreth", "Breccan", "Brenwen", "Brodhaen", "Bryndel", "Cadfael",
    "Caer Halwen", "Caer Morwyn", "Caer Tael", "Caerbrin", "Caerwyn", "Cair Loch", "Cairwen",
    "Callen", "Canwyth", "Carenfael", "Carnoch", "Cenfaen", "Cernach", "Cewen", "Cledfael",
    "Clonmar", "Colwyn", "Conagh", "Corlach", "Craevel", "Credden", "Cregan", "Crumloch",
    "Cwmfael", "Dalfae", "Danwick", "Darwen", "Delwyn", "Derfael", "Derwen", "Desmor",
    "Dewloch", "Dinas Morn", "Dinfael", "Dornach", "Dowren", "Draeg", "Drunfae", "Dunmerra",
    "Eirfael", "Eldmor", "Ellan", "Ennor", "Eredach", "Erlenfae", "Erynwen", "Esgard",
    "Ewyn", "Faelmar", "Farren", "Fennach", "Fernae", "Fiannor", "Finloch", "Firwen",
    "Forwen", "Frethar", "Gaerwyn", "Galfael", "Ganmor", "Garlen", "Garthwen", "Gelden",
    "Glenfae", "Glenmor", "Glynwen", "Gorfaen", "Gralen", "Gwain", "Gwarwen", "Gwenfor",
    "Gwynfael", "Haerwyn", "Halfaen", "Hareth", "Harnach", "Hefen", "Hollen", "Hyllen",
    "Illfae", "Infael", "Islen", "Kaelwyn", "Kernach", "Kilwen", "Kyrloch", "Lanfae",
    "Lennor", "Lerwen", "Leuwen", "Llanmor", "Llynmar", "Lochwen", "Lofren", "Lorfae",
    "Loughrin", "Lunfael", "Lynach", "Machen", "Maerwyn", "Marnach", "Marwyn", "Merrfae",
    "Milwen", "Minfael", "Monwen", "Morfae", "Moylen", "Muren", "Myfael", "Narth",
    "Neirwen", "Nolfael", "Norwen", "Orrfae", "Oslen", "Ostwyn", "Paderach", "Parwen",
    "Penfael", "Penmor", "Penren", "Porthwen", "Prellen", "Quenna", "Rathwen", "Reenfae",
    "Rhosfael", "Rhydwen", "Rillach", "Rinmor", "Rogfae", "Rolen", "Rowenfae", "Rynloch",
    "Sarnfael", "Selmor", "Senfae", "Serwen", "Sharnach", "Sianfae", "Silmar", "Simren",
    "Sithfae", "Sowen", "Strenmor", "Suilfae", "Sundren", "Talfen", "Talfae", "Taraen",
    "Tarrwyn", "Teirfae", "Temra", "Tharnach", "Thelfae", "Thoren", "Torfael", "Torwen",
    "Trefen", "Trellfae", "Trelwen", "Tressa", "Trynfae", "Tulaen", "Turenfae", "Tynwen",
    "Uffren", "Ulwen", "Urfae", "Varnach", "Velwen", "Vennach", "Verfae", "Vorrin",
    "Wenfael", "Wernach", "Wolfae", "Wrenfae", "Wyfael", "Yardra", "Yernach", "Ylwen"
]

village_bios = [
    "Knows the name of every child and every grave.",
    "Keeps peace with patience sharper than any blade.",
    "Believes the land listens and tries to deserve its favor.",
    "Once ended a blood feud by marrying both sides of it into one family.",
    "Prays to the soil more often than to any distant god.",
    "Collects old songs and older debts.",
    "Feeds strangers first and questions later.",
    "Has outlived three disasters and a dozen rivals.",
    "Carries a charm that hums when danger nears.",
    "Teaches children to bow to nothing but the rain.",
    "Once tried to leave for the city and returned with quieter eyes.",
    "Prefers clear skies and honest lies.",
    "Believes that a shared meal can unmake most curses.",
    "Hides their fears in work and their hopes in stories.",
    "Knows which omens to heed and which to ignore out of necessity.",
    "Once bargained with something in the dark and never speaks of the price.",
    "Can hear the weather shift before the wind arrives.",
    "Carries the village's history in memory, not in books.",
    "Laughs rarely but sincerely.",
    "Stands between their people and the world with a stubborn calm.",
    "Keeps a small shrine to ancestors made of twine and patience.",
    "Believes the soil remembers every kindness and every cut.",
    "Once brokered peace between wolves and shepherds—claims it still holds.",
    "Walks barefoot through frost to remind themselves what the land endures.",
    "Believes laughter is a kind of warding charm.",
    "Has seen every flood and fears the one that still hasn't come.",
    "Wakes before sunrise to greet the wind by name.",
    "Teaches that pride should be planted deep, humility deeper.",
    "Speaks softly to roots when pruning trees.",
    "Claims to have spoken once with the rain—and lost the argument.",
    "Bakes bread only on days the clouds move east.",
    "Believes singing while sowing invites better harvests.",
    "Once saved a traveler from drowning; the traveler still writes every spring.",
    "Counts their age not in years but in winters survived.",
    "Wears a necklace of seeds for protection and memory.",
    "Believes no tale worth telling ever ends happily.",
    "Keeps the village bell unpolished, 'so it remembers work.'",
    "Smiles rarely, but every time, the livestock behave for a week.",
    "Taught the children to read clouds before books.",
    "Believes even crows carry messages worth listening to.",
    "Once healed a feud by planting a tree between the houses.",
    "Never learned to write but keeps the records in rhyme.",
    "Tends to every grave personally, even those not yet occupied.",
    "Brews mead for joy and vinegar for revenge.",
    "Keeps a walking stick older than the oldest villager.",
    "Talks to tools before using them—claims they work better that way.",
    "Refuses to cut the oldest tree though it leans dangerously over their roof.",
    "Believes dreams are simply tomorrow's warnings.",
    "Taught the young ones how to dance in storms rather than flee them.",
    "Knows every well has its own temperament.",
    "Laughs at omens, just to keep them humble.",
    "Carries guilt for a drought they couldn't prevent, though none blame them.",
    "Claims to have seen a saint once disguised as a beggar.",
    "Listens to bees and trusts their judgment.",
    "Believes that forgetting is worse than hunger.",
    "Feeds stray dogs and wandering ghosts equally.",
    "Once stopped a plague by burning herbs and singing wrong on purpose.",
    "Says a village's worth is measured in how often its people share silence.",
    "Keeps a charm carved from a lightning-struck branch.",
    "Buried their own name years ago, preferring titles earned by deeds.",
    "Can read the sky like scripture.",
    "Swears every child born here arrives already knowing one secret.",
    "Believes curses lose power when spoken with laughter.",
    "Still sets a place at supper for those lost to the woods.",
    "Once dreamed of the sea and woke with salt in their hair.",
    "Counts seasons by the stories told, not the crops grown.",
    "Watches the moon like a ledger of promises kept and broken.",
    "Claims thunder is simply the land applauding courage.",
    "Knows which ghosts require politeness and which require ale.",
    "Smiles when the wind changes—'means someone arrived safely somewhere.'",
    "Still carries a pouch of the first soil ever plowed here.",
    "Once healed a fever with song when medicine failed.",
    "Believes thunder is the mountain's applause for courage.",
    "Writes every death in a secret book of rain-stains.",
    "Taught the children that laughter feeds the crops.",
    "Once traded a ghost for a goat and never explained how.",
    "Claims to have met the wind in person and lost an argument.",
    "Brews nettle wine only on full moons and funerals.",
    "Keeps feathers in their hat so the dead can find them in dreams.",
    "Can read the sky's mood better than any prayer.",
    "Remembers every famine and forgives none of them.",
    "Says each well has its own accent and listens accordingly.",
    "Still thanks the wolves for keeping the valley honest.",
    "Carries a charm made from the first nail of the first house.",
    "Laughs with eyes closed, as if saving the sound for later.",
    "Once stopped a flood by asking the river politely.",
    "Believes bread rises higher when baked with gossip.",
    "Tends the village's single lantern that never goes out.",
    "Keeps a journal of dreams in the margins of seed-ledgers.",
    "Walks the perimeter nightly, whispering names to the dark.",
    "Claims the scarecrows here remember everything.",
    "Knows three kinds of silence and uses each wisely.",
    "Believes memory itself has seasons.",
    "Once taught a crow to deliver marriage proposals.",
    "Cleans the shrine stones with tears, never water.",
    "Swears the bees understand politics better than humans.",
    "Can tell what's coming by the taste of the wind.",
    "Says grief is a guest that must be fed politely.",
    "Keeps a blade rusted on purpose 'so it remembers blood.'",
    "Refuses to sleep indoors during planting season.",
    "Tells stories backward so children learn patience.",
    "Believes the forest whispers in old dialects forgotten by priests.",
    "Was born during a storm that hasn't quite ended.",
    "Feeds crows at dawn and asks nothing in return.",
    "Measures age by scars rather than years.",
    "Once found a saint's finger bone and used it as a bookmark.",
    "Brews ale said to make travelers confess their sins.",
    "Never married; says the village itself is spouse enough.",
    "Laughs at omens until they start laughing back.",
    "Keeps a lock of wolf fur beside the bread dough for luck.",
    "Claims to remember the sound of the first forge spark.",
    "Never forgets a face, even ones seen only in dreams.",
    "Swears they once bargained with winter and won a week.",
    "Hums the same tune each morning to keep the ghosts orderly.",
    "Counts stars for those too tired to lift their eyes.",
    "Writes letters to ancestors and burns them in the hearth.",
    "Insists the moon owes them a favor from long ago.",
    "Once saved a stranger who later turned out to be no one.",
    "Believes every lie told kindly earns one day of rain.",
    "Refuses payment for advice, accepts bread and secrets.",
    "Carries a pocket full of dried petals for remembering laughter.",
    "Believes sorrow should be composted, not buried.",
    "Can tell the time by how the cows chew.",
    "Says miracles happen mostly to the well-prepared.",
    "Once fed the entire village with a single stubborn loaf.",
    "Claims to hear the dead in the buzzing of flies after harvest.",
    "Plants extra crops 'for the mistakes we'll make next year.'",
    "Believes kindness is a currency older than coin.",
    "Never trusted maps—says roads change their minds too often.",
    "Speaks softly to the well each morning for clean conscience.",
    "Has never broken a promise, only rescheduled them.",
    "Thinks forgiveness tastes like rainwater and ash.",
    "Once taught a fox to fetch kindling.",
    "Swears every storm has a favorite window to rattle.",
    "Keeps bees that sting only liars.",
    "Knew the river before it learned restraint.",
    "Paints blessings on doors using soot and wine.",
    "Believes good luck spoils if bragged about.",
    "Can whistle the exact pitch that makes dogs stop barking.",
    "Once told the king's taxman a joke so long he left hungry.",
    "Still wears their wedding ring though no one recalls a spouse.",
    "Keeps dried apples on every windowsill for passing spirits.",
    "Believes forgetting is the only true sin.",
    "Says music should never outlive its dancer.",
    "Once forged peace by swapping names with an enemy.",
    "Claims dreams are the forest's way of reading us back.",
    "Feeds the shrine's candles from their own breath.",
    "Carries a bone whistle said to summon honesty.",
    "Refuses to own mirrors—'they remember too clearly.'",
    "Once stopped lightning with a shout.",
    "Knows the lineage of every rooster for five generations.",
    "Writes blessings in chalk under wagon wheels before journeys.",
    "Speaks with the calm of old stone and the humor of wet clay.",
    "Believes water holds grudges longer than people.",
    "Bakes a loaf for the dead each harvest and buries the crumbs.",
    "Keeps their heart in the right place, but rarely visits.",
    "Once tricked famine by declaring hunger fashionable.",
    "Believes humility should be taught by weather.",
    "Wears mismatched shoes 'to confuse misfortune.'",
    "Swears the sky once apologized to them personally.",
    "Was the only child born on a leap day—still catching up.",
    "Walks backward on holy days to undo the year's mistakes.",
    "Knows the scent of snow two days early.",
    "Sings lullabies to the fields long after the children sleep.",
    "Can find north with their eyes closed and hope open.",
    "Keeps a nail from every coffin ever buried here.",
    "Once made a scarecrow that laughed—and burned it for safety.",
    "Never forgets a kindness, even from fools or foxes.",
    "Carries a pouch of dust from their birthplace to scatter when homesick.",
    "Was struck by lightning and claims it improved memory.",
    "Prays in silence so the gods must lean close.",
    "Believes true leadership is quieter than thunder.",
    "Owns a walking stick carved with every mistake they've made.",
    "Teaches that peace is simply the courage to wait.",
    "Has a smile that makes crops grow straighter.",
    "Speaks to strangers as if they were old friends returning late.",
    "Once gave away their fortune to prove a prophecy wrong.",
    "Claims the forest itself once voted them leader.",
    "Keeps watch beside the well each solstice until dawn forgives the dark.",
    "Laughs at their own legends just enough to stay human.",
    "Says all roads lead home—eventually, if you walk kindly."
]

