"""
Fetch quest items organized by settlement type.
These items are used in fetch quests offered by different settlement types.
"""

# Village fetch quest items (495 items)
VILLAGE_FETCH_QUEST_ITEMS = [
    "A sprig of heather", "A handful of barley seed", "A spool of red thread", "A carved wooden charm",
    "A basket of apples", "A clay pitcher of milk", "A lump of beeswax", "A cracked prayer stone",
    "A sprig of rowan", "A spool of wool yarn", "A tin of ointment", "A brass button",
    "A sheaf of oats", "A broken spindle", "A feather from a blackbird", "A child's lost shoe",
    "A pot of honey", "A sealed letter", "A lock of hair wrapped in ribbon", "A bundle of dried herbs",
    "A chipped mug", "A torn cloak clasp", "A pouch of salt", "A small mirror",
    "A painted egg", "A worn prayer bead", "A handful of clay", "A cracked bowl",
    "A dog's collar", "A spool of flax", "A pair of knitting needles", "A sprig of wild thyme",
    "A basket of mushrooms", "A sheep's bell", "A sprig of lavender", "A handful of ash from the hearth",
    "A broken flute", "A loaf of barley bread", "A ribbon for the harvest dance", "A bag of nails",
    "A small sack of flour", "A sprig of nettle", "A jug of cider", "A ring lost in the mud",
    "A jar of goose fat", "A cracked hand mirror", "A child's wooden toy", "A set of brass weights",
    "A jar of berry jam", "A chipped cooking pot", "A sheep's fleece", "A spool of silver thread",
    "A bag of grain", "A pinch of incense", "A wooden comb", "A sprig of mistletoe",
    "A clay whistle", "A fishhook", "A pouch of dried mint", "A bottle of homemade ale",
    "A smooth river stone", "A missing button", "A cracked cup", "A jar of preserved pears",
    "A spool of dyed thread", "A charm against fever", "A string of beads", "A pair of worn gloves",
    "A fox pelt", "A jug of goat's milk", "A dried rabbit's foot", "A handful of goose feathers",
    "A basket of blackberries", "A pot of gooseberry jam", "A lost wedding band", "A dog whistle",
    "A chipped pewter spoon", "A small wooden box", "A painted pebble", "A sheep's horn",
    "A copper coin from long ago", "A jar of lard", "A pot of herbal poultice", "A charm of woven grass",
    "A clutch of hen's eggs", "A child's rattle", "A string of garlic", "A sprig of yarrow",
    "A sheaf of rushes", "A spool of linen", "A strip of tanned leather", "A jar of ink",
    "A book of psalms", "A scrap of parchment", "A quill feather", "A pouch of seeds",
    "A sprig of rosemary", "A handful of sand", "A jug of spring water", "A chipped lantern glass",
    "A candle stub", "A lost pendant", "A dried sprig of sage", "A clay idol",
    "A jug stopper", "A piece of broken pottery", "A splinter of driftwood", "A small bronze key",
    "A doll's head", "A patch of homespun cloth", "A bottle of lamp oil", "A spool of hemp twine",
    "A length of rope", "A wicker basket", "A hand mirror", "A cracked pipe",
    "A goose quill", "A bar of soap", "A dried bouquet", "A lock of horsehair",
    "A piece of chalk", "A handful of barley husks", "A small hammer", "A pair of shears",
    "A jar of salve", "A cat's collar bell", "A leather strap", "A handful of soot",
    "A patch of beeswax candle", "A smooth pebble with runes", "A sprig of hawthorn", "A broken charm bracelet",
    "A scrap of red cloth", "A cup of milk for the Good Folk", "A small sickle", "A chipped bowl from the inn",
    "A silver thimble", "A missing glove", "A child's sketchbook", "A dried poppy",
    "A handful of crushed herbs", "A copper brooch", "A pouch of crushed chalk", "A jar of butter",
    "A spoon carved from oak", "A string of dried apples", "A clay pendant", "A lost boot buckle",
    "A sack of potatoes", "A torn piece of tapestry", "A lump of coal", "A folded handkerchief",
    "A charm of seashells", "A page from a hymnbook", "A fish scale that shines like silver", "A carved flute reed",
    "A seed pod from a sacred tree", "A spool of gold thread", "A lamb's wool cap", "A piece of broken jewelry",
    "A small cask of ale", "A jug of honeywine", "A sprig of foxglove", "A sprig of holly",
    "A bucket of fresh water", "A clay cup from the well", "A handful of white sand", "A cat's pawprint charm",
    "A bit of charred wood from a fire", "A feather from a swan", "A scrap of fur from a white hare", "A spindle of spun wool",
    "A broken brooch", "A cracked mirror frame", "A pouch of mead yeast", "A set of mismatched buttons",
    "A carved walking stick head", "A spool of copper wire", "A carved bead from a rosary", "A vial of perfume",
    "A wooden bowl carved with spirals", "A lost diary page", "A faded ribbon", "A spool of black thread",
    "A tattered love letter", "A sheepdog whistle", "A silver pin", "A sprig of juniper",
    "A handful of acorns", "A sheep's tag", "A cracked mug from the tavern", "A handful of thistle seeds",
    "A bottle of strong spirits", "A sprig of gorse", "A hen's feather", "A pouch of ash",
    "A single horseshoe nail", "A patch from a banner", "A child's marble", "A lump of amber",
    "A dried fish tail", "A small sack of salt", "A piece of chalked slate", "A sprig of broom",
    "A carved love token", "A straw hat", "A smoothed river shell", "A torn bit of parchment map",
    "A clump of turf", "A sprig of elderflower", "A bottle cork", "A cracked pocket knife",
    "A leather-bound charm book", "A small anvil stone", "A spool of crimson ribbon", "A set of wooden dice",
    "A pouch of lye", "A carved wooden pipe", "A sprig of ivy", "A pail of goat's milk",
    "A half-burned candle", "A coil of fishing line", "A silver earring", "A clump of wool from a fencepost",
    "A clay jar stopper", "A bundle of firewood", "A lost prayer ribbon", "A sprig of basil",
    "A bunch of grapes", "A sack of turnips", "A broken scythe handle", "A dog's lead",
    "A rabbit snare", "A pouch of spice", "A cracked pewter cup", "A faded family locket",
    "A small crystal shard", "A handwoven belt", "A dried sprig of mint", "A set of old keys",
    "A spool of silver wire", "A handful of pebbles from the stream", "A clay pipe stem", "A sprig of marigold",
    "A vial of blue dye", "A sheep's tag bell", "A lost coin", "A plowshare pin",
    "A sliver of driftwood cross", "A carved bird figurine", "A pair of spectacles", "A candle mold",
    "A scrap of embroidered linen", "A trinket box", "A bit of polished bone", "A set of sewing needles",
    "A small iron buckle", "A handkerchief embroidered with initials", "A lost comb", "A fragment of pottery tile",
    "A chipped tea cup", "A bottle of vinegar", "A hair ribbon", "A spool of coarse twine",
    "A chicken feather quill", "A lump of sap resin", "A spool of gray yarn", "A clay lamp",
    "A ring made of woven grass", "A pouch of ground barley", "A spool of undyed flax", "A faded festival token",
    "A charm carved from driftwood", "A fragment of stained glass", "A broken bell clapper", "A sheep's ear tag",
    "A basket handle", "A cracked horseshoe", "A sprig of meadow sage", "A milk jug stopper",
    "A wooden bead bracelet", "A pebble shaped like a heart", "A clay bird whistle", "A pouch of ashes",
    "A sprig of meadow rue", "A cracked jug", "A flask of nettle beer", "A chipped plate",
    "A spool of green thread", "A child's wooden sword", "A sprig of bog myrtle", "A pressed flower",
    "A silver clasp", "A bit of beeswax polish", "A pouch of chalk dust", "A small cloth pouch of pins",
    "A wooden rosary bead", "A worn shoe buckle", "A copper pin", "A sheep's hoof trimming",
    "A thimble of tin", "A clay amulet", "A handful of wheat kernels", "A set of old playing cards",
    "A cracked cooking lid", "A spool of golden cord", "A sprig of fennel", "A polished stone pendant",
    "A piece of parchment seal", "A scrap of blue velvet", "A piece of dried peat", "A painted wooden charm",
    "A drop of sealing wax", "A sprig of hemlock", "A carved ring box", "A pouch of chalked lime",
    "A small jar of molasses", "A splinter of saint's bone (or so they say)", "A half-written letter", "A clay figurine",
    "A worn shoe", "A bit of goat's cheese", "A sprig of meadow mint", "A pouch of ground herbs",
    "A bunch of onions", "A spool of black hair ribbon", "A sprig of bog cotton", "A small tin whistle",
    "A tiny bottle of perfume", "A smoothed bone dice", "A silver hairpin", "A pouch of earth from a grave",
    "A sprig of pennyroyal", "A clutch of duck eggs", "A scrap of parchment charm", "A folded note sealed with wax",
    "A sprig of chamomile", "A bit of carved antler", "A small jar of pickled onions", "A handful of barley husk",
    "A pewter badge", "A spool of red silk", "A piece of driftwood shaped like a fish", "A sprig of tansy",
    "A woven bracelet", "A cracked bottle stopper", "A clay oil lamp", "A token from a fair",
    "A silver spoon", "A child's chalk drawing", "A sprig of fern", "A wooden spinning top",
    "A spool of pale blue thread", "A bag of dried peas", "A sprig of clover", "A doll made of corn husks",
    "A rabbit pelt", "A chipped pewter plate", "A handful of feathers", "A pouch of powdered dye",
    "A sprig of angelica", "A bag of beans", "A sprig of valerian", "A small clay pot",
    "A handful of river mud", "A spool of rope fiber", "A sprig of lemon balm", "A goose feather quill",
    "A brass button", "A sprig of elder bark", "A lock of baby's hair", "A polished conch shell",
    "A sprig of rue", "A cracked tin cup", "A dried reed flute", "A sprig of meadowsweet",
    "A feather from a crow", "A polished stone heart", "A bottle of tincture", "A spool of linen cord",
    "A bunch of nettles", "A sprig of rosemary and sage", "A bag of lime powder", "A clay tile fragment",
    "A small carved sheep", "A dried beetle wing", "A handful of dirt from the crossroads", "A sprig of sorrel",
    "A pocket knife", "A spool of crimson wool", "A smooth round pebble", "A sprig of dandelion",
    "A jar of gooseberry preserves", "A handful of flour", "A spool of hemp fiber", "A sprig of coltsfoot",
    "A cracked jug stopper", "A spool of golden thread", "A handful of dust from the church floor", "A patch of linen from a burial shroud",
    "A bunch of rushes", "A sheep's tooth charm", "A scrap of parchment from a lost ledger", "A handful of crushed eggshells",
    "A sprig of poppy", "A pebble from a saint's cairn", "A sprig of creeping thyme", "A bit of green glass",
    "A dried frog's leg", "A pouch of earth from the hilltop", "A handful of grain from the last harvest", "A tiny wooden cross",
    "A handful of straw", "A sprig of cow parsley", "A dried frog's heart (for luck, or curse)", "A spool of violet ribbon",
    "A sprig of sagebrush", "A scrap of tanned hide", "A bit of bone needle", "A drop of beeswax candle",
    "A sprig of mint and honey", "A bag of meal", "A fish bone charm", "A lock of horse mane",
    "A sprig of meadow grass", "A pinch of black salt", "A clay cup from the tavern", "A sprig of mullein",
    "A bundle of thatching straw", "A scrap of embroidered lace", "A handful of marbles", "A dried bluebell",
    "A cracked ceramic jug", "A handful of bread crumbs", "A spool of dark gray thread", "A bundle of dried heather",
    "A sheep's hoof token", "A broken rosary", "A sprig of willow bark", "A pouch of powdered chalk",
    "A bit of gold leaf", "A scrap of parchment prayer", "A sprig of horehound", "A polished snail shell",
    "A chunk of beeswax", "A piece of old chain", "A dried fern leaf", "A wooden bead charm",
    "A small brass bell", "A clay shard carved with spirals", "A glass bead", "A dried sunflower head",
    "A woolen mitten", "A sprig of yew", "A jar of black dye", "A piece of worn rope",
    "A bottle cork from the tavern", "A sprig of wolfsbane", "A bone needle", "A sprig of catmint",
    "A small wooden token carved with a spiral", "A sprig of parsley", "A pouch of barley flour", "A lock of white hair",
    "A silver button", "A handful of hay", "A pinch of soot", "A sprig of hawkweed",
    "A piece of cracked pottery", "A spool of violet silk", "A clutch of pigeon feathers", "A handful of acorn caps",
    "A sprig of fennel root", "A broken clay jug", "A copper earring", "A polished pebble with initials carved",
    "A sprig of moss", "A sprig of red clover", "A handful of snail shells", "A jar of goose grease",
    "A sprig of heather and rosemary", "A small glass bead", "A lost charm from a wedding chain", "A sprig of thyme and honey",
    "A spool of dyed crimson thread", "A bag of sugar", "A scrap of parchment torn from a hymn", "A wooden bowl full of grain",
    "A sprig of juniper berries", "A clay cup etched with runes", "A sprig of bell heather", "A cracked copper pot",
    "A dried mouse tail", "A silvered hairbrush", "A sprig of meadow lavender"
]

# Town fetch quest items (to be populated)
TOWN_FETCH_QUEST_ITEMS = [
    # Placeholder - will be populated later
]

# City fetch quest items (to be populated)
CITY_FETCH_QUEST_ITEMS = [
    # Placeholder - will be populated later
]

