"""
Quest location descriptions for different terrain types.
These descriptions are used when generating quests to describe the destination.
"""

# Location descriptions for each terrain type
# Format: "a {description}" - will be used in journal as "You must travel to a {description}..."
quest_location_descriptions = {
    "hill": [
        "windswept cairn where shepherds swear the stones rearrange each solstice",
        "burial mound with iron doors half-buried in peat",
        "ruin of a hilltop fort still echoing with phantom horns",
        "standing-stone circle blackened by lightning and legend",
        "hollowed hill where the earth hums when the moon rises",
        "abandoned watchtower overlooking mist and memory",
        "field of boulders etched with forgotten ogham marks",
        "crumbling remains of a druid's observatory",
        "grassy tor riddled with tunnels no one claims to have dug",
        "hill altar built from bones and belief",
        "forgotten chieftain's tomb sealed by melted bronze",
        "shepherd's hut turned shrine to an unremembered god",
        "stone causeway that appears only when thunder shakes the ground",
        "collapsed hill-fort whose ramparts hide gold — or graves",
        "black pit where miners struck something that sang",
        "windswept ridge where banners still flutter though the army is long gone",
        "sunken ring of stones known as the \"Giants' Seat\"",
        "grassy barrow whose entrance breathes mist at dusk",
        "echoing cavern beneath the sacred hill of vows",
        "cratered mound filled with luminous fungi",
        "hermit's cell carved from solid granite",
        "lonely crossroad cairn haunted by oathbreakers",
        "windmill built from stolen tombstones",
        "ridge where crows gather before war",
        "mossy stair that climbs to a vanished temple",
        "slate quarry where time seems to halt at noon",
        "burnt-out smithy where iron refuses to cool",
        "pilgrimage path ending at a stone finger pointing skyward",
        "shattered keep of a forgotten petty king",
        "hollow hill that hums like a great drum",
        "hilltop field where cattle vanish every Beltane",
        "shrine carved into the spine of the ridge",
        "thunderstone lodged in the earth like a buried heart",
        "ruins of a roundhouse painted with ochre runes",
        "grass mound that opens once a century",
        "dry well that once granted prophecy",
        "grave of the last bard, marked only by a harp of stone",
        "ringfort whose gate never stays closed",
        "mist-hill said to weep when blood is spilled nearby",
        "high pasture where ghostly fires burn unseen",
        "dolmen of three sisters who outwitted death",
        "carved throne of basalt where kings once knelt",
        "shattered obelisk humming faintly when storms approach",
        "glen's lip overlooking a valley of bones",
        "meadow studded with ancient spearheads",
        "shepherd's crossroad cursed to repeat travelers' footsteps",
        "mound said to contain the last breath of a saint",
        "ridge shrine tended by a single blind priest",
        "spiral ditch where druids danced the stars into order",
        "scorched tor where a dragon's shadow burned into stone",
    ],
    "forested_hill": [
        "ravine cloaked in yew where the air smells of honey and rot",
        "ivy-wrapped tower of a vanished monk order",
        "hidden glade where deer kneel to drink from a silver pool",
        "mossy cave said to guard the bones of a sleeping giant",
        "ruined chapel swallowed by oak roots",
        "steep glen where every echo answers in a stranger's voice",
        "hanging bridge that sways even without wind",
        "waterfall shrine where coins vanish from offerings overnight",
        "tangled pass haunted by green-eyed wolves",
        "grove of thorns growing in perfect circles",
        "hilltop hermitage reached by seven uneven steps",
        "moss-dark hollow where mushrooms glow blue at dusk",
        "stone stair carved by monks and reclaimed by foxes",
        "chestnut copse hiding an ancient forge",
        "broken watchtower leaning against a living oak",
        "hunting lodge frozen in time since its master vanished",
        "pine-ringed barrow that bleeds sap like tears",
        "vine-choked amphitheater where shadows perform silently",
        "overgrown ruins of a monastery dedicated to silence",
        "glen whose paths rearrange after each storm",
        "shrine to the Green Mother carved into living bark",
        "slope littered with petrified antlers",
        "\"Hollow Choir\" — standing stones that sing in rain",
        "old druidic waystation built into a cliff face",
        "burned ring of forest where nothing regrows",
        "knotted oak that whispers warnings when cut",
        "ruined hunter's hall now ruled by ravens",
        "moss stair that leads to nowhere but back again",
        "glen whose mist takes the shape of forgotten lovers",
        "\"Sleeping Well\" — a pool that shows the past, not reflections",
        "hermit's cell guarded by foxes that never flee",
        "birch circle around a stone too cold for summer",
        "forest pass sealed by ancient carvings of beasts",
        "watch-post turned shrine to lost rangers",
        "woodcutters' altar buried beneath moss and guilt",
        "echoing cavern where bats form patterns like letters",
        "tangle of fallen pines marking a buried treasure or curse",
        "grove where thunder never reaches",
        "sunken stone circle veiled by bracken",
        "bridge of bones crossing a dry ravine",
        "spring said to heal — or erase — memory",
        "torch tree that burns nightly yet never dies",
        "redwood with steps carved spirally to the heavens",
        "leaf-choked abbey where statues cry amber tears",
        "green road lined with forgotten milestones",
        "bear's cave watched over by carved idols of saints",
        "slope scattered with silver leaves that never decay",
        "stone giant half-swallowed by the hillside",
        "birch copse that glows faintly under moonlight",
        "fallen bridge where each plank hums a different tone",
    ],
    "grassland": [
        "plainland ruin of an ancient abbey whose bells still toll at dusk",
        "wind-swept field dotted with toppled menhirs",
        "crumbling farmhouse surrounded by golden grass and silence",
        "skeletal remains of a great stone circle flattened by time",
        "barrow rising alone amid a sea of heather",
        "lonely crossroads where an unending breeze hums like a hymn",
        "remnants of a monastery's cloister now grazed by sheep",
        "sunken field where wildflowers grow in the shape of old walls",
        "grassy mound marking a forgotten battlefield",
        "standing cross bleached white by centuries of wind",
        "dry well once said to cure broken hearts",
        "remains of a stone hall buried beneath wild oats",
        "ruined waystation overrun by wandering herds",
        "harvest shrine carved into a hill of clay and bone",
        "last archway of a cathedral swallowed by grass",
        "cairn of fieldstones marking the edge of an old kingdom",
        "shepherd's cairn where voices whisper warnings at dusk",
        "broken aqueduct where the wind mimics flowing water",
        "half-collapsed granary turned into a chapel by travelers",
        "shallow vale filled with shards of pottery and bone",
        "scorched meadow that never regrows",
        "ruin of a low stone fort where larks nest in the battlements",
        "forgotten field altar shaped from a single slab of limestone",
        "lonely bell tower standing amid wheat like a sentinel",
        "ruins of a plague village hidden beneath tall grass",
        "shepherd's circle where strange lights gather at night",
        "pilgrim's path marked only by carved wooden posts",
        "skeleton of a windmill that still turns on calm days",
        "pasture cairn dedicated to the goddess of abundance",
        "shallow ditch where a river once flowed before it fled underground",
        "ruins of a market square overtaken by wild barley",
        "sunken shrine said to bloom once every hundred years",
        "field where a saint's footprints are said to remain uncut by plow",
        "crossroads inn buried by dust storms long ago",
        "pair of standing stones that hum in harmony with thunder",
        "meadow of white flowers growing in perfect rows no one planted",
        "cracked foundations of a watchtower on the wide plain",
        "field of old iron tools twisted into the shapes of beasts",
        "spring rising in the center of a perfect green ring",
        "hollow in the earth lined with scorched glass",
        "grassy amphitheater where shepherds still sing contests",
        "mound that bleeds red mud after storms",
        "ring of wooden posts — all burned, yet never charred black",
        "ruin of a monastic bakery where bread once fed a thousand pilgrims",
        "patch of ground that stays unnaturally warm even in frost",
        "solitary oak growing atop a buried crypt",
        "cracked base of a column said to once reach heaven",
        "meadow of whispering grass that grows taller each full moon",
        "ruins of a farmstead surrounded by spectral fireflies",
        "plain of golden grass hiding the outlines of an entire lost town",
    ],
    "forest": [
        "hollow tree large enough to house a family",
        "glade where no bird dares sing",
        "ruins of a druid school, its stones etched with constellations",
        "tangled grove rumored to hold a door to the Otherworld",
        "mossy abbey reclaimed by ivy and silence",
        "black pool said to mirror your death instead of your face",
        "altar of roots tended by unseen hands",
        "ruined bell tower that still tolls at dusk",
        "Whispering Glen, where voices ride the wind like mist",
        "fallen oak whose trunk hides ancient carvings",
        "glimmering pond guarded by white stags",
        "canopy so dense it feels like twilight even at noon",
        "clearing of cairns — one stone for each forgotten oath",
        "hunter's lodge now taken over by moss and birds",
        "grove of seven trees struck by the same lightning",
        "ring of mushrooms that never breaks",
        "overgrown ruins of a monastery swallowed by ferns",
        "silver-barked forest said to have grown overnight",
        "thorn maze rumored to conceal a sleeping knight",
        "root-bridge built by dryads in ancient days",
        "hollow filled with still water reflecting only the moon",
        "burned scar where witches once danced in firelight",
        "cave mouth shaped like an open mouth mid-cry",
        "burial grove lined with lanterns made from gourds",
        "fallen tower inhabited by crows that speak names",
        "glen of eternal rain, where it always drizzles but never floods",
        "stump circle marking the site of a felled god-tree",
        "deer path lined with bones and blessings",
        "spring whose water tastes faintly of copper and song",
        "weeping birch grove, its bark streaked with red sap",
        "shrine of mossy idols who trade dreams for truth",
        "fogbound grove where time moves like syrup",
        "blackthorn grove that grows only near grief",
        "sacred grove sealed by mist for half the year",
        "tree-bridge over a chasm that hums like a harp",
        "ruins of a hermit's scriptorium carved in stone",
        "clearing of silvered logs that glow at night",
        "wolf altar built of skulls and roots",
        "narrow path marked by candles that never burn out",
        "\"Dream Glen,\" where sleepers never wake sane",
        "petrified forest where every trunk hums with memory",
        "copse of elder trees surrounding a pool of black glass",
        "lost chapel of Saint Briga hidden under moss",
        "grove of ash trees grown in the shape of a crown",
        "pool where a white serpent guards its reflection",
        "fallen stone face half buried in leaves",
        "twilight glen where shadows walk separately",
        "ring of ironwood trees impossible to cut",
        "sacred fire pit that reignites on the solstice",
        "root-wrapped ruin humming faintly with prayer",
    ],
    "waterside": [
        "sea cave where waves echo like voices of the drowned",
        "tidal causeway visible only at low tide",
        "ruined abbey half-swallowed by the surf",
        "wreck of a black ship beached like a carcass",
        "fishing pier haunted by lights no hand carries",
        "salt marsh where ghosts walk at dawn",
        "lighthouse that still burns though no keeper remains",
        "stone steps descending beneath the tide",
        "beached whale covered in strange runes",
        "drowned village visible beneath calm waters",
        "storm-battered shrine to the sea god forgotten by all",
        "sea cliff carved with faces that weep in rain",
        "coral grotto glowing faintly from within",
        "wreckage of a bridge linking two vanished shores",
        "sandbar graveyard of ship masts and bones",
        "ruins of a harbor swallowed by shifting dunes",
        "sea-stack crowned with a hermit's hut",
        "bay where the water glows blue under moonlight",
        "jetty of broken chains used in ancient sacrifices",
        "fisher's chapel clinging to a cliff like a barnacle",
        "tidal cave where pearls grow on the ceiling",
        "sunken archway leading nowhere",
        "drowned bell tower whose toll can still be heard",
        "beach where footprints never wash away",
        "skeleton of a sea dragon tangled in seaweed",
        "wrecking shore strewn with false beacons",
        "ruined pier haunted by eternal music",
        "salt lagoon filled with perfectly preserved corpses",
        "submerged ruins of a castle seen only at ebb tide",
        "cove of shimmering sand that moves like liquid",
        "\"Fisher King's Rock,\" stained red even at low tide",
        "stone arch known as the Siren's Gate",
        "harbor statue whose eyes follow every ship",
        "watermill that grinds only bones",
        "seawall overgrown with strange white flowers",
        "skeleton pier where gulls roost like monks",
        "brine cave lined with smooth, luminous shells",
        "cliffside shrine reachable only by rope bridge",
        "fisher's village swallowed once, now half rebuilt on its bones",
        "whirlpool where offerings vanish but return years later",
        "glass beach made of melted sand from a divine strike",
        "tidal inlet where seals gather to sing",
        "lighthouse of shifting light that misleads travelers inland",
        "drowned orchard that still bears fruit beneath the waves",
        "shrine of the salt saint, forever slick with tears",
        "cliff cavern where the air smells faintly of lilac and blood",
        "shipwreck that still drips gold",
        "bay of mirrors, where each reflection moves differently",
        "sandbank graveyard marked with driftwood crosses",
        "tidal crypt of the Last Fisher, sealed by coral and faith",
    ],
}
