"""
Fetch quest items organized by settlement type.
These items are used in fetch quests offered by different settlement types.
"""

# Village fetch quest items (495 items)
VILLAGE_FETCH_QUEST_ITEMS = [
    "A sprig of heather", "A handful of barley seed", "A spool of red thread", "A carved wooden charm",
    "A basket of apples", "A clay pitcher of milk", "A lump of beeswax", "A cracked prayer stone",
    "A sprig of rowan", "A spool of wool yarn", "A tin of ointment", "A brass button",
    "A sheaf of oats", "A broken spindle", "A feather from a blackbird", "A child's lost shoe",
    "A pot of honey", "A sealed letter", "A lock of hair wrapped in ribbon", "A bundle of dried herbs",
    "A chipped mug", "A torn cloak clasp", "A pouch of salt", "A small mirror",
    "A painted egg", "A worn prayer bead", "A handful of clay", "A cracked bowl",
    "A dog's collar", "A spool of flax", "A pair of knitting needles", "A sprig of wild thyme",
    "A basket of mushrooms", "A sheep's bell", "A sprig of lavender", "A handful of ash from the hearth",
    "A broken flute", "A loaf of barley bread", "A ribbon for the harvest dance", "A bag of nails",
    "A small sack of flour", "A sprig of nettle", "A jug of cider", "A ring lost in the mud",
    "A jar of goose fat", "A cracked hand mirror", "A child's wooden toy", "A set of brass weights",
    "A jar of berry jam", "A chipped cooking pot", "A sheep's fleece", "A spool of silver thread",
    "A bag of grain", "A pinch of incense", "A wooden comb", "A sprig of mistletoe",
    "A clay whistle", "A fishhook", "A pouch of dried mint", "A bottle of homemade ale",
    "A smooth river stone", "A missing button", "A cracked cup", "A jar of preserved pears",
    "A spool of dyed thread", "A charm against fever", "A string of beads", "A pair of worn gloves",
    "A fox pelt", "A jug of goat's milk", "A dried rabbit's foot", "A handful of goose feathers",
    "A basket of blackberries", "A pot of gooseberry jam", "A lost wedding band", "A dog whistle",
    "A chipped pewter spoon", "A small wooden box", "A painted pebble", "A sheep's horn",
    "A copper coin from long ago", "A jar of lard", "A pot of herbal poultice", "A charm of woven grass",
    "A clutch of hen's eggs", "A child's rattle", "A string of garlic", "A sprig of yarrow",
    "A sheaf of rushes", "A spool of linen", "A strip of tanned leather", "A jar of ink",
    "A book of psalms", "A scrap of parchment", "A quill feather", "A pouch of seeds",
    "A sprig of rosemary", "A handful of sand", "A jug of spring water", "A chipped lantern glass",
    "A candle stub", "A lost pendant", "A dried sprig of sage", "A clay idol",
    "A jug stopper", "A piece of broken pottery", "A splinter of driftwood", "A small bronze key",
    "A doll's head", "A patch of homespun cloth", "A bottle of lamp oil", "A spool of hemp twine",
    "A length of rope", "A wicker basket", "A hand mirror", "A cracked pipe",
    "A goose quill", "A bar of soap", "A dried bouquet", "A lock of horsehair",
    "A piece of chalk", "A handful of barley husks", "A small hammer", "A pair of shears",
    "A jar of salve", "A cat's collar bell", "A leather strap", "A handful of soot",
    "A patch of beeswax candle", "A smooth pebble with runes", "A sprig of hawthorn", "A broken charm bracelet",
    "A scrap of red cloth", "A cup of milk for the Good Folk", "A small sickle", "A chipped bowl from the inn",
    "A silver thimble", "A missing glove", "A child's sketchbook", "A dried poppy",
    "A handful of crushed herbs", "A copper brooch", "A pouch of crushed chalk", "A jar of butter",
    "A spoon carved from oak", "A string of dried apples", "A clay pendant", "A lost boot buckle",
    "A sack of potatoes", "A torn piece of tapestry", "A lump of coal", "A folded handkerchief",
    "A charm of seashells", "A page from a hymnbook", "A fish scale that shines like silver", "A carved flute reed",
    "A seed pod from a sacred tree", "A spool of gold thread", "A lamb's wool cap", "A piece of broken jewelry",
    "A small cask of ale", "A jug of honeywine", "A sprig of foxglove", "A sprig of holly",
    "A bucket of fresh water", "A clay cup from the well", "A handful of white sand", "A cat's pawprint charm",
    "A bit of charred wood from a fire", "A feather from a swan", "A scrap of fur from a white hare", "A spindle of spun wool",
    "A broken brooch", "A cracked mirror frame", "A pouch of mead yeast", "A set of mismatched buttons",
    "A carved walking stick head", "A spool of copper wire", "A carved bead from a rosary", "A vial of perfume",
    "A wooden bowl carved with spirals", "A lost diary page", "A faded ribbon", "A spool of black thread",
    "A tattered love letter", "A sheepdog whistle", "A silver pin", "A sprig of juniper",
    "A handful of acorns", "A sheep's tag", "A cracked mug from the tavern", "A handful of thistle seeds",
    "A bottle of strong spirits", "A sprig of gorse", "A hen's feather", "A pouch of ash",
    "A single horseshoe nail", "A patch from a banner", "A child's marble", "A lump of amber",
    "A dried fish tail", "A small sack of salt", "A piece of chalked slate", "A sprig of broom",
    "A carved love token", "A straw hat", "A smoothed river shell", "A torn bit of parchment map",
    "A clump of turf", "A sprig of elderflower", "A bottle cork", "A cracked pocket knife",
    "A leather-bound charm book", "A small anvil stone", "A spool of crimson ribbon", "A set of wooden dice",
    "A pouch of lye", "A carved wooden pipe", "A sprig of ivy", "A pail of goat's milk",
    "A half-burned candle", "A coil of fishing line", "A silver earring", "A clump of wool from a fencepost",
    "A clay jar stopper", "A bundle of firewood", "A lost prayer ribbon", "A sprig of basil",
    "A bunch of grapes", "A sack of turnips", "A broken scythe handle", "A dog's lead",
    "A rabbit snare", "A pouch of spice", "A cracked pewter cup", "A faded family locket",
    "A small crystal shard", "A handwoven belt", "A dried sprig of mint", "A set of old keys",
    "A spool of silver wire", "A handful of pebbles from the stream", "A clay pipe stem", "A sprig of marigold",
    "A vial of blue dye", "A sheep's tag bell", "A lost coin", "A plowshare pin",
    "A sliver of driftwood cross", "A carved bird figurine", "A pair of spectacles", "A candle mold",
    "A scrap of embroidered linen", "A trinket box", "A bit of polished bone", "A set of sewing needles",
    "A small iron buckle", "A handkerchief embroidered with initials", "A lost comb", "A fragment of pottery tile",
    "A chipped tea cup", "A bottle of vinegar", "A hair ribbon", "A spool of coarse twine",
    "A chicken feather quill", "A lump of sap resin", "A spool of gray yarn", "A clay lamp",
    "A ring made of woven grass", "A pouch of ground barley", "A spool of undyed flax", "A faded festival token",
    "A charm carved from driftwood", "A fragment of stained glass", "A broken bell clapper", "A sheep's ear tag",
    "A basket handle", "A cracked horseshoe", "A sprig of meadow sage", "A milk jug stopper",
    "A wooden bead bracelet", "A pebble shaped like a heart", "A clay bird whistle", "A pouch of ashes",
    "A sprig of meadow rue", "A cracked jug", "A flask of nettle beer", "A chipped plate",
    "A spool of green thread", "A child's wooden sword", "A sprig of bog myrtle", "A pressed flower",
    "A silver clasp", "A bit of beeswax polish", "A pouch of chalk dust", "A small cloth pouch of pins",
    "A wooden rosary bead", "A worn shoe buckle", "A copper pin", "A sheep's hoof trimming",
    "A thimble of tin", "A clay amulet", "A handful of wheat kernels", "A set of old playing cards",
    "A cracked cooking lid", "A spool of golden cord", "A sprig of fennel", "A polished stone pendant",
    "A piece of parchment seal", "A scrap of blue velvet", "A piece of dried peat", "A painted wooden charm",
    "A drop of sealing wax", "A sprig of hemlock", "A carved ring box", "A pouch of chalked lime",
    "A small jar of molasses", "A splinter of saint's bone (or so they say)", "A half-written letter", "A clay figurine",
    "A worn shoe", "A bit of goat's cheese", "A sprig of meadow mint", "A pouch of ground herbs",
    "A bunch of onions", "A spool of black hair ribbon", "A sprig of bog cotton", "A small tin whistle",
    "A tiny bottle of perfume", "A smoothed bone dice", "A silver hairpin", "A pouch of earth from a grave",
    "A sprig of pennyroyal", "A clutch of duck eggs", "A scrap of parchment charm", "A folded note sealed with wax",
    "A sprig of chamomile", "A bit of carved antler", "A small jar of pickled onions", "A handful of barley husk",
    "A pewter badge", "A spool of red silk", "A piece of driftwood shaped like a fish", "A sprig of tansy",
    "A woven bracelet", "A cracked bottle stopper", "A clay oil lamp", "A token from a fair",
    "A silver spoon", "A child's chalk drawing", "A sprig of fern", "A wooden spinning top",
    "A spool of pale blue thread", "A bag of dried peas", "A sprig of clover", "A doll made of corn husks",
    "A rabbit pelt", "A chipped pewter plate", "A handful of feathers", "A pouch of powdered dye",
    "A sprig of angelica", "A bag of beans", "A sprig of valerian", "A small clay pot",
    "A handful of river mud", "A spool of rope fiber", "A sprig of lemon balm", "A goose feather quill",
    "A brass button", "A sprig of elder bark", "A lock of baby's hair", "A polished conch shell",
    "A sprig of rue", "A cracked tin cup", "A dried reed flute", "A sprig of meadowsweet",
    "A feather from a crow", "A polished stone heart", "A bottle of tincture", "A spool of linen cord",
    "A bunch of nettles", "A sprig of rosemary and sage", "A bag of lime powder", "A clay tile fragment",
    "A small carved sheep", "A dried beetle wing", "A handful of dirt from the crossroads", "A sprig of sorrel",
    "A pocket knife", "A spool of crimson wool", "A smooth round pebble", "A sprig of dandelion",
    "A jar of gooseberry preserves", "A handful of flour", "A spool of hemp fiber", "A sprig of coltsfoot",
    "A cracked jug stopper", "A spool of golden thread", "A handful of dust from the church floor", "A patch of linen from a burial shroud",
    "A bunch of rushes", "A sheep's tooth charm", "A scrap of parchment from a lost ledger", "A handful of crushed eggshells",
    "A sprig of poppy", "A pebble from a saint's cairn", "A sprig of creeping thyme", "A bit of green glass",
    "A dried frog's leg", "A pouch of earth from the hilltop", "A handful of grain from the last harvest", "A tiny wooden cross",
    "A handful of straw", "A sprig of cow parsley", "A dried frog's heart (for luck, or curse)", "A spool of violet ribbon",
    "A sprig of sagebrush", "A scrap of tanned hide", "A bit of bone needle", "A drop of beeswax candle",
    "A sprig of mint and honey", "A bag of meal", "A fish bone charm", "A lock of horse mane",
    "A sprig of meadow grass", "A pinch of black salt", "A clay cup from the tavern", "A sprig of mullein",
    "A bundle of thatching straw", "A scrap of embroidered lace", "A handful of marbles", "A dried bluebell",
    "A cracked ceramic jug", "A handful of bread crumbs", "A spool of dark gray thread", "A bundle of dried heather",
    "A sheep's hoof token", "A broken rosary", "A sprig of willow bark", "A pouch of powdered chalk",
    "A bit of gold leaf", "A scrap of parchment prayer", "A sprig of horehound", "A polished snail shell",
    "A chunk of beeswax", "A piece of old chain", "A dried fern leaf", "A wooden bead charm",
    "A small brass bell", "A clay shard carved with spirals", "A glass bead", "A dried sunflower head",
    "A woolen mitten", "A sprig of yew", "A jar of black dye", "A piece of worn rope",
    "A bottle cork from the tavern", "A sprig of wolfsbane", "A bone needle", "A sprig of catmint",
    "A small wooden token carved with a spiral", "A sprig of parsley", "A pouch of barley flour", "A lock of white hair",
    "A silver button", "A handful of hay", "A pinch of soot", "A sprig of hawkweed",
    "A piece of cracked pottery", "A spool of violet silk", "A clutch of pigeon feathers", "A handful of acorn caps",
    "A sprig of fennel root", "A broken clay jug", "A copper earring", "A polished pebble with initials carved",
    "A sprig of moss", "A sprig of red clover", "A handful of snail shells", "A jar of goose grease",
    "A sprig of heather and rosemary", "A small glass bead", "A lost charm from a wedding chain", "A sprig of thyme and honey",
    "A spool of dyed crimson thread", "A bag of sugar", "A scrap of parchment torn from a hymn", "A wooden bowl full of grain",
    "A sprig of juniper berries", "A clay cup etched with runes", "A sprig of bell heather", "A cracked copper pot",
    "A dried mouse tail", "A silvered hairbrush", "A sprig of meadow lavender"
]

# Town fetch quest items (500 items)
TOWN_FETCH_QUEST_ITEMS = [
    "A blessed scroll rumored to guide travelers to the Broken Tower",
    "A blessed seal once offered at the Old Abbey",
    "A blessed silver idol recovered from the Hollow Glen",
    "A blessed spindle rumored to guide travelers to the Frostwood",
    "A brass amulet rumored to be used by the Keeper of Keys",
    "A brass amulet tied to the legends of Kildar Keep",
    "A brass tablet tied to the legends of the Moonwell",
    "A brass vial rumored to be used by the Keeper of Keys",
    "A bronze idol fragment rumored to be used by the Keeper of Keys",
    "A bronze mirror rumored to be used by Brother Cian",
    "A bronze tablet believed to protect against ill omens",
    "A bronze tablet rumored to be used by Aelric of the Crossroads",
    "A brooch adorned with wave patterns from the Frostwood",
    "A brooch carved from horn, said to ward off spirits",
    "A brooch engraved with a stag and set in stone",
    "A brooch of amber origin, etched with the mark of Lady Odran",
    "A brooch of steel, once belonging to Branwen the Pale",
    "A brooch stained with ash and blood from the Iron Marches",
    "A buckle adorned with raven patterns from the Old Abbey",
    "A buckle carved from ivory, said to ward off spirits",
    "A buckle engraved with a eye and set in horn",
    "A buckle engraved with a flame and set in horn",
    "A buckle of lead origin, etched with the mark of Lady Odran",
    "A buckle of obsidian, once belonging to Eira of the Hollow",
    "A buckle of rowanwood origin, etched with the mark of the Keeper of Keys",
    "A buckle of steel, once belonging to Brother Cian",
    "A buckle stained with ash and blood from the Frostwood",
    "A buckle stained with ash and blood from the Shrine of the Nine",
    "A buckle wrapped in bronze thread and sealed with wax",
    "A burnished bronze talisman bound in sinew and ash",
    "A burnished lead mirror said to hum softly at dusk",
    "A burnished rowanwood talisman said to hum softly at dusk",
    "A carved brooch rumored to guide travelers to the Weaver's Guild",
    "A carved talisman rumored to guide travelers to the North Gate",
    "A carved vial once offered at Kildar Keep",
    "A chalice adorned with branch patterns from Kildar Keep",
    "A chalice adorned with triskele patterns from the Weaver's Guild",
    "A chalice of gold origin, etched with the mark of the Keeper of Keys",
    "A chalice stained with ash and blood from the Isle of Mists",
    "A chalice wrapped in ashwood thread and sealed with wax",
    "A chalice wrapped in copper thread and sealed with wax",
    "A charm adorned with sunburst patterns from the Isle of Mists",
    "A charm carved from pewter, said to ward off spirits",
    "A charm carved from steel, said to ward off spirits",
    "A charm of iron, once belonging to Sorcha of the Loom",
    "A charm of lead, once belonging to Donn the Red",
    "A charm of rowanwood, once belonging to Ronan of the Isles",
    "A charm of steel, once belonging to Branwen the Pale",
    "A charm of stone, once belonging to the Keeper of Keys",
    "A codex adorned with oak leaf patterns from the Old Abbey",
    "A codex carved from crystal, said to ward off spirits",
    "A codex engraved with a hand and set in steel",
    "A codex of gold, once belonging to Sorcha of the Loom",
    "A codex of iron, once belonging to Ronan of the Isles",
    "A codex of ivory, once belonging to Aelric of the Crossroads",
    "A codex of lead, once belonging to Aelric of the Crossroads",
    "A codex of obsidian, once belonging to Lady Odran",
    "A codex of pewter origin, etched with the mark of the Drowned Scribe",
    "A codex stained with ash and blood from Kildar Keep",
    "A codex stained with ash and blood from the Hollow Glen",
    "A copper ring tarnished with the sign of a spiral",
    "A copper spindle tied to the legends of the Iron Marches",
    "A cracked buckle rumored to guide travelers to Kildar Keep",
    "A cracked goblet rumored to guide travelers to the Isle of Mists",
    "A cracked pewter buckle recovered from the Stone Circle",
    "A cracked relic once offered at the Barrow Hills",
    "A crystal amulet believed to protect against ill omens",
    "A crystal brooch shimmering with the sign of a oak leaf",
    "A crystal ring rumored to be used by Lady Odran",
    "A crystal tablet filigreed with the sign of a torch",
    "A crystal talisman tied to the legends of the Broken Tower",
    "A crystal token shimmering with the sign of a wheel",
    "A crystal vial rumored to be used by the Ashen Monk",
    "A cursed ivory pendant said to hum softly at dusk",
    "A filigreed codex rumored to guide travelers to the Old Abbey",
    "A filigreed copper mirror recovered from the Broken Tower",
    "A filigreed idol fragment rumored to guide travelers to Kildar Keep",
    "A filigreed ring once offered at the North Gate",
    "A filigreed steel amulet recovered from the Broken Tower",
    "A filigreed token rumored to guide travelers to the Frostwood",
    "A forgotten amulet once part of a set crafted by the Drowned Scribe",
    "A forgotten bronze ring bound in sinew and ash",
    "A forgotten brooch bound in lead bands",
    "A forgotten charm once part of a set crafted by Donn the Red",
    "A forgotten codex bound in tin bands",
    "A forgotten idol once part of a set crafted by Sorcha of the Loom",
    "A forgotten ivory mirror said to hum softly at dusk",
    "A forgotten ivory orb said to hum softly at dusk",
    "A forsaken horn mirror bound in sinew and ash",
    "A forsaken medallion once part of a set crafted by Maeve the Seer",
    "A gilded brooch once offered at Kildar Keep",
    "A gilded buckle once offered at the Barrow Hills",
    "A gilded oak vial recovered from the Stone Circle",
    "A gilded silver seal recovered from the Broken Tower",
    "A goblet engraved with a eye and set in steel",
    "A goblet of horn origin, etched with the mark of Sorcha of the Loom",
    "A goblet of lead origin, etched with the mark of the Ashen Monk",
    "A goblet of pewter, once belonging to Taran the Smith",
    "A goblet stained with ash and blood from the Moonwell",
    "A goblet stained with ash and blood from the Weaver's Guild",
    "A gold amulet rumored to be used by Donn the Red",
    "A gold vial rumored to be used by Maeve the Seer",
    "A hallowed amulet bound in crystal bands",
    "A hallowed codex once part of a set crafted by the Drowned Scribe",
    "A hallowed pendant bound in oak bands",
    "A hallowed pewter amulet said to hum softly at dusk",
    "A hallowed rowanwood spindle said to hum softly at dusk",
    "A hallowed scroll once part of a set crafted by the Ashen Monk",
    "A haunted amber relic said to hum softly at dusk",
    "A haunted chalice bound in bronze bands",
    "A haunted codex bound in brass bands",
    "A haunted relic once part of a set crafted by Sorcha of the Loom",
    "A haunted rowanwood rod bound in sinew and ash",
    "A haunted tablet bound in jet bands",
    "A hollowed idol fragment once offered at the Broken Tower",
    "A hollowed orb rumored to guide travelers to the Shrine of the Nine",
    "A hollowed rowanwood idol fragment recovered from the Moonwell",
    "A horn buckle rumored to be used by Donn the Red",
    "A horn idol fragment tied to the legends of the Stone Circle",
    "A horn mirror believed to protect against ill omens",
    "A jet amulet woven with the sign of a oak leaf",
    "A jet goblet tied to the legends of the Moonwell",
    "A jet tablet lacquered with the sign of a spiral",
    "A jet vial tied to the legends of the Moonwell",
    "A lead idol rumored to be used by the Drowned Scribe",
    "A lead insignia rumored to be used by Brother Cian",
    "A lead pendant rumored to be used by Donn the Red",
    "A lead rod tied to the legends of the Iron Marches",
    "A lead tablet rumored to be used by Ronan of the Isles",
    "A lead tablet tied to the legends of the Barrow Hills",
    "A lead talisman rumored to be used by Branwen the Pale",
    "A lost amulet once part of a set crafted by the Drowned Scribe",
    "A lost brooch bound in stone bands",
    "A lost codex bound in bronze bands",
    "A lost pendant once part of a set crafted by the Keeper of Keys",
    "A lost relic once part of a set crafted by the Keeper of Keys",
    "A lost tin spindle bound in sinew and ash",
    "A medallion engraved with a oak leaf and set in rowanwood",
    "A medallion engraved with a wave and set in tin",
    "A medallion engraved with a wheel and set in pewter",
    "A medallion stained with ash and blood from the Hollow Glen",
    "A medallion wrapped in pewter thread and sealed with wax",
    "A medallion wrapped in steel thread and sealed with wax",
    "A mirror adorned with moon patterns from the Hollow Glen",
    "A mirror adorned with wave patterns from the Old Abbey",
    "A mirror carved from iron, said to ward off spirits",
    "A mirror carved from rowanwood, said to ward off spirits",
    "A mirror engraved with a raven and set in steel",
    "A mirror of pewter origin, etched with the mark of the Drowned Scribe",
    "A mirror wrapped in brass thread and sealed with wax",
    "A mournful amulet bound in brass bands",
    "A mournful charm bound in lead bands",
    "A mournful copper idol fragment said to hum softly at dusk",
    "A mournful gold token bound in sinew and ash",
    "A mournful idol once part of a set crafted by the Ashen Monk",
    "A mournful insignia bound in ivory bands",
    "A mournful insignia bound in obsidian bands",
    "A mournful oak tablet said to hum softly at dusk",
    "A mournful ring bound in tin bands",
    "A mournful spindle once part of a set crafted by the Keeper of Keys",
    "A mystic horn pendant bound in sinew and ash",
    "A mystic insignia bound in iron bands",
    "A pendant adorned with crown patterns from the Weaver's Guild",
    "A pendant carved from amber, said to ward off spirits",
    "A pendant carved from iron, said to ward off spirits",
    "A pendant engraved with a sunburst and set in tin",
    "A pendant of obsidian origin, etched with the mark of Lady Odran",
    "A pendant stained with ash and blood from the Broken Tower",
    "A pendant stained with ash and blood from the Isle of Mists",
    "A pewter chalice rumored to be used by Maeve the Seer",
    "A pewter insignia carved with the sign of a stag",
    "A pewter orb tied to the legends of the Iron Marches",
    "A pewter rod tied to the legends of the Barrow Hills",
    "A pewter talisman tied to the legends of the Old Abbey",
    "A polished charm rumored to guide travelers to Kildar Keep",
    "A polished copper goblet recovered from the Isle of Mists",
    "A polished medallion once offered at the Iron Marches",
    "A polished orb once offered at the Moonwell",
    "A polished pewter idol fragment recovered from Kildar Keep",
    "A polished silver codex recovered from the Barrow Hills",
    "A polished steel charm recovered from Kildar Keep",
    "A polished tin insignia recovered from the Broken Tower",
    "A relic adorned with oak leaf patterns from the Iron Marches",
    "A relic carved from copper, said to ward off spirits",
    "A relic carved from silver, said to ward off spirits",
    "A relic engraved with a eye and set in copper",
    "A relic engraved with a torch and set in pewter",
    "A relic of amber origin, etched with the mark of Ronan of the Isles",
    "A ring adorned with crown patterns from the Weaver's Guild",
    "A ring adorned with flame patterns from the North Gate",
    "A ring adorned with triskele patterns from Kildar Keep",
    "A ring engraved with a crown and set in crystal",
    "A ring of ashwood, once belonging to the Drowned Scribe",
    "A ring of rowanwood, once belonging to Taran the Smith",
    "A ring stained with ash and blood from the Hollow Glen",
    "A ring wrapped in brass thread and sealed with wax",
    "A ring wrapped in lead thread and sealed with wax",
    "A ring wrapped in obsidian thread and sealed with wax",
    "A rod adorned with oak leaf patterns from the Weaver's Guild",
    "A rod adorned with spiral patterns from the Iron Marches",
    "A rod engraved with a crown and set in rowanwood",
    "A rod of gold origin, etched with the mark of the Keeper of Keys",
    "A rod of iron origin, etched with the mark of Eira of the Hollow",
    "A rod stained with ash and blood from the Broken Tower",
    "A rowanwood amulet believed to protect against ill omens",
    "A rowanwood medallion tied to the legends of the Moonwell",
    "A rowanwood rod rumored to be used by Ronan of the Isles",
    "A rowanwood spindle believed to protect against ill omens",
    "A sacred amulet bound in silver bands",
    "A sacred horn tablet said to hum softly at dusk",
    "A sacred idol once part of a set crafted by Brother Cian",
    "A sacred stone chalice bound in sinew and ash",
    "A scroll adorned with sunburst patterns from the Barrow Hills",
    "A scroll engraved with a thorn and set in jet",
    "A scroll of ashwood, once belonging to Aelric of the Crossroads",
    "A scroll of silver, once belonging to Eira of the Hollow",
    "A seal carved from ashwood, said to ward off spirits",
    "A seal of silver, once belonging to Donn the Red",
    "A seal wrapped in stone thread and sealed with wax",
    "A secret goblet once part of a set crafted by Eira of the Hollow",
    "A secret insignia bound in tin bands",
    "A secret mirror once part of a set crafted by Ronan of the Isles",
    "A secret pewter codex said to hum softly at dusk",
    "A secret pewter goblet bound in sinew and ash",
    "A secret silver medallion bound in sinew and ash",
    "A secret token once part of a set crafted by the Drowned Scribe",
    "A shimmering ring rumored to guide travelers to the Hollow Glen",
    "A shimmering vial once offered at the Barrow Hills",
    "A silver codex rumored to be used by the Ashen Monk",
    "A silver goblet believed to protect against ill omens",
    "A silver goblet tied to the legends of the Iron Marches",
    "A silver medallion hollowed with the sign of a raven",
    "A silver pendant tied to the legends of the Frostwood",
    "A silver ring rumored to be used by Sorcha of the Loom",
    "A silver talisman rumored to be used by Lady Odran",
    "A silver token inlaid with the sign of a oak leaf",
    "A silver vial believed to protect against ill omens",
    "A spindle adorned with crown patterns from Kildar Keep",
    "A spindle adorned with moon patterns from the Old Abbey",
    "A spindle adorned with wave patterns from the Hollow Glen",
    "A spindle carved from crystal, said to ward off spirits",
    "A spindle carved from silver, said to ward off spirits",
    "A spindle engraved with a oak leaf and set in lead",
    "A spindle stained with ash and blood from the Frostwood",
    "A spindle stained with ash and blood from the Iron Marches",
    "A spindle stained with ash and blood from the Weaver's Guild",
    "A spindle wrapped in brass thread and sealed with wax",
    "A spindle wrapped in iron thread and sealed with wax",
    "A spindle wrapped in stone thread and sealed with wax",
    "A stamped chalice rumored to guide travelers to Kildar Keep",
    "A stamped iron brooch recovered from the Old Abbey",
    "A stamped mirror once offered at the Frostwood",
    "A stamped oak goblet recovered from the Barrow Hills",
    "A stamped relic rumored to guide travelers to the North Gate",
    "A steel buckle believed to protect against ill omens",
    "A steel seal rumored to be used by Eira of the Hollow",
    "A steel spindle tied to the legends of the Moonwell",
    "A steel token believed to protect against ill omens",
    "A stone chalice rumored to be used by the Ashen Monk",
    "A stone charm believed to protect against ill omens",
    "A stone idol aged with the sign of a crown",
    "A stone rod tied to the legends of the Moonwell",
    "A stone seal rumored to be used by Taran the Smith",
    "A stone seal tied to the legends of the Moonwell",
    "A sung idol once part of a set crafted by the Drowned Scribe",
    "A sung mirror bound in brass bands",
    "A sung oak rod said to hum softly at dusk",
    "A sung stone relic said to hum softly at dusk",
    "A sung tablet once part of a set crafted by Ronan of the Isles",
    "A sung talisman bound in tin bands",
    "A sung tin seal bound in sinew and ash",
    "A sung token bound in ivory bands",
    "A tablet carved from iron, said to ward off spirits",
    "A tablet of ivory origin, etched with the mark of Branwen the Pale",
    "A tablet stained with ash and blood from Kildar Keep",
    "A tablet stained with ash and blood from the Isle of Mists",
    "A tablet stained with ash and blood from the Weaver's Guild",
    "A talisman adorned with branch patterns from the Stone Circle",
    "A talisman adorned with torch patterns from the North Gate",
    "A talisman carved from jet, said to ward off spirits",
    "A talisman stained with ash and blood from the Iron Marches",
    "A talisman stained with ash and blood from the Isle of Mists",
    "A talisman wrapped in crystal thread and sealed with wax",
    "A tarnished ashwood codex recovered from the Iron Marches",
    "A tarnished insignia once offered at the Old Abbey",
    "A tarnished ring once offered at the Hollow Glen",
    "A tarnished rod rumored to guide travelers to the Frostwood",
    "A tarnished steel seal recovered from the Iron Marches",
    "A tarnished vial rumored to guide travelers to the Moonwell",
    "A tin charm believed to protect against ill omens",
    "A tin pendant rumored to be used by Aelric of the Crossroads",
    "A tin relic tied to the legends of the Old Abbey",
    "A tin spindle tied to the legends of the Moonwell",
    "A tin talisman tied to the legends of the Broken Tower",
    "A tin vial tied to the legends of the North Gate",
    "A token adorned with serpent patterns from the Weaver's Guild",
    "A token adorned with sunburst patterns from the Frostwood",
    "A token carved from brass, said to ward off spirits",
    "A token carved from rowanwood, said to ward off spirits",
    "A token carved from silver, said to ward off spirits",
    "A token of amber, once belonging to Maeve the Seer",
    "A token of brass, once belonging to the Drowned Scribe",
    "A token of crystal, once belonging to Eira of the Hollow",
    "A token of iron, once belonging to the Drowned Scribe",
    "A token wrapped in oak thread and sealed with wax",
    "A venerated amber ring bound in sinew and ash",
    "A venerated ashwood idol fragment said to hum softly at dusk",
    "A venerated brass relic bound in sinew and ash",
    "A venerated idol fragment bound in amber bands",
    "A venerated rowanwood amulet bound in sinew and ash",
    "A venerated seal bound in copper bands",
    "A venerated silver idol said to hum softly at dusk",
    "A venerated spindle bound in gold bands",
    "A venerated spindle once part of a set crafted by Aelric of the Crossroads",
    "A venerated steel insignia said to hum softly at dusk",
    "A venerated token bound in jet bands",
    "A vial adorned with oak leaf patterns from the Barrow Hills",
    "A vial adorned with wheel patterns from the Hollow Glen",
    "A vial carved from horn, said to ward off spirits",
    "A vial engraved with a serpent and set in amber",
    "A vial engraved with a triskele and set in ivory",
    "A vial engraved with a wheel and set in ashwood",
    "A vial of ashwood, once belonging to Aelric of the Crossroads",
    "A weathered gold charm recovered from the Moonwell",
    "A weathered ivory buckle recovered from Kildar Keep",
    "A weathered medallion rumored to guide travelers to the Old Abbey",
    "A weathered mirror rumored to guide travelers to the Stone Circle",
    "A woven scroll rumored to guide travelers to the Old Abbey",
    "A woven spindle once offered at the Barrow Hills",
    "A woven steel idol recovered from the Shrine of the Nine",
    "An aged buckle rumored to guide travelers to Kildar Keep",
    "An aged buckle rumored to guide travelers to the Barrow Hills",
    "An aged obsidian idol fragment recovered from the Old Abbey",
    "An aged tin medallion recovered from the Moonwell",
    "An amber amulet believed to protect against ill omens",
    "An amber goblet enameled with the sign of a flame",
    "An amber orb tied to the legends of the North Gate",
    "An amber scroll tied to the legends of the Frostwood",
    "An amber seal filigreed with the sign of a sunburst",
    "An amber spindle tied to the legends of the Barrow Hills",
    "An amulet adorned with raven patterns from Kildar Keep",
    "An amulet carved from ashwood, said to ward off spirits",
    "An amulet carved from oak, said to ward off spirits",
    "An amulet carved from pewter, said to ward off spirits",
    "An amulet carved from tin, said to ward off spirits",
    "An amulet engraved with a boar and set in bronze",
    "An amulet engraved with a boar and set in gold",
    "An amulet engraved with a wheel and set in ashwood",
    "An amulet of steel origin, etched with the mark of Ronan of the Isles",
    "An amulet wrapped in brass thread and sealed with wax",
    "An amulet wrapped in silver thread and sealed with wax",
    "An amulet wrapped in steel thread and sealed with wax",
    "An ancient brooch once part of a set crafted by Eira of the Hollow",
    "An ancient brooch once part of a set crafted by the Keeper of Keys",
    "An ancient charm once part of a set crafted by Taran the Smith",
    "An ancient pewter idol fragment bound in sinew and ash",
    "An ashwood buckle believed to protect against ill omens",
    "An ashwood charm tied to the legends of the Shrine of the Nine",
    "An ashwood codex tied to the legends of the Isle of Mists",
    "An ashwood idol fragment believed to protect against ill omens",
    "An ashwood medallion shimmering with the sign of a crown",
    "An ashwood pendant believed to protect against ill omens",
    "An ashwood pendant rumored to be used by Ronan of the Isles",
    "An ashwood ring believed to protect against ill omens",
    "An ashwood rod polished with the sign of a triskele",
    "An eldritch amber idol fragment said to hum softly at dusk",
    "An eldritch brass chalice bound in sinew and ash",
    "An eldritch buckle once part of a set crafted by Maeve the Seer",
    "An eldritch gold tablet bound in sinew and ash",
    "An eldritch mirror bound in iron bands",
    "An eldritch rod bound in gold bands",
    "An eldritch scroll bound in steel bands",
    "An embellished crystal spindle recovered from the Barrow Hills",
    "An embellished idol once offered at the Isle of Mists",
    "An embellished mirror once offered at the Shrine of the Nine",
    "An embossed brass amulet recovered from the Old Abbey",
    "An embossed charm rumored to guide travelers to the Broken Tower",
    "An embossed codex once offered at the Old Abbey",
    "An embossed oak pendant recovered from the Old Abbey",
    "An embossed ring once offered at the Isle of Mists",
    "An embossed stone seal recovered from the Old Abbey",
    "An embossed stone tablet recovered from the Stone Circle",
    "An enameled crystal buckle recovered from the Hollow Glen",
    "An enameled insignia once offered at the Old Abbey",
    "An enameled rod once offered at the Old Abbey",
    "An enameled tablet once offered at the North Gate",
    "An engraved copper amulet recovered from the Barrow Hills",
    "An engraved pendant once offered at the Barrow Hills",
    "An idol engraved with a stag and set in copper",
    "An idol fragment carved from copper, said to ward off spirits",
    "An idol fragment carved from gold, said to ward off spirits",
    "An idol fragment engraved with a torch and set in brass",
    "An idol fragment of bronze, once belonging to Donn the Red",
    "An idol fragment of copper origin, etched with the mark of Branwen the Pale",
    "An idol fragment of copper origin, etched with the mark of Donn the Red",
    "An idol fragment stained with ash and blood from the Barrow Hills",
    "An idol fragment stained with ash and blood from the Iron Marches",
    "An idol fragment stained with ash and blood from the North Gate",
    "An idol fragment wrapped in bronze thread and sealed with wax",
    "An idol of gold, once belonging to Maeve the Seer",
    "An idol of pewter origin, etched with the mark of Donn the Red",
    "An idol stained with ash and blood from Kildar Keep",
    "An idol stained with ash and blood from the Hollow Glen",
    "An inlaid ashwood tablet recovered from Kildar Keep",
    "An inlaid gold tablet recovered from the Shrine of the Nine",
    "An inlaid obsidian chalice recovered from Kildar Keep",
    "An inlaid token once offered at the Iron Marches",
    "An inscribed brooch from the Stone Circle, bearing faint script",
    "An inscribed buckle from the Old Abbey, bearing faint script",
    "An inscribed chalice from the Frostwood, bearing faint script",
    "An inscribed codex from the Hollow Glen, bearing faint script",
    "An inscribed goblet from Kildar Keep, bearing faint script",
    "An inscribed idol fragment from the Frostwood, bearing faint script",
    "An inscribed idol from the Iron Marches, bearing faint script",
    "An inscribed idol from the Shrine of the Nine, bearing faint script",
    "An inscribed insignia from the Barrow Hills, bearing faint script",
    "An inscribed medallion from the Hollow Glen, bearing faint script",
    "An inscribed mirror from the Moonwell, bearing faint script",
    "An inscribed orb from Kildar Keep, bearing faint script",
    "An inscribed pendant from the Barrow Hills, bearing faint script",
    "An inscribed relic from the Moonwell, bearing faint script",
    "An inscribed seal from the Broken Tower, bearing faint script",
    "An inscribed spindle from Kildar Keep, bearing faint script",
    "An inscribed tablet from the Stone Circle, bearing faint script",
    "An inscribed tablet from the Weaver's Guild, bearing faint script",
    "An inscribed token from the Moonwell, bearing faint script",
    "An inscribed vial from the Frostwood, bearing faint script",
    "An inscribed vial from the Moonwell, bearing faint script",
    "An inscribed vial from the Weaver's Guild, bearing faint script",
    "An insignia adorned with spiral patterns from the Stone Circle",
    "An insignia engraved with a thorn and set in gold",
    "An insignia engraved with a triskele and set in stone",
    "An insignia engraved with a wave and set in jet",
    "An insignia of obsidian origin, etched with the mark of Taran the Smith",
    "An insignia stained with ash and blood from the North Gate",
    "An insignia wrapped in crystal thread and sealed with wax",
    "An insignia wrapped in jet thread and sealed with wax",
    "An iron brooch inlaid with the sign of a stag",
    "An iron chalice rumored to be used by Aelric of the Crossroads",
    "An iron ring rumored to be used by Aelric of the Crossroads",
    "An ivory amulet rumored to be used by Maeve the Seer",
    "An ivory amulet tied to the legends of the Iron Marches",
    "An ivory buckle filigreed with the sign of a torch",
    "An ivory codex blessed with the sign of a flame",
    "An ivory medallion rumored to be used by Sorcha of the Loom",
    "An ivory rod believed to protect against ill omens",
    "An ivory spindle believed to protect against ill omens",
    "An ivory talisman believed to protect against ill omens",
    "An oak orb believed to protect against ill omens",
    "An oak orb rumored to be used by Eira of the Hollow",
    "An oak pendant hollowed with the sign of a raven",
    "An oak spindle believed to protect against ill omens",
    "An oak token tied to the legends of the Isle of Mists",
    "An obsidian medallion believed to protect against ill omens",
    "An obsidian mirror believed to protect against ill omens",
    "An obsidian talisman tied to the legends of the Old Abbey",
    "An obsidian vial enameled with the sign of a branch",
    "An orb adorned with boar patterns from the Weaver's Guild",
    "An orb carved from iron, said to ward off spirits",
    "An orb of rowanwood origin, etched with the mark of Branwen the Pale",
    "An orb wrapped in obsidian thread and sealed with wax",
    "An unfinished amulet left by Lady Odran in the Frostwood",
    "An unfinished amulet left by the Ashen Monk in the North Gate",
    "An unfinished brooch left by Brother Cian in the Barrow Hills",
    "An unfinished brooch left by Lady Odran in the Hollow Glen",
    "An unfinished buckle left by Lady Odran in the Broken Tower",
    "An unfinished charm left by Sorcha of the Loom in the Stone Circle",
    "An unfinished charm left by the Drowned Scribe in the Iron Marches",
    "An unfinished goblet left by Donn the Red in Kildar Keep",
    "An unfinished goblet left by Lady Odran in Kildar Keep",
    "An unfinished goblet left by Sorcha of the Loom in the Hollow Glen",
    "An unfinished idol fragment left by Maeve the Seer in the Hollow Glen",
    "An unfinished idol left by Aelric of the Crossroads in the Barrow Hills",
    "An unfinished idol left by the Keeper of Keys in the Weaver's Guild",
    "An unfinished medallion left by Brother Cian in the Iron Marches",
    "An unfinished medallion left by the Keeper of Keys in the Hollow Glen",
    "An unfinished mirror left by Eira of the Hollow in the Hollow Glen",
    "An unfinished orb left by Sorcha of the Loom in the Old Abbey",
    "An unfinished relic left by Aelric of the Crossroads in the Old Abbey",
    "An unfinished relic left by Ronan of the Isles in the Old Abbey",
    "An unfinished relic left by the Drowned Scribe in the North Gate",
    "An unfinished scroll left by Eira of the Hollow in the Broken Tower",
    "An unfinished scroll left by Eira of the Hollow in the Frostwood",
    "An unfinished seal left by the Keeper of Keys in the Stone Circle",
    "An unfinished talisman left by Branwen the Pale in the Old Abbey",
    "An unfinished talisman left by Sorcha of the Loom in the Iron Marches",
    "An unfinished token left by Maeve the Seer in the Barrow Hills",
    "An unfinished vial left by Donn the Red in the Frostwood",
    "An unfinished vial left by Lady Odran in the Moonwell",
    "An unhallowed amulet bound in stone bands",
    "An unhallowed bronze charm bound in sinew and ash",
    "An unhallowed copper token said to hum softly at dusk",
    "An unhallowed horn goblet said to hum softly at dusk",
    "An unhallowed idol fragment bound in silver bands",
    "An unhallowed iron spindle said to hum softly at dusk",
    "An unhallowed ivory buckle said to hum softly at dusk",
    "An unhallowed jet talisman bound in sinew and ash",
    "An unhallowed lead charm bound in sinew and ash",
    "An unhallowed steel goblet said to hum softly at dusk",
    "An unhallowed tablet bound in copper bands"
]

# City fetch quest items (500 items)
CITY_FETCH_QUEST_ITEMS = [
    "A banner forged from stormsilver in the age of Danu the Mother",
    "A banner forged from wyrdstone in the age of Bran the Blessed",
    "A banner forged of dragonscale, used to crown Cairn of the Broken Crown",
    "A banner of demon-bronze origin, bearing the seal of a thorn",
    "A blade of obsidian origin, radiating the aura of Bodb Derg",
    "A blade of soul-iron origin, radiating the aura of Eira the Eternal",
    "A blade of spiritwood origin, bearing the seal of a wolf",
    "A blazing diadem forged to bind the power of a storm",
    "A blazing mask said to whisper with the voice of Taranis the Thunderer",
    "A blazing mask that hums softly with the will of Eithne of the Shining Veil",
    "A blazing stormsilver mirror said to be tempered by song",
    "A blazing tablet said to hold the essence of Cú Chulainn",
    "A blazing talisman said to hold the essence of Goibniu the Smith",
    "A blazing wyrdstone rune said to be tempered by song",
    "A blighted amulet tied by fate to the will of Maeve the Witch Queen",
    "A blighted mask that glows when a spiral is near",
    "A blighted tablet that glows when a mirror is near",
    "A blood-amber pendant engraved with the likeness of a raven",
    "A burning heartstone said to whisper with the voice of Danu the Mother",
    "A burning rune said to hold the essence of Danu the Mother",
    "A burning scepter crafted by Manannán mac Lir to channel divine power",
    "A celestial amulet that glows when a dragon is near",
    "A celestial eldwood orb once offered to Arawn of Annwn as tribute",
    "A celestial idol that glows when a key is near",
    "A celestial relic that glows when a stag is near",
    "A celestial rune forged of sky-crystal during the age of Bres the Fair",
    "A celestial shadowglass spear believed to be blessed by Goibniu the Smith",
    "A celestial torch that glows when a key is near",
    "A celestial wyrdstone talisman believed to be blessed by Nuada of the Silver Hand",
    "A celestial wyrm-bone seal once offered to Lugh of the Long Arm as tribute",
    "A chalice forged from wyrdsteel in the age of Goibniu the Smith",
    "A chalice forged of demon-bronze, used to crown Danu the Mother",
    "A chalice of blood-amber origin, radiating the aura of Maeve the Witch Queen",
    "A chalice of dragonscale origin, bearing the seal of a crown",
    "A chalice of meteoric iron origin, radiating the aura of Maeve the Witch Queen",
    "A chalice of meteoric iron, glowing faintly with the mark of a flame",
    "A chalice of meteoric iron, glowing faintly with the mark of a key",
    "A chalice of phoenix-feather, glowing faintly with the mark of a rose",
    "A chalice of sky-crystal origin, bearing the seal of a sunburst",
    "A chalice of soul-iron, glowing faintly with the mark of a mirror",
    "A chalice of sun-gold origin, bearing the seal of a sword",
    "A chalice of wyrm-bone, glowing faintly with the mark of a rose",
    "A corrupted amulet crafted by The Morrígan to channel divine power",
    "A corrupted crown forged to bind the power of a crown",
    "A corrupted crown said to hold the essence of Balor of the Evil Eye",
    "A corrupted crown said to hold the essence of Nuada of the Silver Hand",
    "A corrupted grimoire said to hold the essence of Manannán mac Lir",
    "A corrupted heartstone that hums softly with the will of Fionn mac Cumhaill",
    "A corrupted hourglass said to whisper with the voice of Bres the Fair",
    "A corrupted key said to hold the essence of Eira the Eternal",
    "A corrupted stormsilver mask said to be tempered by song",
    "A corrupted wyrdsteel blade said to be tempered by song",
    "A corrupted wyrdstone hourglass said to be tempered by song",
    "A cracked banner forged to bind the power of a phoenix",
    "A cracked grimoire that hums softly with the will of Balor of the Evil Eye",
    "A cracked heartstone crafted by Lugh of the Long Arm to channel divine power",
    "A cracked mirror crafted by Cú Chulainn to channel divine power",
    "A cracked rune born from the dreams of Maeve the Witch Queen",
    "A cracked scepter that hums softly with the will of Balor of the Evil Eye",
    "A cracked seal said to hold the essence of Maeve the Witch Queen",
    "A crown forged of obsidian, used to crown Lugh of the Long Arm",
    "A crown of demon-bronze origin, bearing the seal of a stag",
    "A crown of dragonscale origin, radiating the aura of Lugh of the Long Arm",
    "A crown of starsteel origin, radiating the aura of Taranis the Thunderer",
    "A crown of stormsilver origin, radiating the aura of Danu the Mother",
    "A cursed blade said to hold the essence of Cú Chulainn",
    "A cursed chalice forged to bind the power of a tree of life",
    "A cursed grimoire said to whisper with the voice of Taranis the Thunderer",
    "A cursed mask forged to bind the power of a storm",
    "A cursed meteoric iron rod said to be tempered by song",
    "A cursed ring born from the dreams of Bres the Fair",
    "A cursed seal forged to bind the power of a raven",
    "A cursed seal said to hold the essence of Bodb Derg",
    "A demon-bronze blade engraved with the likeness of a eye",
    "A demon-bronze blade inscribed with the prayer of The Morrígan",
    "A demon-bronze diadem inscribed with the prayer of Goibniu the Smith",
    "A demon-bronze idol engraved with the likeness of a mirror",
    "A demon-bronze torch once wielded by Goibniu the Smith in a forgotten war",
    "A diadem forged from spiritwood in the age of Neit the War-God",
    "A diadem forged of dragonscale, used to crown Dagda the Great",
    "A diadem forged of wyrm-bone, used to crown Taranis the Thunderer",
    "A diadem of dragonscale origin, bearing the seal of a key",
    "A diadem of stormsilver origin, bearing the seal of a crescent moon",
    "A diadem of stormsilver origin, bearing the seal of a crown",
    "A divine blade crafted by Balor of the Evil Eye to channel divine power",
    "A divine blade that hums softly with the will of Fionn mac Cumhaill",
    "A divine demon-bronze diadem said to be tempered by song",
    "A divine etherglass ring once offered to Manannán mac Lir as tribute",
    "A divine grimoire that glows when a rose is near",
    "A divine heartstone forged of etherglass during the age of Cairn of the Broken Crown",
    "A divine idol forged of shadowglass during the age of Fionn mac Cumhaill",
    "A divine key tied by fate to the will of Bodb Derg",
    "A divine mask forged of eldwood during the age of Balor of the Evil Eye",
    "A divine mask forged to bind the power of a stag",
    "A divine meteoric iron blade said to be tempered by song",
    "A divine mirror said to whisper with the voice of Manannán mac Lir",
    "A divine mirror that hums softly with the will of Neit the War-God",
    "A divine mirror tied by fate to the will of Manannán mac Lir",
    "A divine moonstone hourglass once offered to Bran the Blessed as tribute",
    "A divine rod born from the dreams of Dagda the Great",
    "A divine rune that hums softly with the will of Manannán mac Lir",
    "A divine wyrdstone grimoire believed to be blessed by Eithne of the Shining Veil",
    "A divine wyrdstone rod once offered to Goibniu the Smith as tribute",
    "A dragonscale hourglass engraved with the likeness of a wolf",
    "A dragonscale key once wielded by Cú Chulainn in a forgotten war",
    "A dragonscale pendant engraved with the likeness of a sunburst",
    "A dragonscale relic engraved with the likeness of a stag",
    "A dread blade that glows when a crescent moon is near",
    "A dread crown that glows when a stag is near",
    "A dread spear tied by fate to the will of Taranis the Thunderer",
    "A dread stormsilver key once offered to Bres the Fair as tribute",
    "A dread tablet tied by fate to the will of Neit the War-God",
    "A fated blood-amber rod believed to be blessed by Taranis the Thunderer",
    "A fated dragonscale heartstone believed to be blessed by Bodb Derg",
    "A fated key forged of wyrdsteel during the age of Bres the Fair",
    "A fated mask forged of meteoric iron during the age of Cú Chulainn",
    "A fated seal that glows when a stag is near",
    "A fated starsteel mirror once offered to Bres the Fair as tribute",
    "A fated wyrdsteel tablet believed to be blessed by Eira the Eternal",
    "A fated wyrm-bone talisman once offered to Eira the Eternal as tribute",
    "A forgotten banner that hums softly with the will of Bodb Derg",
    "A forgotten heartstone crafted by Cairn of the Broken Crown to channel divine power",
    "A forgotten mask forged to bind the power of a stag",
    "A forgotten mirror born from the dreams of Taranis the Thunderer",
    "A forgotten ring said to hold the essence of Bres the Fair",
    "A forgotten scepter that hums softly with the will of Nuada of the Silver Hand",
    "A forgotten spear crafted by Dagda the Great to channel divine power",
    "A forgotten spear crafted by Neit the War-God to channel divine power",
    "A forgotten tablet born from the dreams of Bres the Fair",
    "A forgotten talisman born from the dreams of Eira the Eternal",
    "A forsworn chalice forged of spiritwood during the age of Neit the War-God",
    "A forsworn demon-bronze ring once offered to Taranis the Thunderer as tribute",
    "A forsworn dragonscale idol believed to be blessed by Manannán mac Lir",
    "A forsworn hourglass forged of spiritwood during the age of Bres the Fair",
    "A forsworn idol that glows when a phoenix is near",
    "A forsworn pendant that glows when a stag is near",
    "A forsworn stormsilver idol once offered to Arawn of Annwn as tribute",
    "A gilded chalice said to whisper with the voice of Cú Chulainn",
    "A gilded heartstone that hums softly with the will of Cairn of the Broken Crown",
    "A gilded pendant that hums softly with the will of Cú Chulainn",
    "A gilded relic forged to bind the power of a serpent",
    "A gilded scepter that hums softly with the will of Goibniu the Smith",
    "A gilded seal born from the dreams of Balor of the Evil Eye",
    "A gilded tablet said to hold the essence of The Morrígan",
    "A gilded wyrdstone grimoire said to be tempered by song",
    "A grimoire forged of sun-gold, used to crown Maeve the Witch Queen",
    "A hallowed amulet born from the dreams of Dagda the Great",
    "A hallowed chalice born from the dreams of Maeve the Witch Queen",
    "A hallowed chalice that hums softly with the will of Cú Chulainn",
    "A hallowed crown that hums softly with the will of Goibniu the Smith",
    "A hallowed diadem born from the dreams of Goibniu the Smith",
    "A hallowed diadem said to hold the essence of Taranis the Thunderer",
    "A hallowed heartstone said to hold the essence of Bres the Fair",
    "A hallowed pendant said to hold the essence of Nuada of the Silver Hand",
    "A hallowed rod forged to bind the power of a mirror",
    "A heartstone forged from phoenix-feather in the age of Goibniu the Smith",
    "A heartstone forged from phoenix-feather in the age of Neit the War-God",
    "A heartstone of dragonscale origin, bearing the seal of a tree of life",
    "A heartstone of eldwood origin, radiating the aura of Arawn of Annwn",
    "A heartstone of etherglass origin, bearing the seal of a crown",
    "A heavenly dragonscale mask believed to be blessed by Dagda the Great",
    "A heavenly eldwood rod once offered to Cairn of the Broken Crown as tribute",
    "A heavenly heartstone tied by fate to the will of Arawn of Annwn",
    "A heavenly idol that glows when a storm is near",
    "A heavenly meteoric iron torch once offered to Eithne of the Shining Veil as tribute",
    "A heavenly pendant that glows when a serpent is near",
    "A heavenly relic tied by fate to the will of Balor of the Evil Eye",
    "A heavenly rune tied by fate to the will of Taranis the Thunderer",
    "A heavenly tablet that glows when a crown is near",
    "A heroic ring tied by fate to the will of Manannán mac Lir",
    "A heroic rune forged of meteoric iron during the age of Eira the Eternal",
    "A heroic spear forged of demon-bronze during the age of Balor of the Evil Eye",
    "A heroic sun-gold amulet once offered to Bres the Fair as tribute",
    "A heroic torch forged of moonstone during the age of Cú Chulainn",
    "A hourglass forged from etherglass in the age of Manannán mac Lir",
    "A hourglass forged from soul-iron in the age of Dagda the Great",
    "A hourglass forged of blood-amber, used to crown Arawn of Annwn",
    "A hourglass of dragonscale origin, radiating the aura of The Morrígan",
    "A hourglass of meteoric iron origin, bearing the seal of a wolf",
    "A hourglass of moonstone origin, bearing the seal of a dragon",
    "A hourglass of stormsilver origin, radiating the aura of Lugh of the Long Arm",
    "A key forged from blood-amber in the age of Cú Chulainn",
    "A key forged from wyrdsteel in the age of Cú Chulainn",
    "A key of sky-crystal origin, bearing the seal of a rose",
    "A key of wyrm-bone, glowing faintly with the mark of a dragon",
    "A legendary diadem forged of shadowglass during the age of Cú Chulainn",
    "A legendary eldwood ring believed to be blessed by Bres the Fair",
    "A legendary etherglass idol believed to be blessed by Eithne of the Shining Veil",
    "A legendary etherglass key believed to be blessed by Dagda the Great",
    "A legendary hourglass tied by fate to the will of Danu the Mother",
    "A legendary idol forged of eldwood during the age of Bres the Fair",
    "A legendary orb forged of phoenix-feather during the age of Arawn of Annwn",
    "A legendary ring tied by fate to the will of Cairn of the Broken Crown",
    "A legendary soul-iron mask once offered to Danu the Mother as tribute",
    "A legendary sun-gold orb once offered to Danu the Mother as tribute",
    "A legendary tablet forged of dragonscale during the age of Cairn of the Broken Crown",
    "A mask of blood-amber, glowing faintly with the mark of a crescent moon",
    "A mask of demon-bronze, glowing faintly with the mark of a storm",
    "A meteoric iron rod inscribed with the prayer of Cú Chulainn",
    "A meteoric iron spear engraved with the likeness of a eye",
    "A meteoric iron tablet engraved with the likeness of a serpent",
    "A mirror forged of blood-amber, used to crown Cú Chulainn",
    "A mirror forged of stormsilver, used to crown Balor of the Evil Eye",
    "A mirror of blood-amber origin, radiating the aura of Bres the Fair",
    "A mirror of dragonscale origin, bearing the seal of a tree of life",
    "A mirror of shadowglass origin, bearing the seal of a crown",
    "A moonstone orb engraved with the likeness of a tree of life",
    "A moonstone ring inscribed with the prayer of Lugh of the Long Arm",
    "A mythic blade forged of moonstone during the age of Cú Chulainn",
    "A mythic grimoire tied by fate to the will of Balor of the Evil Eye",
    "A mythic idol that glows when a key is near",
    "A mythic obsidian banner believed to be blessed by Neit the War-God",
    "A mythic phoenix-feather hourglass believed to be blessed by The Morrígan",
    "A mythic ring forged of sun-gold during the age of Maeve the Witch Queen",
    "A mythic soul-iron diadem believed to be blessed by Fionn mac Cumhaill",
    "A mythic torch that glows when a sunburst is near",
    "A mythic wyrm-bone tablet believed to be blessed by Nuada of the Silver Hand",
    "A pendant forged from soul-iron in the age of Bodb Derg",
    "A pendant forged from wyrdsteel in the age of The Morrígan",
    "A pendant forged of dragonscale, used to crown Dagda the Great",
    "A pendant of moonstone origin, radiating the aura of Bran the Blessed",
    "A pendant of starsteel origin, bearing the seal of a hand",
    "A phoenix-feather blade engraved with the likeness of a stag",
    "A phoenix-feather diadem once wielded by Dagda the Great in a forgotten war",
    "A phoenix-feather orb once wielded by Taranis the Thunderer in a forgotten war",
    "A phoenix-feather talisman once wielded by Lugh of the Long Arm in a forgotten war",
    "A primordial diadem forged of spiritwood during the age of Taranis the Thunderer",
    "A primordial orb forged of blood-amber during the age of Arawn of Annwn",
    "A primordial pendant forged of shadowglass during the age of Bres the Fair",
    "A primordial pendant tied by fate to the will of Bres the Fair",
    "A primordial phoenix-feather torch once offered to Nuada of the Silver Hand as tribute",
    "A primordial rod that glows when a spiral is near",
    "A radiant amulet crafted by Bres the Fair to channel divine power",
    "A radiant banner crafted by Goibniu the Smith to channel divine power",
    "A radiant idol born from the dreams of Lugh of the Long Arm",
    "A radiant tablet said to whisper with the voice of Nuada of the Silver Hand",
    "A radiant wyrdstone seal said to be tempered by song",
    "A relic of obsidian, glowing faintly with the mark of a eye",
    "A relic of phoenix-feather origin, radiating the aura of Arawn of Annwn",
    "A relic of starsteel, glowing faintly with the mark of a key",
    "A relic-bound amulet tied by fate to the will of Danu the Mother",
    "A relic-bound blood-amber torch believed to be blessed by Eira the Eternal",
    "A relic-bound hourglass that glows when a hand is near",
    "A relic-bound moonstone spear once offered to Maeve the Witch Queen as tribute",
    "A relic-bound orb tied by fate to the will of Manannán mac Lir",
    "A relic-bound rune that glows when a sword is near",
    "A relic-bound sky-crystal scepter believed to be blessed by Arawn of Annwn",
    "A relic-bound spiritwood talisman believed to be blessed by Manannán mac Lir",
    "A relic-bound talisman forged of soul-iron during the age of Nuada of the Silver Hand",
    "A relic-bound wyrdstone diadem believed to be blessed by Arawn of Annwn",
    "A resplendent demon-bronze key said to be tempered by song",
    "A resplendent relic said to whisper with the voice of Bran the Blessed",
    "A resplendent ring said to hold the essence of Dagda the Great",
    "A resplendent rod said to hold the essence of Arawn of Annwn",
    "A resplendent talisman forged to bind the power of a stag",
    "A restored chalice said to hold the essence of Nuada of the Silver Hand",
    "A restored crown forged to bind the power of a phoenix",
    "A restored grimoire born from the dreams of Goibniu the Smith",
    "A restored hourglass born from the dreams of Eithne of the Shining Veil",
    "A restored hourglass born from the dreams of Manannán mac Lir",
    "A restored hourglass that hums softly with the will of Taranis the Thunderer",
    "A restored orb that hums softly with the will of Balor of the Evil Eye",
    "A restored pendant that hums softly with the will of Bres the Fair",
    "A restored rod said to whisper with the voice of Goibniu the Smith",
    "A restored rod said to whisper with the voice of Lugh of the Long Arm",
    "A restored rune crafted by Neit the War-God to channel divine power",
    "A restored rune that hums softly with the will of Neit the War-God",
    "A restored tablet crafted by Goibniu the Smith to channel divine power",
    "A restored talisman that hums softly with the will of Balor of the Evil Eye",
    "A ring forged from dragonscale in the age of Lugh of the Long Arm",
    "A ring forged of etherglass, used to crown Lugh of the Long Arm",
    "A ring forged of phoenix-feather, used to crown Bran the Blessed",
    "A ring of meteoric iron, glowing faintly with the mark of a mirror",
    "A ring of phoenix-feather origin, bearing the seal of a raven",
    "A ring of sun-gold origin, radiating the aura of Maeve the Witch Queen",
    "A ring of sun-gold, glowing faintly with the mark of a eye",
    "A ring of wyrm-bone origin, bearing the seal of a flame",
    "A rod forged from meteoric iron in the age of Manannán mac Lir",
    "A rod forged from wyrm-bone in the age of Balor of the Evil Eye",
    "A rod forged of moonstone, used to crown Cairn of the Broken Crown",
    "A rod forged of wyrm-bone, used to crown Bodb Derg",
    "A rod of obsidian origin, radiating the aura of The Morrígan",
    "A rod of wyrdsteel, glowing faintly with the mark of a spiral",
    "A rune forged from meteoric iron in the age of Bres the Fair",
    "A rune forged from phoenix-feather in the age of The Morrígan",
    "A rune forged of wyrdstone, used to crown Lugh of the Long Arm",
    "A rune of demon-bronze, glowing faintly with the mark of a raven",
    "A rune of demon-bronze, glowing faintly with the mark of a sword",
    "A rune of etherglass origin, bearing the seal of a storm",
    "A rune of wyrm-bone, glowing faintly with the mark of a dragon",
    "A sacred amulet forged to bind the power of a spiral",
    "A sacred etherglass torch said to be tempered by song",
    "A sacred heartstone forged to bind the power of a tree of life",
    "A sacred mirror forged to bind the power of a hand",
    "A sacred pendant that hums softly with the will of Taranis the Thunderer",
    "A sacred rod said to whisper with the voice of The Morrígan",
    "A sacred spear that hums softly with the will of Arawn of Annwn",
    "A sanctified chalice forged of dragonscale during the age of Maeve the Witch Queen",
    "A sanctified chalice forged of etherglass during the age of Neit the War-God",
    "A sanctified chalice tied by fate to the will of Arawn of Annwn",
    "A sanctified relic tied by fate to the will of Bran the Blessed",
    "A sanctified rod tied by fate to the will of Eira the Eternal",
    "A scepter forged from moonstone in the age of Bodb Derg",
    "A scepter forged from wyrdstone in the age of Arawn of Annwn",
    "A scepter forged of sun-gold, used to crown Manannán mac Lir",
    "A scepter forged of wyrm-bone, used to crown Bodb Derg",
    "A scepter of dragonscale origin, bearing the seal of a serpent",
    "A scepter of etherglass origin, radiating the aura of Goibniu the Smith",
    "A seal forged from sky-crystal in the age of Eira the Eternal",
    "A seal forged of blood-amber, used to crown The Morrígan",
    "A seal forged of phoenix-feather, used to crown Manannán mac Lir",
    "A seal forged of phoenix-feather, used to crown Nuada of the Silver Hand",
    "A seal of shadowglass origin, bearing the seal of a sunburst",
    "A seal of shadowglass origin, radiating the aura of Goibniu the Smith",
    "A seal of sky-crystal origin, radiating the aura of Manannán mac Lir",
    "A shadowed crown said to hold the essence of Taranis the Thunderer",
    "A shadowed hourglass that hums softly with the will of Eithne of the Shining Veil",
    "A shadowed key forged to bind the power of a raven",
    "A shadowed mask said to hold the essence of Dagda the Great",
    "A shadowed mask that hums softly with the will of Danu the Mother",
    "A shadowed mirror born from the dreams of Maeve the Witch Queen",
    "A shadowed orb born from the dreams of Bran the Blessed",
    "A shadowed pendant born from the dreams of Dagda the Great",
    "A shadowed ring born from the dreams of Taranis the Thunderer",
    "A shadowed rune crafted by Arawn of Annwn to channel divine power",
    "A shadowed seal said to hold the essence of Manannán mac Lir",
    "A shadowed spiritwood diadem said to be tempered by song",
    "A shadowglass crown inscribed with the prayer of Taranis the Thunderer",
    "A shadowglass orb engraved with the likeness of a stag",
    "A shining blade tied by fate to the will of Cú Chulainn",
    "A shining diadem forged of spiritwood during the age of Danu the Mother",
    "A shining dragonscale chalice once offered to The Morrígan as tribute",
    "A singing amulet said to hold the essence of Balor of the Evil Eye",
    "A singing chalice that hums softly with the will of Balor of the Evil Eye",
    "A singing crown that hums softly with the will of Manannán mac Lir",
    "A singing heartstone said to whisper with the voice of Manannán mac Lir",
    "A singing mirror said to hold the essence of Fionn mac Cumhaill",
    "A singing relic said to hold the essence of Manannán mac Lir",
    "A singing rod forged to bind the power of a serpent",
    "A singing rune born from the dreams of Taranis the Thunderer",
    "A singing rune forged to bind the power of a dragon",
    "A singing rune forged to bind the power of a stag",
    "A singing shadowglass orb said to be tempered by song",
    "A singing torch born from the dreams of Eira the Eternal",
    "A singing torch said to hold the essence of Manannán mac Lir",
    "A sky-crystal grimoire inscribed with the prayer of Lugh of the Long Arm",
    "A sky-crystal mask inscribed with the prayer of Fionn mac Cumhaill",
    "A soul-iron crown once wielded by Eira the Eternal in a forgotten war",
    "A soul-iron relic inscribed with the prayer of Fionn mac Cumhaill",
    "A soul-iron scepter inscribed with the prayer of Cairn of the Broken Crown",
    "A soul-iron spear engraved with the likeness of a dragon",
    "A spear forged from sun-gold in the age of Fionn mac Cumhaill",
    "A spear forged from wyrdsteel in the age of Arawn of Annwn",
    "A spear forged of dragonscale, used to crown Goibniu the Smith",
    "A spear of dragonscale, glowing faintly with the mark of a sword",
    "A spear of moonstone origin, radiating the aura of Bres the Fair",
    "A spear of moonstone origin, radiating the aura of Maeve the Witch Queen",
    "A spear of obsidian, glowing faintly with the mark of a hand",
    "A spiritwood rod inscribed with the prayer of Nuada of the Silver Hand",
    "A starsteel mask once wielded by Arawn of Annwn in a forgotten war",
    "A starsteel orb once wielded by Balor of the Evil Eye in a forgotten war",
    "A starsteel seal once wielded by Eithne of the Shining Veil in a forgotten war",
    "A starsteel tablet engraved with the likeness of a wolf",
    "A stormsilver banner once wielded by Manannán mac Lir in a forgotten war",
    "A stormsilver crown once wielded by Neit the War-God in a forgotten war",
    "A stormsilver scepter engraved with the likeness of a wolf",
    "A sun-gold mirror engraved with the likeness of a phoenix",
    "A tablet forged from eldwood in the age of Taranis the Thunderer",
    "A tablet forged from stormsilver in the age of Fionn mac Cumhaill",
    "A tablet forged of stormsilver, used to crown Manannán mac Lir",
    "A tablet forged of sun-gold, used to crown Danu the Mother",
    "A tablet of spiritwood origin, bearing the seal of a mirror",
    "A tablet of spiritwood origin, bearing the seal of a rose",
    "A tablet of stormsilver, glowing faintly with the mark of a eye",
    "A tablet of wyrdsteel origin, radiating the aura of Bodb Derg",
    "A talisman forged from moonstone in the age of Goibniu the Smith",
    "A talisman forged of spiritwood, used to crown Cú Chulainn",
    "A talisman of blood-amber, glowing faintly with the mark of a crown",
    "A talisman of eldwood origin, radiating the aura of Nuada of the Silver Hand",
    "A talisman of starsteel, glowing faintly with the mark of a key",
    "A talisman of wyrdsteel origin, radiating the aura of Eira the Eternal",
    "A talisman of wyrdstone, glowing faintly with the mark of a serpent",
    "A talisman of wyrdstone, glowing faintly with the mark of a stag",
    "A talisman of wyrm-bone origin, radiating the aura of Taranis the Thunderer",
    "A timeworn blood-amber talisman believed to be blessed by Lugh of the Long Arm",
    "A timeworn grimoire that glows when a phoenix is near",
    "A timeworn moonstone spear once offered to Fionn mac Cumhaill as tribute",
    "A timeworn obsidian orb believed to be blessed by Bran the Blessed",
    "A timeworn rune forged of dragonscale during the age of Eira the Eternal",
    "A timeworn torch that glows when a spiral is near",
    "A timeworn wyrdstone key once offered to Bran the Blessed as tribute",
    "A torch forged of stormsilver, used to crown Lugh of the Long Arm",
    "A torch of dragonscale origin, radiating the aura of Maeve the Witch Queen",
    "A torch of spiritwood, glowing faintly with the mark of a stag",
    "A torch of starsteel origin, radiating the aura of Bres the Fair",
    "A torch of stormsilver origin, radiating the aura of Nuada of the Silver Hand",
    "A transcendent amulet that hums softly with the will of Eira the Eternal",
    "A transcendent heartstone forged to bind the power of a rose",
    "A transcendent hourglass that hums softly with the will of The Morrígan",
    "A transcendent mask born from the dreams of Lugh of the Long Arm",
    "A transcendent moonstone crown said to be tempered by song",
    "A transcendent relic that hums softly with the will of Fionn mac Cumhaill",
    "A transcendent rune crafted by Eithne of the Shining Veil to channel divine power",
    "A transcendent sky-crystal hourglass said to be tempered by song",
    "A transcendent talisman forged to bind the power of a dragon",
    "A veiled banner said to whisper with the voice of The Morrígan",
    "A veiled chalice said to whisper with the voice of Maeve the Witch Queen",
    "A veiled hourglass that hums softly with the will of Goibniu the Smith",
    "A veiled key crafted by Nuada of the Silver Hand to channel divine power",
    "A veiled mask born from the dreams of Arawn of Annwn",
    "A veiled mask said to hold the essence of Eithne of the Shining Veil",
    "A veiled moonstone torch said to be tempered by song",
    "A veiled pendant forged to bind the power of a storm",
    "A veiled torch crafted by Cú Chulainn to channel divine power",
    "A venerable amulet born from the dreams of Dagda the Great",
    "A venerable mask born from the dreams of Fionn mac Cumhaill",
    "A venerable obsidian heartstone said to be tempered by song",
    "A venerable pendant born from the dreams of Danu the Mother",
    "A venerable talisman that hums softly with the will of Cairn of the Broken Crown",
    "A wyrdsteel banner once wielded by Fionn mac Cumhaill in a forgotten war",
    "A wyrdsteel key once wielded by Dagda the Great in a forgotten war",
    "A wyrdsteel orb engraved with the likeness of a stag",
    "A wyrdsteel scepter engraved with the likeness of a crescent moon",
    "A wyrdsteel tablet inscribed with the prayer of Neit the War-God",
    "A wyrdstone banner engraved with the likeness of a raven",
    "A wyrdstone rod inscribed with the prayer of Taranis the Thunderer",
    "A wyrdstone torch once wielded by Lugh of the Long Arm in a forgotten war",
    "A wyrm-bone blade once wielded by Taranis the Thunderer in a forgotten war",
    "A wyrm-bone crown once wielded by Balor of the Evil Eye in a forgotten war",
    "A wyrm-bone seal engraved with the likeness of a mirror",
    "An accursed phoenix-feather key believed to be blessed by Taranis the Thunderer",
    "An amulet forged from demon-bronze in the age of Goibniu the Smith",
    "An amulet forged from etherglass in the age of Nuada of the Silver Hand",
    "An amulet forged from meteoric iron in the age of Arawn of Annwn",
    "An amulet forged of demon-bronze, used to crown Bodb Derg",
    "An amulet forged of meteoric iron, used to crown Goibniu the Smith",
    "An amulet of soul-iron origin, bearing the seal of a spiral",
    "An amulet of wyrdstone origin, radiating the aura of Maeve the Witch Queen",
    "An ancient amulet said to whisper with the voice of Manannán mac Lir",
    "An ancient blade said to whisper with the voice of Taranis the Thunderer",
    "An ancient chalice said to hold the essence of Dagda the Great",
    "An ancient key crafted by Balor of the Evil Eye to channel divine power",
    "An ancient orb born from the dreams of Eira the Eternal",
    "An ancient ring said to whisper with the voice of Balor of the Evil Eye",
    "An ancient scepter crafted by Manannán mac Lir to channel divine power",
    "An ancient tablet forged to bind the power of a hand",
    "An eldwood chalice inscribed with the prayer of Bres the Fair",
    "An eldwood mirror engraved with the likeness of a mirror",
    "An eldwood mirror engraved with the likeness of a serpent",
    "An eldwood orb engraved with the likeness of a tree of life",
    "An eldwood orb once wielded by Arawn of Annwn in a forgotten war",
    "An eldwood tablet inscribed with the prayer of Bodb Derg",
    "An eternal amulet tied by fate to the will of Taranis the Thunderer",
    "An eternal banner tied by fate to the will of Dagda the Great",
    "An eternal diadem forged of phoenix-feather during the age of Lugh of the Long Arm",
    "An eternal hourglass forged to bind the power of a dragon",
    "An eternal rod tied by fate to the will of Bodb Derg",
    "An eternal rune that hums softly with the will of Eithne of the Shining Veil",
    "An eternal scepter forged to bind the power of a dragon",
    "An eternal stormsilver rune once offered to Goibniu the Smith as tribute",
    "An eternal tablet that glows when a eye is near",
    "An eternal wyrm-bone rod once offered to Nuada of the Silver Hand as tribute",
    "An etherglass hourglass inscribed with the prayer of Bres the Fair",
    "An etherglass mask inscribed with the prayer of Arawn of Annwn",
    "An etherglass seal engraved with the likeness of a key",
    "An idol forged of phoenix-feather, used to crown Arawn of Annwn",
    "An idol of blood-amber origin, radiating the aura of Balor of the Evil Eye",
    "An idol of etherglass, glowing faintly with the mark of a crown",
    "An idol of sky-crystal, glowing faintly with the mark of a mirror",
    "An immortal blood-amber talisman believed to be blessed by Danu the Mother",
    "An immortal demon-bronze idol believed to be blessed by Fionn mac Cumhaill",
    "An immortal relic forged of stormsilver during the age of Eithne of the Shining Veil",
    "An immortal torch tied by fate to the will of Arawn of Annwn",
    "An obsidian mirror inscribed with the prayer of Eithne of the Shining Veil",
    "An obsidian orb once wielded by Balor of the Evil Eye in a forgotten war",
    "An obsidian rune engraved with the likeness of a storm",
    "An orb forged from eldwood in the age of Lugh of the Long Arm",
    "An orb forged from obsidian in the age of Arawn of Annwn",
    "An orb forged from shadowglass in the age of Maeve the Witch Queen",
    "An orb forged of stormsilver, used to crown Fionn mac Cumhaill",
    "An orb of shadowglass origin, radiating the aura of Dagda the Great",
    "An orb of wyrdsteel origin, radiating the aura of Bodb Derg",
    "An unbound banner forged of wyrdstone during the age of Eithne of the Shining Veil",
    "An unbound blood-amber chalice once offered to Maeve the Witch Queen as tribute",
    "An unbound moonstone chalice once offered to Dagda the Great as tribute",
    "An unbound moonstone key believed to be blessed by Maeve the Witch Queen",
    "An unbound ring tied by fate to the will of Goibniu the Smith",
    "An unbound tablet tied by fate to the will of Maeve the Witch Queen",
    "An unbound wyrdstone heartstone once offered to Balor of the Evil Eye as tribute",
    "An unholy amulet that glows when a wolf is near",
    "An unholy banner that glows when a eye is near",
    "An unholy banner that glows when a thorn is near",
    "An unholy blade that glows when a hand is near",
    "An unholy mask forged of sun-gold during the age of Arawn of Annwn",
    "An unholy mask tied by fate to the will of Eithne of the Shining Veil",
    "An unholy relic that glows when a mirror is near",
    "An unholy scepter forged of phoenix-feather during the age of Dagda the Great",
    "An unholy stormsilver banner believed to be blessed by The Morrígan",
    "An unholy tablet tied by fate to the will of Manannán mac Lir",
    "An unholy talisman tied by fate to the will of Lugh of the Long Arm"
]

