"""
City-level worldbuilding data.
"""

# ---- CITY LEVEL ----
city_tones = [
    "ruled by a council older than its own walls",
    "where silver tongues cut deeper than swords",
    "haunted by the echo of forgotten kings",
    "kept alive by trade, treachery, and tired saints",
    "crowned by towers that pierce clouds and ambition alike",
    "bathed in candlelight and conspiracy",
    "built on catacombs that hum with unfinished prayers",
    "wrapped in banners of devotion and deceit",
    "watched by stone angels whose eyes never close",
    "known for libraries filled with forbidden treatises",
    "where faith competes with fortune in every marketplace",
    "a city of laughter that curdles after dark",
    "raised from ruin and forever falling back into it",
    "whose festivals smell of wine, wax, and fear",
    "where justice is measured in volume, not virtue",
    "whose nobles polish lies until they shine like mirrors",
    "balanced precariously between salvation and spectacle",
    "where even the shadows kneel to power",
    "whose streets hum like strings drawn too tight",
    "famed for its beauty, feared for its memory",
    "where peace lasts only as long as the bells ring",
    "where rumor is the only true currency",
    "a labyrinth of saints, thieves, and playwrights",
    "lit by faith, fed by folly",
    "whose dreams of empire still haunt its sleep",
    "where scholars and spies share the same desks",
    "built from ambition, fueled by guilt",
    "where coins bear the faces of both heroes and traitors",
    "that prides itself on never learning from the past",
    "where hope is rationed like clean water",
    "whose walls whisper the names of every broken vow",
    "that calls itself eternal but trembles each winter",
    "where the poor pray for mercy and the rich pray for mercy's end",
    "a citadel of contradictions and confessions",
    "where every promise has a witness and a loophole",
    "whose clocktower runs fast whenever war is near",
    "whose archives smell of dust, ink, and fear",
    "where relics outnumber truths tenfold",
    "whose silence at midnight is always rehearsed",
    "that believes itself the heart of the world, though the pulse is fading"
]

city_tones.extend([
    "a proud citadel where every tower casts a political shadow.",
    "a city of scholars who debate ethics while merchants price the air.",
    "a river-wrapped metropolis that trades faith for progress and back again.",
    "a hill-throned capital built on the bones of its own ambition.",
    "a radiant city whose streets gleam brighter than its conscience.",
    "a holy metropolis where saints and spies share the same confessional.",
    "a city of gilded promises and uncollected debts.",
    "a fortress-turned-market where the sword and the scale weigh the same.",
    "a capital of mirrors, obsessed with its reflection in history.",
    "a city born from rebellion and maintained by bureaucracy.",
    "a marble labyrinth where even sunlight must pay admission.",
    "a harbor metropolis whose ships bring both trade and temptation.",
    "a desert citadel that sells water, wisdom, and mercy separately.",
    "a silver-roofed seat of art that hides its ugliness in galleries.",
    "a mountain capital that mistakes echo for applause.",
    "a temple-city where the gods are mostly investors now.",
    "a city-state ruled by poets who legislate in riddles.",
    "a coastal hub where politics flow in tides and treachery.",
    "a walled empire-city that trusts no wind it can't tax.",
    "a sprawling marble spire that worships perfection and punishes failure.",
    "a twin-tiered capital divided between dreamers and accountants.",
    "a fortress city that never surrendered and never quite won.",
    "a court of masks where truth is a seasonal fashion.",
    "a city of seven bridges, each with its own religion.",
    "a citadel of wisdom that forgets compassion every winter.",
    "a sprawling city of artisans that manufactures nostalgia.",
    "a marble crown worn by ambition and cracked by pride.",
    "a sea-washed city built of coral and compromise.",
    "a highland capital whose towers vanish into cloud and rumor.",
    "a desert oasis turned metropolis of illusion and light.",
    "a holy court where miracles require permits.",
    "a great capital whose markets sound like hymns off-key.",
    "a cliff-side city carved from defiance and debt.",
    "a city whose laws were written by the wind and enforced by time.",
    "a metropolis whose prosperity depends on carefully maintained ignorance.",
    "a gleaming capital that considers mercy a dangerous precedent.",
    "a city ruled by mathematicians who've lost count of their own sins.",
    "a court of marble hearts and iron tongues.",
    "a dream-born city that ages a year every full moon.",
    "a city-state that declares neutrality and practices extortion.",
    "a jewel of the realm that shines brightest during famine.",
    "a marble sprawl whose beauty distracts from its rot.",
    "a city whose rulers built towers to avoid hearing the streets.",
    "a holy metropolis where relics outnumber the faithful.",
    "a river-metropolis that believes cleanliness is next to divinity and wealth.",
    "a desert city where every shadow is for sale.",
    "a city of peace treaties framed and forgotten.",
    "a mist-ringed capital that wakes new every decade under a different name.",
    "a golden city whose gates open only for parades and invaders.",
    "a port capital where the horizon is treated like competition.",
    "a snow-throned metropolis that measures purity in frostbite.",
    "a city of philosophers who charge entrance to their debates.",
    "a forge-city that outgrew purpose and started making history instead.",
    "a capital of echoes where memory itself is currency.",
    "a city built around a clock that runs backward and perfectly.",
    "a republic of ambition that swears it remembers being kind.",
    "a city-state ruled by silence louder than its armies.",
    "a steelhearted metropolis that believes progress forgives everything.",
    "a glass-paved city that reflects too much to see clearly.",
    "a holy metropolis that built walls to keep heaven out.",
    "a merchant capital where every law is an advertisement.",
    "a citadel of banners whose colors change with the season of deceit.",
    "a shining city that feeds on praise and starves on truth.",
    "a riverborn capital where bridges gossip louder than priests.",
    "a twin-walled metropolis whose inner circle has forgotten the outer.",
    "a city of towers leaning toward ambition and away from grace.",
    "a pearl of civilization whose shell hides its rot.",
    "a clockwork capital obsessed with punctual prophecy.",
    "a mountain citadel where hope must climb stairs.",
    "a university-city where heresy is elective.",
    "a metropolis of saints with scandalous footnotes.",
    "a mist-veiled capital that vanishes from maps when ashamed.",
    "a coastal jewel whose reflection is truer than its reality.",
    "a marble dome of arguments dressed as prayers.",
    "a fortress-city where law and love are mutually exclusive.",
    "a harbor metropolis that calls storms 'foreign diplomacy.'",
    "a frost-lit city whose rulers believe in destiny, not design.",
    "a sandstone spire-city that glows red at dusk like a confession.",
    "a vast capital that keeps history in ledgers instead of libraries.",
    "a river fortress that forgot it was meant to protect, not collect.",
    "a mountain-seat where the air is too thin for humility.",
    "a silver-paved capital that mistakes reflection for introspection.",
    "a spire metropolis built by artisans who worship precision.",
    "a city built on salt—its wealth, its wounds, its tears.",
    "a holy city where the gods are silent but the bureaucracy sings.",
    "a capital of endless debate and carefully rationed truth.",
    "a city of fountains that drown rather than quench.",
    "a fortress of faith whose walls keep both heresy and compassion out.",
    "a city whose ruling council meets only during eclipses.",
    "a marble labyrinth whose citizens mistake tradition for freedom.",
    "a shining metropolis built entirely from rivalries.",
    "a sprawl of banners that changes color every coronation.",
    "a fog-shrouded capital rumored to rule three nations unknowingly.",
    "a clock-towered metropolis that believes progress forgives cruelty.",
    "a cliff-city that mistakes vertigo for perspective.",
    "a holy capital that sells redemption in bulk.",
    "a mountain fortress that trades altitude for arrogance.",
    "a great city that celebrates tomorrow because today is unbearable."
])

city_flavors = [
    "Its rulers speak of justice but define it by convenience.",
    "Merchants and monks share the same patrons.",
    "Each bell toll marks a bargain fulfilled or betrayed.",
    "Children learn lies before prayers.",
    "The scent of incense hides the stench of fear.",
    "Its walls are carved with stories no one dares read aloud.",
    "Rats here are rumor brokers with impeccable sources.",
    "Hope is rationed, despair distributed freely.",
    "Every street has its own god, none answer prayers.",
    "The city council's motto translates roughly to 'Delay and Profit.'",
    "Its libraries burn periodically—by tradition.",
    "Every sermon doubles as a sales pitch.",
    "Saints here are canonized by popular vote.",
    "When the wind changes, so do alliances.",
    "Laughter echoes loudest near the gallows.",
    "The city's anthem changes each decade, lyrics optional.",
    "Its peace is purchased in installments.",
    "Every secret has a custodian, usually underpaid.",
    "Nobles collect relics the way beggars collect blessings.",
    "Faith is fashionable but rarely practiced after dusk.",
    "No coin leaves a hand unblessed or uncounted.",
    "Even its pigeons are rumored to be spies.",
    "Mercy is taxed; cruelty subsidized.",
    "The moon refuses to rise over its poorest quarter.",
    "The city never sleeps—only negotiates with exhaustion.",
    "Every bridge hides a deal; every statue, a scandal.",
    "The priests pray louder during elections.",
    "Rain smells faintly of perfume and regret.",
    "Hope survives disguised as stubbornness.",
    "Coins here whisper when they change hands.",
    "Its greatest virtue is forgetting.",
    "Every heir inherits three debts and one ghost.",
    "Old walls remember newer sins.",
    "The marketplace echoes with hymns to greed.",
    "Each noble family keeps one truth locked in a chest.",
    "Even beggars file petitions.",
    "Prophets charge admission.",
    "The fountains run red on holy days—tradition, they say.",
    "Its anthem is sung in three languages, none sincere.",
    "The sunsets here look guilty."
]

city_flavors.extend([
    "Smells of spiced wine, old parchment, and ambition gone to seed.",
    "Famous for its markets that never close and its promises that never open.",
    "Known for its bells — each tolling a different lie.",
    "Every street bears a saint's name and a sinner's story.",
    "Merchants sell relics by day and rumors by candlelight.",
    "Citizens speak softly, as if afraid of waking the statues.",
    "Festival banners hang year-round because no one remembers when the last one ended.",
    "Its fountains run with both water and political metaphors.",
    "Every tavern wall is etched with poetry and unpaid debts.",
    "Street performers reenact revolutions that never happened.",
    "Lanterns are painted with blessings to ward off nostalgia.",
    "The smell of incense can't hide the stench of conspiracy.",
    "Pigeons here carry both messages and small acts of treason.",
    "The city's best bakers are also its best poisoners.",
    "A thousand stairways lead upward, but none lead out.",
    "Coins here are heavier with history than with gold.",
    "The city's anthem changes key with every new ruler.",
    "Every mural hides a name that was better forgotten.",
    "The local proverb: 'All debts are sacred, even emotional ones.'",
    "Each dawn, the priests bless the market weights before trade begins.",
    "Street lamps burn brighter near corruption and dimmer near love.",
    "The air hums faintly — not from magic, but mutual suspicion.",
    "Dogs are trained to bark only at truth.",
    "A marble plaza engraved with the word 'someday.'",
    "Street sweepers collect both dust and secrets.",
    "Even the sewers are rumored to have political opinions.",
    "A curfew horn that sounds different depending on who's guilty.",
    "Every neighborhood swears it's the true heart of the city.",
    "A skyline of towers competing to see which one regrets less.",
    "Rainwater tastes faintly of wine and bureaucracy.",
    "Markets trade not only goods but memories — fresh or used.",
    "Citizens boast of their ancestors and apologize for their descendants.",
    "The moon is said to avoid shining directly on its palace.",
    "A local law requires public optimism every spring.",
    "City gates engraved with a poem no one dares to finish.",
    "Its pigeons wear colored ribbons denoting allegiance.",
    "The bakeries open before dawn to avoid politics.",
    "A clock tower that chimes in irregular rhythms — intentionally.",
    "Public fountains decorated with coins stamped from rebellion.",
    "A guild of candle-makers who only work by moonlight.",
    "Every rooftop garden grows the same flower: amnesia bloom.",
    "A black obelisk in the center that no one admits to touching.",
    "Fishmongers shout prayers instead of prices.",
    "Every bridge has its own superstition, and none are comforting.",
    "Citizens claim the city's founder will return — once everyone forgets him.",
    "The sound of laughter is taxed by the hour.",
    "Every autumn, the pigeons vote for a new mayor.",
    "Artisans craft masks more honest than faces.",
    "Rumor says the city's cat population secretly runs the courts.",
    "Beggars paint on the cobblestones, and nobles walk carefully to preserve the art.",
    "All clocks are slightly wrong, by law.",
    "Citizens swear oaths on broken mirrors for luck.",
    "The main square's cobblestones are rumored to rearrange overnight.",
    "Street vendors sell bottled sunsets imported from nowhere.",
    "The city mint produces more propaganda than coin.",
    "An old law requires at least one secret per household.",
    "The market bells ring thirteen times for mercy and none for truth.",
    "Every wall bears traces of past graffiti, never fully washed away.",
    "The night patrols wear perfume to confuse hunting spirits.",
    "A guild of thieves issues receipts for every crime.",
    "Musicians duel publicly — the loser must teach the winner's apprentice.",
    "Taverns name drinks after scandals that haven't yet happened.",
    "Puppeteers perform tragedies that foretell elections.",
    "All wine sold in the palace is blessed by economists.",
    "At dusk, the statues whisper until the lamplighters drown them out.",
    "A rumor insists the city dreams itself each night into being.",
    "Every alley has a name and a small grudge.",
    "The oldest bridge is said to remember every betrayal.",
    "A clock tower built by lovers who never met on time.",
    "Fountains run red during coronations — by tradition.",
    "Every noble family has a sworn enemy in the bakery trade.",
    "The library burns its own books to prove restraint.",
    "Pigeons deliver apologies written in verse.",
    "Street minstrels play only in minor keys for political reasons.",
    "A custom requires citizens to bow to mirrors at dawn.",
    "Public trials are performed as operas for efficiency.",
    "Coins jingle differently depending on their owner's conscience.",
    "Every innkeeper keeps a ledger of the city's collective sins.",
    "The royal gardens are watered with regret — metaphorically and otherwise.",
    "Street sweepers are forbidden to speak while sweeping, lest they gossip with ghosts.",
    "A law requires jesters to attend all council meetings.",
    "Candlelight dances in patterns that spell dissent.",
    "Every spring, the city's pigeons migrate and the mood improves.",
    "Each morning, bells toll the number of unkept promises.",
    "A public fountain named 'The Second Chance' — always dry.",
    "Citizens compete annually to see who can forget the past most elegantly.",
    "The baker's guild controls both bread and policy.",
    "Every map of the city is slightly different — and all are correct.",
    "Tax collectors wear masks of smiling saints.",
    "The city's anthem changes tempo with each era's anxiety.",
    "Lanterns in the noble quarter burn with imported moonlight.",
    "Rumor has it the city's founder still walks at night, correcting grammar.",
    "Street scribes copy secrets faster than news.",
    "A thousand bells ring daily, and not one means salvation.",
    "Every monument commemorates the wrong person on purpose.",
    "Courtiers greet one another with 'May your scandals age well.'",
    "All wine is stored underground, because sunlight embarrasses it.",
    "The grand bazaar spans seven districts and three realities.",
    "Visitors say it smells like cinnamon, iron, and paperwork.",
    "Every house has at least one ghost tenant — legally speaking.",
    "The city cathedral echoes slightly ahead of the choir.",
    "Each festival ends in applause and quiet regret.",
    "Children play at trial, and one always plays the accused.",
    "The palace clock runs slow to prove dominance over time."
])

city_titles = [
    "High Lord", "High Lady", "First Magistrate", "Archon", "High Reeve",
    "Lord Protector", "Lady Protector", "Chancellor", "Hierophant",
    "Duke", "Duchess", "Margrave", "Consul", "Arbiter", "Prelate",
    "High Chancellor", "Voice of the Council", "Lord Regent",
    "Warden Supreme", "High Envoy", "Grand Scribe", "Silver Regent",
    "Night Marshal", "Star-Court Elder", "Blood Chancellor",
    "Keeper of Oaths", "High Exarch", "Mistress of the Seal",
    "Lord of Ashes", "High Vicar", "Speaker of Stones"
]

city_leader_names = [
    "Aedon", "Aerfael", "Aeronwyn", "Ailric", "Aisled", "Alaric",
    "Alwenna", "Ambren", "Anarion", "Ansel", "Ardric", "Argen",
    "Aricel", "Arion", "Arthgal", "Arwynne", "Baelorin", "Balinor",
    "Baraithen", "Belenos", "Brenic", "Brendan", "Brennor", "Briannon",
    "Brigwen", "Brynach", "Cadarn", "Cadeyr", "Cadfaeron", "Cadric",
    "Caelanor", "Caeric", "Caerwynne", "Callenor", "Calwen", "Caradryn",
    "Carwenna", "Cathalor", "Cavanen", "Cearwyn", "Cedren", "Cerwyn",
    "Ciarwen", "Cillan", "Clarenor", "Colfael", "Conaric", "Conchobar",
    "Corfaen", "Corren", "Creon", "Culric", "Cynfaeron", "Cynricen",
    "Darion", "Darran", "Declaen", "Deiric", "Delanor", "Denfael",
    "Derian", "Derwyn", "Diarwyn", "Donnor", "Doranic", "Dragan",
    "Drystanor", "Dwynen", "Eadric", "Eirfael", "Eiraen", "Eithron",
    "Elanor", "Eledric", "Elenwyn", "Elgar", "Elricen", "Eochaen",
    "Eoghen", "Eonanor", "Erfaen", "Eryl", "Eryndor", "Esylltan",
    "Evric", "Faenric", "Faerwyn", "Faranor", "Fergusen", "Fiachren",
    "Finlaen", "Fintanor", "Flannon", "Foran", "Gairic", "Garethor",
    "Garion", "Garric", "Gawyn", "Gildric", "Gilfaen", "Glenric",
    "Glyndor", "Goran", "Gormach", "Gwydric", "Gwynfael", "Gwyric",
    "Haelenor", "Halric", "Harkinor", "Heledric", "Hollan", "Hywelric",
    "Idron", "Illior", "Ilyraen", "Iorfael", "Iricen", "Ithric",
    "Kaelric", "Kaeron", "Kavanor", "Kellanor", "Kerfael", "Kianor",
    "Kieranor", "Kynric", "Lachanor", "Lairenor", "Lannor", "Leirion",
    "Llewric", "Lochanor", "Lorcanen", "Lugric", "Lynfael", "Maelor",
    "Maeronor", "Malricen", "Marfael", "Marenic", "Medric", "Meirionen",
    "Meradoc", "Merinor", "Merric", "Morran", "Moyric", "Myrfaen",
    "Nairen", "Neiran", "Nemainor", "Nevricen", "Nialen", "Noranic",
    "Odranor", "Oengric", "Oisinor", "Ordan", "Orlaen", "Orrenfael",
    "Owainor", "Padric", "Paranor", "Peadric", "Phelanor", "Piranen",
    "Pryderion", "Raelan", "Rathric", "Rhiannonor", "Rhysfaen", "Riagorn",
    "Rionen", "Ronanor", "Rowanor", "Ruairen", "Sarenor", "Selric",
    "Seranor", "Shenfael", "Siaron", "Sionen", "Sorric", "Sulricen",
    "Talfaen", "Talfenor", "Taranic", "Tarranor", "Tarynfael", "Teiric",
    "Thalion", "Thaneir", "Tiernanor", "Tigernor", "Toranic", "Torfaen",
    "Torinor", "Torric", "Tristanor", "Turlanor", "Uillanor", "Urienfael",
    "Valenric", "Vaughanor", "Vennor", "Verric", "Vornic", "Wenricen",
    "Wynricen", "Ysfaen", "Ysricen", "Yvaen", "Ywenfael"
]

city_names = [
    "Caerwyn", "Eira", "Talrec", "Nolla", "Alwen", "Merric", "Caldon", "Branoc",
    "Siorra", "Relan", "Isla", "Mael", "Tane", "Darrin", "Kaen", "Orlan", "Fiora",
    "Luned", "Brenna", "Corin", "Daegan", "Morwen", "Garric", "Ysolde", "Trevan",
    "Seren", "Rowan", "Leoric", "Taryn", "Elric", "Maeve", "Torren", "Rhiannon",
    "Eamon", "Ciaran", "Bronwen", "Finola", "Gareth", "Nerys", "Aedan", "Lirien",
    "Bryndel", "Eldric", "Aveline", "Seoras", "Fenric", "Tavien", "Meliora", "Draven",
    "Carwyn", "Seraphine", "Malric", "Thalen", "Ariane", "Cairis", "Vennor", "Orryn",
    "Maelis", "Ronan", "Tiora", "Ansel", "Cerys", "Nareth", "Veyla", "Rowenna", "Torin",
    "Ilyra", "Kaelis", "Meran", "Syllis", "Corwen", "Deryn", "Lucen", "Auren", "Eryndor",
    "Faela", "Belen", "Rohain", "Taris", "Fynor", "Brannic", "Solenne", "Caelis", "Mira",
    "Eldwen", "Garron", "Tirren", "Rhiada", "Sorrel", "Maren", "Vallis", "Cadrin", "Enric",
    "Eldren", "Torwyn", "Orissa", "Verris", "Kellan", "Saran", "Cynric", "Theren",
    "Aelric", "Brenwyn", "Caelan", "Dara", "Eithne", "Fionn", "Gwyneth", "Hedwyn",
    "Iorwen", "Jareth", "Kaelen", "Lira", "Maelwen", "Niamh", "Oisin", "Pryderi",
    "Quinn", "Rhydian", "Sian", "Tara", "Urien", "Vaelen", "Wynne", "Xara",
    "Yvaine", "Zephyr", "Aedric", "Branwen", "Cormac", "Deirdre", "Eoghan", "Faelan",
    "Gareth", "Helena", "Ivor", "Jenna", "Kieran", "Lyssa", "Morgan", "Nessa",
    "Owen", "Phelan", "Quinn", "Rhian", "Sorcha", "Tadhg", "Una", "Vaughn",
    "Wyn", "Xander", "Yara", "Zara", "Ailbhe", "Brenna", "Cian", "Dara",
    "Eamonn", "Fiona", "Gavin", "Hannah", "Iain", "Jocelyn", "Keiran", "Lara",
    "Maeve", "Nolan", "Orla", "Padraig", "Quinn", "Roisin", "Sean", "Tara",
    "Ursula", "Vera", "William", "Xara", "Yseult", "Zoe", "Aidan", "Bridget",
    "Cillian", "Dervla", "Eoin", "Fionnuala", "Grainne", "Hugh", "Iseult", "Jude"
]

city_bios = [
    "Once a scholar turned despot, still quoting scripture to justify taxes.",
    "A conqueror who prays daily for enemies to forgive what isn't repented.",
    "Heir to a broken line, obsessed with restoring its glory at any cost.",
    "Spends nights in the archives rewriting ancestors' glory.",
    "Smiles like a saint, bargains like a devil.",
    "Claimed the throne by right, keeps it by rumor.",
    "Wrote treatises on virtue, burned them after coronation.",
    "Learned statecraft from priests and corruption from poets.",
    "Once beloved by the people, now loved only by statues.",
    "Believes mercy is the truest form of control.",
    "Seeks unity through fear, claiming even fear can be holy.",
    "Survived three assassination attempts; the would-be killers now serve as advisors.",
    "A former artist who sees governance as another canvas for perfection.",
    "Rules by decree but speaks in parables.",
    "Keeps an empty throne beside their own for the city's conscience.",
    "Trains in silence by day and whispers in dreams by night.",
    "Collects old debts and older secrets.",
    "Calls the people 'my flock,' though no sermon ever ends well.",
    "Sleeps under banners of prophecy, wakes under banners of war.",
    "Believes history is not written—it's negotiated.",
    "Once a poet, now an editor of truth.",
    "Claims to hear counsel from the city itself.",
    "Prays only for memory to fade when mercy fails.",
    "Tends to the city as one tends to a garden—rooting out dissent and weeds alike.",
    "Spends hours staring at the city's river, muttering names.",
    "Once sold maps, now redraws borders with ink and blood.",
    "Every decree is a confession disguised as law.",
    "Keeps a skull on the desk—rumored to be an old friend.",
    "Rewards loyalty with trust, and trust with exile.",
    "Dreams aloud so others think them sane."
]

city_bios.extend([
    "Once a reformer, now a relic polished daily by their own regret.",
    "Rules from behind curtains of silk and surveillance.",
    "Claims to be descended from the city's first bricklayer — and behaves accordingly.",
    "Believes mercy is a luxury item best kept off the market.",
    "Writes laws in verse and edits them by whim.",
    "Was a philosopher before ambition cured them of curiosity.",
    "Collects enemies as proof of importance.",
    "Laughs like someone who remembers when laughter was banned.",
    "Keeps the crown locked in a chest labeled 'Mistake.'",
    "Believes their reflection gives better advice than their council.",
    "Once outlawed mirrors after losing an argument with one.",
    "Favors parables over policies; none end happily.",
    "Rules by rumor and finds it efficient.",
    "Inherited a throne and a drought; solved one by taxing rain.",
    "Claims to dream for the entire city so others can sleep soundly.",
    "Treats forgiveness as performance art.",
    "Fights corruption mostly to keep it exclusive.",
    "Writes personal apologies to the statues every solstice.",
    "Pretends to hate poetry but quotes it in decrees.",
    "Speaks softly, except to the divine — there they shout.",
    "Believes history will forgive them; plans to edit it personally.",
    "Once burned their own portrait to prove humility.",
    "Married diplomacy, divorced honesty.",
    "Still insists on dining alone with their conscience.",
    "Keeps a cabinet of curiosities labeled 'unkept promises.'",
    "Wears armor made from melted court invitations.",
    "Rules through bureaucracy so dense it might be sentient.",
    "Smiles like a candle guttering in wind — lovely, brief, and dangerous.",
    "Maintains peace through paperwork thicker than faith.",
    "Survived three coups by pretending to be their own twin.",
    "Preaches equality, owns the definition.",
    "Holds a public confession every equinox, timed for applause.",
    "Collects maps of imaginary nations as inspiration.",
    "Was once a beloved teacher until ideals met interest rates.",
    "Dreams of retirement in a world that no longer exists.",
    "Keeps a live hawk on their shoulder named 'Policy.'",
    "Rules a republic that has forgotten the word 'public.'",
    "Knows exactly how many citizens love them — by census.",
    "Outlawed prophecy to monopolize surprise.",
    "Was born during an eclipse and never forgave the sun.",
    "Signs decrees in disappearing ink 'to encourage flexibility.'",
    "Maintains a court of jesters as unofficial historians.",
    "Fears nothing except applause from the wrong crowd.",
    "Carries a dagger carved with their childhood nickname.",
    "Keeps a personal archivist to document all their revisions of self.",
    "Claims their bloodline traces back to a forgotten god of paperwork.",
    "Holds the record for fewest executions and most exiles.",
    "Believes justice should dress well, even when late.",
    "Quotes scripture selectively and with great enthusiasm.",
    "Treats alliances like seasonal fruit — fresh, fragile, easily spoiled.",
    "Commands loyalty mostly through exhaustion.",
    "Maintains order by outlawing coincidence.",
    "Still writes letters to their childhood friend — the revolution.",
    "Hides behind piety the way others hide behind armor.",
    "Rules beside a council that never speaks aloud.",
    "Believes fear ages better than love.",
    "Employs three astrologers and ignores all of them.",
    "Speaks seven languages but trusts none of their translations.",
    "Is adored by children and distrusted by their parents.",
    "Keeps a library of rumors bound in gold leaf.",
    "Believes every rebellion deserves a nice uniform.",
    "Prefers flattery in iambic pentameter.",
    "Wears mourning black for the death of their idealism.",
    "Refused coronation until the crowd begged — a mistake ever since.",
    "Claims to have banished hunger; still hungry for praise.",
    "Consults a mirror-polisher more often than a priest.",
    "Knows the exact weight of their own hypocrisy.",
    "Carries a ring forged from the city's first coin.",
    "Believes the gods envy their efficiency.",
    "Sends spies disguised as philosophers and philosophers disguised as beggars.",
    "Taught the city to pray politely for stability.",
    "Laughs during speeches so no one else knows when to.",
    "Turns every argument into legislation.",
    "Claims democracy is a form of theater they happen to direct.",
    "Keeps a pet crow that delivers vetoes.",
    "Promises transparency and sells tinted glass.",
    "Has survived four assassins, each now employed in public relations.",
    "Worships progress, though none can define it.",
    "Fears peace more than war — peace leaves room for memory.",
    "Collects signed apologies from conquered rivals.",
    "Quotes their enemies as proof of humility.",
    "Prefers speeches to battles and wins both by volume.",
    "Owns more crowns than virtues.",
    "Holds councils at midnight to keep decisions dreaming.",
    "Treats confession as public entertainment.",
    "Still believes destiny can be negotiated.",
    "Has outlawed irony after losing too many debates to it.",
    "Commissions statues taller than their self-awareness.",
    "Keeps an empty throne beside theirs labeled 'The People.'",
    "Plans to retire as a saint, pending paperwork.",
    "Writes love letters to the city disguised as edicts.",
    "Allows criticism in writing, then censors ink.",
    "Claims to rule by divine right but keeps receipts.",
    "Thinks the future looks best in uniform.",
    "Rewrites national myths during long baths.",
    "Collects broken promises the way some collect medals.",
    "Leads parades for causes already lost.",
    "Prays daily that history develops amnesia.",
    "Surrounds themselves with advisors fluent in flattery.",
    "Holds the loyalty of the army by paying its poets.",
    "Despises mirrors, adores portraits.",
    "Believes betrayal is a necessary punctuation in governance.",
    "Smiles with professional accuracy.",
    "Believes progress is just tradition with better branding.",
    "Keeps peace through exhaustion rather than trust.",
    "Rests easy knowing their critics are on the payroll."
])


    "Taught the city to pray politely for stability.",
    "Laughs during speeches so no one else knows when to.",
    "Turns every argument into legislation.",
    "Claims democracy is a form of theater they happen to direct.",
    "Keeps a pet crow that delivers vetoes.",
    "Promises transparency and sells tinted glass.",
    "Has survived four assassins, each now employed in public relations.",
    "Worships progress, though none can define it.",
    "Fears peace more than war — peace leaves room for memory.",
    "Collects signed apologies from conquered rivals.",
    "Quotes their enemies as proof of humility.",
    "Prefers speeches to battles and wins both by volume.",
    "Owns more crowns than virtues.",
    "Holds councils at midnight to keep decisions dreaming.",
    "Treats confession as public entertainment.",
    "Still believes destiny can be negotiated.",
    "Has outlawed irony after losing too many debates to it.",
    "Commissions statues taller than their self-awareness.",
    "Keeps an empty throne beside theirs labeled 'The People.'",
    "Plans to retire as a saint, pending paperwork.",
    "Writes love letters to the city disguised as edicts.",
    "Allows criticism in writing, then censors ink.",
    "Claims to rule by divine right but keeps receipts.",
    "Thinks the future looks best in uniform.",
    "Rewrites national myths during long baths.",
    "Collects broken promises the way some collect medals.",
    "Leads parades for causes already lost.",
    "Prays daily that history develops amnesia.",
    "Surrounds themselves with advisors fluent in flattery.",
    "Holds the loyalty of the army by paying its poets.",
    "Despises mirrors, adores portraits.",
    "Believes betrayal is a necessary punctuation in governance.",
    "Smiles with professional accuracy.",
    "Believes progress is just tradition with better branding.",
    "Keeps peace through exhaustion rather than trust.",
    "Rests easy knowing their critics are on the payroll."
])

