"""
Town-level worldbuilding data.
"""

# ---- TOWN LEVEL ----
town_tones = [
    "a bustling trade town where honesty is a luxury",
    "a proud craftsman's haven with pride as its finest export",
    "a quiet hub of gossip disguised as worship",
    "a crossroads where caravans, thieves, and pilgrims all pass through the same gate",
    "a former garrison town that forgot how to stand at attention",
    "a market town that wears its prosperity like armor",
    "a settlement where laughter comes easily and trust does not",
    "a town whose streets are lined with stalls and unspoken rules",
    "a river of coin flowing through a bed of grudges",
    "a town that sells everything except forgiveness",
    "a place where the forge fires burn later than the temple candles",
    "a town built on bargains, loopholes, and late payments",
    "a weary settlement that survives by knowing when to bow and when to bend",
    "a guild-ruled town where titles are bought more often than earned",
    "a border town that changes its loyalties with the wind",
    "a quiet town with loud debts",
    "a town that has seen too many wars and not enough peace",
    "a settlement where crafts are sacred and saints are optional",
    "a town that prides itself on never closing its taverns",
    "a place where the clocktower keeps perfect time but no one does",
    "a town that feeds the cities and starves its own dreams",
    "a settlement where guild banners hang heavier than the law",
    "a town that grew around a marketplace and never stopped growing",
    "a crossroads that pretends to be a destination",
    "a town that trains apprentices, merchants, and liars with equal skill",
    "a settlement where every family has a trade and a secret",
    "a town that paints smiles on cracked doors",
    "a place that has forgotten what silence sounds like",
    "a town that greets travelers with open arms and counting eyes",
    "a market hub that believes the gods invented coin first and people later",
    "a town that prides itself on surviving every tax increase",
    "a settlement where ambition is measured in stalls, not swords",
    "a town where children learn to haggle before they can read",
    "a place that treats rumor as small change",
    "a town that calls itself humble but counts its wealth nightly",
    "a settlement where the loudest prayers are for profit",
    "a town with more ledgers than legends",
    "a place where every alley holds either a shortcut or a trap",
    "a town that learned to bloom in the cracks of larger empires",
    "a settlement that pretends to be sleepy and never truly is",
    "a windswept crossroad built on bargains older than memory",
    "a stubborn riverport where laughter and labor compete each dawn",
    "a merchant's maze whose alleys smell of spice, sweat, and half-truths",
    "a faded garrison town turned trading haven, still saluting its ghosts",
    "a pilgrimage stop that sells relics no saint ever owned",
    "a proud craft-center that polishes its own myths nightly",
    "a timber town whose sawmills hum louder than sermons",
    "a sleepy grain hub that wakes only for festivals and taxes",
    "a place where debtors hide among dreamers",
    "a fishing quarter that pretends to be a city",
    "a forge town that claims its anvils ring with prophecy",
    "a marketplace so loud the gods have learned to bargain",
    "a wine-blessed town where every oath is toasted twice",
    "a riverbend settlement that changes banks when the floods come",
    "a once-holy borough now ruled by guild tallies and gambling odds",
    "a border trade post that counts seasons by sieges survived",
    "a mining-supply town that smells of sulfur and stubborn pride",
    "a cobblestone sprawl where merchants quote scripture as receipts",
    "a proud textile town weaving fortunes and feuds alike",
    "a dusty stop where travelers swap rumors more valuable than coin",
    "a hill-shadowed town whose towers lean as if eavesdropping",
    "a salt-road junction run by cousins who've forgotten who's elder",
    "a mill-lined settlement where bread tastes faintly of machinery",
    "a lakeside town whose calm masks quick profits",
    "a post-siege refuge rebuilt with salvaged stones and selective memory",
    "a scholar's town that teaches logic by day and illusion by night",
    "a copper-roofed borough gleaming brighter than its morals",
    "a fairground settlement living permanently between celebrations",
    "a trade-cart rest stop that became a republic by accident",
    "a walled town whose watchmen sell passwords by sunset",
    "a smoke-drenched town that smells perpetually of ambition",
    "a merchant guild's experiment that accidentally produced citizens",
    "a town whose founding charter is half legend, half legal loophole",
    "a supply hub where nothing costs what it did an hour ago",
    "a river ferry point turned minor metropolis of gossip",
    "a dusty place where optimism is imported weekly",
    "a smugglers' waystation that learned honesty as camouflage",
    "a town proud of surviving prosperity intact",
    "a quarry town built entirely from its own absence",
    "a market built around an ancient gallows—now the best tavern square",
    "a stubborn high-road town that keeps rebuilding faster than it burns",
    "a wine-route waypoint where politics flow faster than drink",
    "a frontier outpost disguised as a festival ground",
    "a weaving town where patterns repeat through families and fates",
    "a harborless port that trades wind for rumor",
    "a frontier hub whose welcome depends on wind direction",
    "a mead-brewing settlement run by widows who outlived every mayor",
    "a town that prides itself on fairness but defines it hourly",
    "a mud-bank borough whose streets flood with commerce and rain alike",
    "a proud repair town where nothing stays broken except hearts",
    "a shrewd roadside haven that taxes smiles and excuses",
    "a town where architects and arsonists share blueprints",
    "a peaceful-looking town with a duel scheduled most mornings",
    "a sun-baked outpost that worships shade more than gods",
    "a calm-voiced town that negotiates every miracle",
    "a timber-pier town whose children play coin toss with sailors",
    "a mining depot that learned politics by listening to echoes",
    "a trade-school town whose graduates never truly leave",
    "a valley town where music replaces curfews",
    "a saffron-scented hub where color itself is currency",
    "a bell-tower town measuring morality in decibels",
    "a rest stop that pretends to be neutral and never is",
    "a forge settlement where even gossip sparks",
    "a hillfort turned bazaar, still pretending its walls matter",
    "a quarry ridge town whose sunsets look earned",
    "a crossroad of pilgrims where the relic sellers know everyone's sins",
    "a parchment-makers' town perfumed by dust and ink",
    "a smugglers' cove rebranded as a tax office",
    "a town that rebuilt its church into a theater and calls it progress",
    "a river-split borough whose bridges never agree on tolls",
    "a caravan-camp turned democracy of tents and tempers",
    "a settlement that still rings bells for storms that passed centuries ago",
    "a city-wannabe that brags about humility",
    "a bread-scented town with more ovens than sermons",
    "a cold-market hub where words freeze before they reach the listener",
    "a tinker's haven whose inventions occasionally survive testing",
    "a modest inland port forever waiting for the sea to change its mind",
    "a walled garden of taxes and tulips",
    "a fairground-turned-parliament where applause counts as law",
    "a guildborn town that worships efficiency as divinity",
    "a slate-roof settlement echoing with perpetual repair",
    "a narrow-streeted maze where maps are considered treason",
    "a town stitched together from three failed experiments",
    "a night-market borough that shines brighter under embargo",
    "a prosperous town embarrassed by its own luck",
    "a cartwrights' quarter where wheels never stop turning",
    "a perfume town whose air smells sweeter than its intentions",
    "a parchment-signed utopia functioning entirely on optimism",
    "a canal-cut borough where the water judges all disputes",
    "a town that calls every scandal 'last season's sport'",
    "a bronze-bell town that measures wealth by echo",
    "a refugee-founded town that refuses to die quietly",
    "a mountain-road town that barters shelter for secrets",
    "a cider town whose festivals last until regret begins",
    "a faded court town that remembers its etiquette but not its purpose",
    "a market-at-the-edge town where bargains end and wildlands begin",
    "a bustling trade nexus that never truly sleeps, only pauses to count",
    "a riverside borough where every stone remembers a bargain",
    "a windswept market town built on promises and unpaid favors",
    "a forge-town whose smoke writes its own scripture against the sky",
    "a crossroad of caravans, pilgrims, and pickpockets alike",
    "a seaside quarter where sails and secrets billow together",
    "a faded garrison rebuilt as a sanctuary for merchants and mercenaries",
    "a cheerful place that hides its debts behind laughter and song",
    "a muddy port that claims every flood is a baptism of profit",
    "a stone-walled town whose watchmen trade boredom for beer",
    "a tavern-born settlement that grew around its own bad ideas",
    "a guild-run borough where law and logistics are synonyms",
    "a smugglers' haven legalized by paperwork",
    "a border-town so often conquered it speaks in three currencies",
    "a cobblestoned warren where even sunlight must pay toll",
    "a faded monastery turned mint, now worshipping efficiency",
    "a timber-spired town where carpenters argue theology through architecture",
    "a quarry-side settlement that hums like a hive of ambition",
    "a fishing depot reeking of salt, superstition, and song",
    "a wine-market town whose drunkards quote scripture accurately",
    "a frontier waystop patched together from the dreams of deserters",
    "a weaving town that spins both cloth and rumor with equal skill",
    "a bridge-town split by river and united by gossip",
    "a copper-roofed borough glittering like false gold at dusk",
    "a town founded on the premise that taxes can outlast faith",
    "a caravan post that mistook motion for progress",
    "a bell-rung borough where curfew is optional but guilt mandatory",
    "a parchment-makers' district perfumed by dust and pride",
    "a granary town that measures virtue in grain and gossip",
    "a lakeside refuge whose reflection looks more honest than it is",
    "a crossroad of saints and smugglers who use the same blessings",
    "a timber outpost that prays to the forest for forgiveness",
    "a high-road town with too many inns and not enough exits",
    "a salt-harvest borough where laughter tastes briny",
    "a hillside town whose markets echo louder than its church bells",
    "a mint-town that worships the sound of coin more than its saints",
    "a farmstead metropolis where manure and money mix freely",
    "a spice-town whose colors dazzle and distract",
    "a glassblowers' borough where truth is always fragile",
    "a painter's haven where every wall lies beautifully",
    "a scriptorium village where gossip is footnoted and cross-referenced",
    "a brewery-town that counts sermons in pints",
    "a fortress turned counting house, bricks mortared with ambition",
    "a place where every street corner smells faintly of negotiations",
    "a mead-route stop that survived three raids and one bad harvest",
    "a sleepy township whose dreams are more vivid than its days",
    "a pilgrim's last rest before regret",
    "a hillside borough echoing with the ring of anvils and arguments",
    "a market junction where the poor sell faith and the rich buy absolution",
    "a frost-bitten settlement whose only warmth comes from trade fires",
    "a lumber-town whose axes double as family heirlooms",
    "a meadowtown whose festivals last until the livestock complain",
    "a wine-route hamlet proud of both hangovers and heritage",
    "a ruin rebuilt with optimism and unlicensed masonry",
    "a star-viewing town where every astrologer is broke and beloved",
    "a barge-town that drifts slightly farther downstream each year",
    "a lantern-lit borough where night never ends and neither do the deals",
    "a crossroad settlement kept alive by habit and hope",
    "a town whose air smells of bread, ink, and revenge",
    "a repurposed fortress now defended by bureaucracy",
    "a beacon-town where even the fog pays rent",
    "a plains hub that pretends the horizon is progress",
    "a farmhand's collective that accidentally invented democracy",
    "a tannery-town where patience and hides cure together",
    "a hillfort converted to warehouses and optimism",
    "a spice-junction that tastes of risk and rain",
    "a dockside borough where sailors spend faith like coin",
    "a red-clay town where every footprint leaves an opinion",
    "a swamp-edge outpost half sunk and wholly stubborn",
    "a wool-town whose silence smells faintly of lanolin",
    "a high-valley community that swears each echo belongs to an ancestor",
    "a wine-cellar settlement carved under its own vineyards",
    "a clocktower town obsessed with punctuality and denial",
    "a parchment-town that files miracles under 'miscellaneous'",
    "a storm-battered township where courage is measured in roof repairs",
    "a fairground settlement that never packed up its tents",
    "a grain-merchant borough that counts festivals as fiscal quarters",
    "a bridge-city whose toll collectors know more theology than priests",
    "a cliffside trade post that greets the sunrise with hangovers",
    "a cobbler's haven where roads lead outward faster than dreams",
    "a canal-cut town whose reflections are tidier than its citizens",
    "a bronze-workers' town that glows even after sunset",
    "a toll-road settlement that measures loyalty in receipts",
    "a watermill borough where gossip turns faster than gears",
    "a clay-banked town molded daily by floods and forgiveness",
    "a limekiln settlement that paints every roof white as denial",
    "a guildborn borough where apprentices run everything after dusk",
    "a saddle-makers' quarter that breeds both horses and rumors",
    "a merchant-founded enclave ruled by inherited IOUs",
    "a toll-bridge kingdom pretending not to be small",
    "a festival-town that refuses to end the celebration out of superstition",
    "a parchment-mart where ink stains reputations permanently",
    "a string of taverns legally recognized as a municipality",
    "a pottery hub where shards outnumber whole truths",
    "a border-borough that hosts duels as civic entertainment",
    "a charcoal settlement that smells of ambition and regret",
    "a salt-pan town shimmering under perpetual mirage",
    "a reed-market town that hums when the wind shifts",
    "a peninsular haven of merchants who never look inland",
    "a crag-foot borough whose roofs cling to cliffs like stubborn hope",
    "a mead-town where laughter is both currency and confession",
    "a plains-border outpost trading harvest for stories",
    "a baker's town where every loaf hides a family feud",
    "a harp-makers' borough that hums even at night",
    "a dye-town stained more by rumor than pigment",
    "a lumber-route junction perfumed by sawdust and secrets",
    "a mule-stop town whose patience rivals its beasts",
    "a fortification turned flea market",
    "a seaside borough where coins are polished more than consciences",
    "a bridge-market hub sustained by tolls and tall tales",
    "a parchment-trading colony that measures years in signatures",
    "a forge-district rebuilt entirely out of discarded ambition",
    "a half-sunken trade hamlet whose courage outpaces its infrastructure",
    "a frontier town that still believes prosperity is contagious",
    "a rural trade loop disguised as civilization",
    "a meadow-town that exports good cheer by the barrel",
    "a grain-junction that celebrates taxation as sport",
    "a hill-line borough famed for cider, scandal, and second chances",
    "a ferry-town where arrivals and departures are equal business",
    "a peatland community that smells perpetually of nostalgia",
    "a frost-worn market that sells wool, ale, and dubious advice",
    "a brewery-haven whose saints are all drunks and dreamers",
    "a highland tollgate where merchants tithe to mountain spirits",
    "a painted-town of murals masking old scars",
    "a caravan crossroad that renames itself every decade for luck",
    "a lakeshore hub of reflection and deception alike",
    "a root-path village run by stubborn families and older grudges",
    "a cliff-perched haven where wind replaces conversation",
    "a river-junction town that prays for low water and high trade",
    "a plowland borough whose gods wear farmer's hands",
    "a midnight market hamlet that glows long after sense sleeps",
    "a slate-roof town that echoes every rainstorm like applause",
    "a quiet borough pretending to be unimportant and succeeding",
    "a sunlit plain town where time itself slows to negotiate",
    "a gossipy guild borough where truth is subcontracted",
    "a broken-fort town held together by stubbornness and hope",
    "a honey-town whose bees are better organized than its council",
    "a parchment-court borough where bureaucrats quote poetry badly",
    "a wainwrights' market surrounded by cartwheel halos",
    "a twilight settlement whose lamps burn through dawn as protest",
    "a logging hub so deep in debt it counts trees as currency",
    "a hillshadow borough that never forgave the sunrise",
    "a waystation so old the road itself bows in respect"
]

town_flavors = [
    "Its crest shows a balance, always tipping.",
    "Children here play at being merchants long before they can count.",
    "The town motto translates loosely to 'Never for Free.'",
    "Banners of guilds blot out the sky in every festival.",
    "Rumors sell faster than bread at dawn.",
    "Charity is profitable if properly witnessed.",
    "The guards carry ledgers as readily as spears.",
    "Its busiest shrine is the one dedicated to Good Fortune.",
    "The taverns keep better records than the town hall.",
    "Old disputes are cataloged with the same care as trade routes.",
    "Market bells ring louder than temple bells.",
    "Outsiders are welcome, their ignorance more welcome still.",
    "Every loan here comes with a story attached.",
    "The town clerk can recite debts better than names.",
    "No secret lasts more than a week without being priced.",
    "Celebrations are frequent; excuses for them even more so.",
    "The main square is paved with promises, none written down.",
    "Children are taught to smile, nod, and never agree too quickly.",
    "A single market stall has toppled more careers than battles.",
    "Old guild wars are commemorated with sales.",
    "Even beggars quote interest rates.",
    "The town's oldest family is the one that never appears on any ledger.",
    "Contracts are sealed with wax, wine, and wary eyes.",
    "Each guild keeps a private shrine to its patron vice.",
    "The town crier announces discounts as loudly as decrees.",
    "Sometimes trials are held in the marketplace, for convenience.",
    "Bribes are called 'expedited gratitude.'",
    "The road tolls are adjusted according to the mood of the council.",
    "The town is known for never turning away a stranger, or a profit.",
    "The temple collects tithes in coin, confession in passing.",
    "Every shop sign includes a blessing against mischief and miscounting.",
    "Local sayings compare trust to a coin—valuable, but too easily spent.",
    "They say if you drop a coin, the street decides who deserves it.",
    "The watch rotates posts often to prevent familiarity and favors.",
    "Nights are brighter near the taverns than near the temple.",
    "The tax code is thicker than the town chronicle.",
    "Disputes are often settled over dice and ale.",
    "The oldest bridge is said to collapse beneath unpaid debts.",
    "A festival of trade is held every year to celebrate surviving the last one.",
    "A ledger fire once nearly destroyed the town; some suspect it was deliberate.",
    "Merchants haggle as if faith itself were negotiable.",
    "Every window box hides a spy and a geranium.",
    "The town guard doubles as an accounting guild.",
    "Local proverbs begin with prices and end with apologies.",
    "Each tavern claims to have invented honesty, none prove it.",
    "Festivals occur weekly, usually by accident.",
    "Beggars offer directions in exchange for gossip.",
    "Children practice barter using pebbles and promises.",
    "The mayor's dog receives more petitions than the mayor.",
    "Every roof tile has been mortgaged at least once.",
    "Fires are frequent, forgiveness rarer.",
    "The temple tithes in both coin and rumors.",
    "Visitors are welcomed with warmth and assessed for solvency.",
    "Even the pigeons seem to deliver invoices.",
    "Street criers compete with rival sermons for attention.",
    "The council keeps minutes but sells interpretations.",
    "A silver coin tossed in the well buys one wish or one witness.",
    "No one recalls who built the town hall, but everyone blames him.",
    "The main square smells of bread, sweat, and mild deceit.",
    "The watch captain is rumored to be on both payrolls.",
    "Half the signboards hang upside-down in protest of something forgotten.",
    "Every cobbler claims to shoe destiny itself.",
    "The baker's ovens double as a rumor mill.",
    "Rainfall is measured in lost sales, not inches.",
    "No theft goes unrecorded; few go unbilled.",
    "Coins jingle like prayer beads in every pocket.",
    "The old gallows post now supports a flower basket.",
    "The apothecary's cures are effective against boredom.",
    "A market bell tolls whenever truth is spoken—rarely.",
    "The notary offers discounts for silence.",
    "Old debts are celebrated as anniversaries.",
    "Children's songs rhyme perfectly with tax codes.",
    "Duelists meet weekly to settle accounts poetic or otherwise.",
    "The town anthem changes key with each administration.",
    "Rats pay rent in secrets.",
    "Every milestone marks the spot of a former tavern.",
    "The clocktower runs five minutes fast to encourage productivity.",
    "All business pauses for gossip at noon.",
    "The tannery pays its workers in credit and courage.",
    "Letters of introduction are valid until laughed at.",
    "Even the wells charge interest.",
    "A modest scandal is considered healthy competition.",
    "Nobles visit incognito and leave indebted.",
    "Every mural contains at least one legal disclaimer.",
    "Festival banners double as account ledgers.",
    "Shopkeepers quote philosophy with the same conviction as prices.",
    "The brewer's apprentices run the local government during harvest season.",
    "Lost property is auctioned before the owner finishes complaining.",
    "Town criers announce births, deaths, and clearance sales.",
    "Citizens argue politics only when sober, hence rarely.",
    "Each district keeps its own holidays to confuse outsiders.",
    "Bridges collapse ceremonially every decade for tourism.",
    "Taxes are paid in coin, kind, or elaborate compliments.",
    "The oldest streetlamp is rumored to grant small regrets.",
    "Every bench bears initials of both lovers and lawsuits.",
    "The postmaster writes better poetry than the priests.",
    "Chimneys whisper louder than sermons.",
    "Every guild has at least one patron ghost.",
    "Even pigeons avoid the council chamber on market days.",
    "Visitors who stay a week forget what quiet means.",
    "The cobblestones are slick with tradition.",
    "Every dog here understands three commands and two conspiracies.",
    "The shoemaker claims to have mended a god's sandal once.",
    "Arguments about interest rates qualify as sport.",
    "A statue in the square points accusingly at city hall—no one knows why.",
    "Children sell tickets to watch council meetings.",
    "Even sunrise is scheduled here.",
    "The tax collector publishes a romance novel each winter.",
    "The apothecary insists all ailments are fiscal in nature.",
    "Fishmongers debate theology over scales and salt.",
    "Weddings are public; divorces charge admission.",
    "A festival once lasted so long it became a fiscal quarter.",
    "The town crier occasionally announces his own debts.",
    "Bards here are paid per exaggeration.",
    "Every warehouse has a back door into history.",
    "When it rains, the market smells like ambition.",
    "Old curses are treated as municipal property.",
    "The best wine in town is watered by tears of accountants.",
    "Half the population serves on committees; the other half hides from them.",
    "Newcomers are warned never to trust smiling bakers.",
    "Every fourth lantern is dedicated to Saint Coincidia, patron of luck.",
    "The archives contain recipes, receipts, and revolutions.",
    "Children draw trade routes instead of castles.",
    "A single goose owns more property than some merchants.",
    "Public debates are settled by applause meters.",
    "Night watchmen whistle the town anthem backward for luck.",
    "A clockmaker runs the temple bells out of spite.",
    "Visitors often mistake sarcasm for friendliness—and aren't wrong.",
    "Festivals here end only when the ale or the patience runs out.",
    "Every tavern keeps a running tab on the truth.",
    "The mayor's portrait changes expressions daily.",
    "Stray dogs here obey the tax collector but no one else.",
    "Children play at merchant councils with stones for coins.",
    "No clock runs the same time, but all agree when debts are due.",
    "Fishermen swear they've seen gold coins in the river mud—none admit diving for them.",
    "Every roof tile is signed by its maker as a silent complaint.",
    "The cobblestones hum with old wagon songs after rain.",
    "Bakers rise before dawn to gossip with ghosts still wandering home.",
    "Every well has a name and a reputation for advice.",
    "Once a week the town bell rings without human help.",
    "Traders mark their stalls with charms carved from broken oaths.",
    "Even the pigeons look like they've done time for smuggling.",
    "Children learn arithmetic by counting empty bottles.",
    "The council meets in the tavern; order of business follows the ale list.",
    "There's a rumor that the tax ledgers write back.",
    "Every third house doubles as a shrine to good luck and bad timing.",
    "When it rains, the streets smell of iron, hope, and regret.",
    "The apothecary bottles 'courage' in unlabeled flasks.",
    "Locals cheer the sunrise like gamblers backing a long shot.",
    "Half the signposts point toward places that don't exist anymore.",
    "The market square never empties—only rearranges.",
    "Tavern stools are carved with initials of both lovers and lawsuits.",
    "A forgotten fountain still grants small fortunes and large headaches.",
    "The town guard plays dice with destiny—literally, according to legend.",
    "Every bench doubles as a courtroom after dark.",
    "Pigeons here deliver IOUs instead of messages.",
    "Once a year the baker refuses payment 'to keep the gods guessing.'",
    "Every child knows three recipes for soup and one for blackmail.",
    "The chandlery's candles burn different colors on election days.",
    "Street vendors call each other cousin—sometimes accurately.",
    "No one remembers founding day, so they celebrate twice.",
    "The smith claims sparks are spirits trying to escape his anvil.",
    "Masons argue about who laid the first stone—and who'll remove the last.",
    "Every tavern band plays one song that isn't on purpose.",
    "The town motto changes depending on who's drunk enough to declare it.",
    "Even the beggars carry business cards.",
    "Rain gutters double as message tubes between rival lovers.",
    "The clock tower stopped decades ago but still rings at lunchtime.",
    "Every new mayor inherits a secret drawer and a nervous twitch.",
    "Visitors are greeted with warmth and assessed for collateral.",
    "Children dare each other to steal taxes from the donation box.",
    "A goat once served on the council and arguably did the best job.",
    "Every wine barrel bears initials of the ambitious and the doomed.",
    "Town gossip travels faster than plague but less reliably.",
    "There's a bench in the square no one sits on twice—bad knees guaranteed.",
    "The postman delivers both letters and verdicts.",
    "Most families own at least one heirloom lie.",
    "The baker names each loaf after a local scandal.",
    "During storms, the streets smell like envy and wet parchment.",
    "The mayor's parrot knows every confession ever whispered nearby.",
    "Festival banners are repurposed legal documents.",
    "Old debts are framed and displayed like art.",
    "Every second candle in the temple flickers with guilt.",
    "Street musicians tune their instruments to the sound of arguments.",
    "There's a shop that sells nothing but apologies on fine paper.",
    "Half the lamplighters are spies, the other half are poets.",
    "The smith's apprentice swears the forge answers back sometimes.",
    "Children sell fake maps to real places.",
    "Dogs bark only when politicians lie—hence the noise.",
    "A single goose has held the same corner for thirty years.",
    "Newcomers are welcome until they try to change anything.",
    "The tax collector moonlights as the town matchmaker.",
    "Coins here smell faintly of cinnamon and guilt.",
    "At dusk, the wind carries whispers too rehearsed to be random.",
    "Local superstition says laughter keeps the bridges standing.",
    "Merchants measure honesty by the pound.",
    "Every shopkeeper can recite the local charter but ignores it.",
    "Streetlights dim when someone lies in court.",
    "Every mural hides at least one face the painter regretted.",
    "There's a lane where only lovers and debtors dare walk.",
    "The apothecary sells tonics for boredom and envy alike.",
    "Once a year the council auctions the right to start rumors legally.",
    "Carpenters leave wooden charms under doorframes 'for stability of mood.'",
    "The undertaker doubles as the florist for convenience.",
    "A street preacher shouts prosperity sermons to pigeons—and gets donations.",
    "When a bell rings thrice after midnight, someone just changed sides.",
    "The butcher claims his knives predict market trends.",
    "Each rainstorm brings a new proverb no one understands.",
    "The mayor's handwriting is rumored to curse contracts.",
    "Children skip stones into the well for luck; adults for revenge.",
    "Old bridges groan louder than citizens at tax season.",
    "Every chair in the council hall wobbles on purpose.",
    "Some taverns pay their bills in poetry—poorly written poetry.",
    "No one counts the cats, but everyone swears there are more weekly.",
    "Each tradesman has a sworn rival in the next street.",
    "Festivals begin as accidents and end as traditions.",
    "The local paper publishes gossip disguised as weather reports.",
    "Once a year, the cobblers refuse to sell left shoes—it's a long story.",
    "Every chimney leans slightly toward the richer district.",
    "The wine tastes better during arguments.",
    "Public statues are all missing one small but significant detail.",
    "No one admits to running the town, but everyone takes credit.",
    "The market clock has two faces, neither honest.",
    "A raven sits above the courthouse roof and laughs during trials.",
    "Every alley has at least one deal waiting to happen.",
    "Shop signs swing even when there's no wind—especially then.",
    "The local tailor mends reputations for a fee.",
    "Newcomers are measured in how well they lie politely.",
    "Rain brings out colors the town denies owning.",
    "The tax office smells faintly of honey and fear.",
    "Every window box hides either herbs or evidence.",
    "Rumors are weighed like grain and priced accordingly.",
    "The candle-maker's daughter writes love notes in wax.",
    "A chalk mark on a door can mean trust, trouble, or tea.",
    "Every musician's case contains both instrument and alibi.",
    "The bell tower leans slightly toward temptation.",
    "During feast days, all rules bend but none quite break.",
    "Even the dogs observe market hours.",
    "Pigeons here vote by majority on leftover bread.",
    "A council meeting once lasted three days; no one remembers why.",
    "Rain turns the streets into rivers of reflection and regret.",
    "The town square tilts a little more each year, like its morals.",
    "The brewer's family crest features a hangover and a halo.",
    "Every shop claims the same miracle occurred there first.",
    "The old innkeeper knows everyone's secrets and discounts accordingly.",
    "The constable carries both handcuffs and a harmonica.",
    "Festival masks are kept year-round, just in case honesty breaks out.",
    "Half the town swears by luck; the other half rents it.",
    "The baker's guild publishes moral advice on the backs of receipts.",
    "Even the beggars use accounting ledgers.",
    "When fog rolls in, so do opportunities.",
    "Merchants count stars like inventory.",
    "The mayor's office keeps a complaint box large enough to live in.",
    "Every door squeaks in its own dialect.",
    "The town crier rhymes his proclamations for plausible deniability.",
    "Shopkeepers bless scales before weighing gold.",
    "Rainwater runs red once a year—no one agrees on why.",
    "The fishmonger hums sea shanties in perfect legal disclaimers.",
    "Children play 'council meeting' to learn interruption timing.",
    "Even thieves issue receipts now and then.",
    "Lanterns sway when promises are broken.",
    "Every wall has at least one secret mapped in graffiti.",
    "When thunder rolls, everyone checks their ledgers.",
    "There's an unspoken rule about whistling after dusk—no one remembers who broke it first.",
    "The street cats keep better records than the magistrate.",
    "Winds here carry old jokes and unpaid invoices.",
    "Even the baker's clock runs on borrowed time.",
    "Citizens claim they can smell a lie—especially near payday.",
    "The temple choir sells its silences individually.",
    "There's a toll for leaving, but no one ever collects it.",
    "Every handshake counts as a minor legal agreement.",
    "Bread here rises with suspicious consistency.",
    "When the moon is full, laughter echoes where no one stands."
]

town_titles = [
    "Guildmaster", "Provost", "Bailiff", "Warden", "Magistrate", "Factor",
    "Steward", "Captain of the Watch", "Marshal", "Mayor", "Chief Artificer",
    "Harbormaster", "Overseer", "Comptroller", "Prefect", "Registrar",
    "High Merchant", "Constable", "Chief Factor", "Trade Reeve",
    "Market Warden", "Coin Marshal", "Town Reeve", "High Steward",
    "Gate Captain", "Council Speaker", "Quartermaster", "Waywarden"
]

town_bios = [
    "Rose from apprentice to master through grit and opportunism.",
    "Preaches fairness but practices arithmetic.",
    "Knows the weight of every coin and the price of every conscience.",
    "Once loved justice; now married to compromise.",
    "Fought in wars, sells medals as souvenirs to passing soldiers.",
    "Keeps peace by keeping everyone equally uncertain.",
    "Writes ledgers in neat script and curses in clumsy shorthand.",
    "Smiles only when the numbers favor the town.",
    "Once refused a bribe out of principle, later learned to price principles.",
    "Measures loyalty by the hour and productivity by the sigh.",
    "Defended a border so long the town forgot there was a war.",
    "Saved the town from famine by rationing truth and grain.",
    "Built the first proper docks—and the first secret smuggling route beneath them.",
    "Runs the market by day and a private card game by night.",
    "Claims neutrality in politics while quietly funding every side.",
    "Learned diplomacy from exiled nobles and trade from desperate peasants.",
    "Keeps a ledger of sins and a ledger of profits—and ensures they balance.",
    "Trusts contracts more than vows, ink more than blood.",
    "Once sold their family heirloom to cover a town debt and never asked it back.",
    "Believes that kindness should never interfere with efficiency.",
    "Nurses a quiet hatred for laziness, especially in themselves.",
    "Keeps a small locked box on their desk that no one has seen opened.",
    "Remembers every face that ever begged for an extension.",
    "Carries the town's charter rolled inside their coat, close to the heart.",
    "Once wanted to be a priest; settled for balancing other people's sins.",
    "Maintains a secret fund for disasters and another for 'opportunities.'",
    "Has the unsettling habit of remembering details no one recalls saying.",
    "Argues tariffs with the same intensity others reserve for theology.",
    "Sleeps little and dreams often of empty streets and full granaries.",
    "Believes the town must prosper, even if no one remembers who led it there.",
    "Rose from a dockhand to magistrate by selling favors more deftly than fish.",
    "Keeps peace with charm and a hidden dagger.",
    "Once defied the guild council; now chairs every meeting.",
    "Believes commerce is the purest form of confession.",
    "Preaches transparency while collecting stained-glass secrets.",
    "Inherited the office, not the patience.",
    "Still uses the quill that signed their first bribe.",
    "Survived three bankruptcies and one poisoning, learning from each.",
    "Finds inspiration in ledgers and poetry in tariffs.",
    "Has never lost a negotiation, only postponed a victory.",
    "Pretends to despise gambling, but calls every deal a wager.",
    "Once fed a mob with bread and speeches, saving both town and reputation.",
    "Trained under a priest and a pickpocket, quoting both equally.",
    "Keeps a lucky coin engraved with the word 'Mercy'—never spends it.",
    "Bans gossip officially but encourages it strategically.",
    "Secretly funds the orphanage and the thieves' guild alike.",
    "Earned respect through punctuality, fear through memory.",
    "Believes charity without profit is just poor accounting.",
    "Wrote the town's code of ethics, framed it, and ignored it.",
    "Claims their signature alone keeps the walls from crumbling.",
    "Lost a family to famine, found purpose in taxes.",
    "Knows exactly how much silence costs.",
    "Sleeps under portraits of rivals, 'to stay alert.'",
    "Quotes scripture only during audits.",
    "Fought corruption for a decade before realizing efficiency was faster.",
    "Sells civic virtue by the barrel, like good wine.",
    "Hates waste, loves loopholes.",
    "Treats each day like a ledger: balanced, bloodied, or both.",
    "Believes justice can be improved with interest.",
    "Speaks softly but carries an itemized list.",
    "Once promised to abolish taxes; invented new ones instead.",
    "Finds solace in clean ink and quiet betrayal.",
    "Writes poems no one is allowed to read.",
    "Won their position in a card game; lost their innocence the same night.",
    "Keeps the peace by knowing who not to offend.",
    "Counts every breath as an investment in longevity.",
    "Considers honesty a seasonal delicacy.",
    "Laughs like a coin flipping midair.",
    "Planted trees to shade streets they'll never walk again.",
    "Carries guilt folded neatly into policy.",
    "Thinks mercy should accrue compound interest.",
    "Owns more paper than conscience.",
    "Once outlawed duels—then challenged the enforcer.",
    "Wakes before dawn to rewrite the town's definition of fair.",
    "Believes the market is a mirror for the soul, cracked but reflective.",
    "Favors pragmatism over passion, but regrets it each spring.",
    "Collects debts in coin, gratitude, and silence.",
    "Keeps minutes from every meeting, annotated with private judgments.",
    "Measures loyalty by how quickly it pays dividends.",
    "Speaks four languages: trade, threat, flattery, and silence.",
    "Once turned down a bribe simply to prove they could.",
    "Despises laziness almost as much as self-reflection.",
    "Buys confessions as souvenirs.",
    "Claims to dream of reform but never wakes up early enough.",
    "Keeps a prayer candle burning on the ledger desk.",
    "Knows that virtue, properly priced, sells itself.",
    "Pardoned an embezzler just to study his technique.",
    "Refers to workers as 'citizens in draft form.'",
    "Laments that corruption is so poorly organized.",
    "Owns the largest library in town, mostly of old receipts.",
    "Fears no god that can't be audited.",
    "Rewards honesty like an exotic spice—rarely and with ceremony.",
    "Keeps an assassin on retainer as a 'consultant in conflict resolution.'",
    "Claims to have once bartered with fate and won.",
    "Hides their doubts in long speeches about duty.",
    "Believes the council exists mainly to admire them.",
    "Once raised taxes to prove a point; forgot what the point was.",
    "Treats rumor as weather: unavoidable, profitable, and seasonal.",
    "Made a fortune selling the idea of restraint.",
    "Rebuilt the town's wall higher, then sold tickets to climb it.",
    "Writes speeches backward to ensure they end dramatically.",
    "Believes honesty should be taxed as a luxury.",
    "Invented a new measurement of loyalty: how long silence lasts after pay.",
    "Claims to have a clean conscience—outsourced, naturally.",
    "Was exiled once, but the exile never left their tone.",
    "Knows every lie begins with the phrase 'for the good of the town.'",
    "Carries a silver quill said to write only when watched.",
    "Prefers simple people; they're easier to complicate.",
    "Trained their successor years ago—then promoted them sideways.",
    "Finds diplomacy most effective after dessert.",
    "Collects maps of towns that failed, for perspective.",
    "Once solved a famine by redefining hunger.",
    "Keeps the peace by pretending everyone's already guilty.",
    "Never swears in public—uses taxation instead.",
    "Has never built a monument, but every decree feels like one.",
    "Carries the town's seal and three personal escape routes.",
    "Pretends not to understand poetry but quotes it in private letters.",
    "Rewrote the guild charter to include a clause about patience.",
    "Dreams of leaving office, then wakes up and laughs.",
    "Once took an oath of service and has regretted every renewal.",
    "Keeps a jar of old coins from the rebellion, 'for luck or warning.'",
    "Hired a bard to chronicle their humility.",
    "Counts enemies like investments: diversified, stable, and long-term.",
    "Speaks of duty as others speak of debt—inevitable and never settled.",
    "Once resigned in protest, then fined themselves for inefficiency.",
    "Uses words like armor and charm like currency.",
    "Claims the gods admire consistency, if not morality.",
    "Rebuilt the marketplace after every fire, always with wider stalls.",
    "Laughs quietly during storms—'good for trade,' they say.",
    "Was once a blacksmith who learned diplomacy by cooling tempers instead of iron.",
    "Inherited the title from an aunt who faked her own death to retire quietly.",
    "Believes leadership is just another form of negotiation—with fewer refunds.",
    "Was caught smuggling once, and then promoted for efficiency.",
    "Keeps a hidden cellar of unpaid debts and unpaid kindnesses.",
    "Ran away from nobility to prove competence and never quite did.",
    "Hired a bard to rewrite their past and now believes every word.",
    "Swears by fairness, but their definition shifts like market prices.",
    "Once saved the town by selling its future at half price.",
    "Has never drawn a sword but has ruined many reputations with a smile.",
    "Lost their family in a fire and rebuilt both the home and the habit of control.",
    "Believes the gods are accountants with longer patience.",
    "Fell in love with a rival mayor and solved the issue by annexation.",
    "Claims their greatest strength is 'knowing when to apologize publicly.'",
    "Has nightmares about running out of ink mid-decree.",
    "Once disguised themselves as a beggar to test charity; was disappointed.",
    "Measures time in trade cycles and regrets in missed opportunities.",
    "Was elected on a dare and never found the courage to resign.",
    "Knows every citizen's name and half their secrets.",
    "Trained under a guildmaster who taught them that loyalty is a luxury.",
    "Claims to sleep soundly, which everyone takes as a threat.",
    "Invented a new tax and called it a 'community contribution.'",
    "Once bribed a priest to declare a miracle of good bookkeeping.",
    "Survived a duel by letting the opponent trip over etiquette.",
    "Writes poetry no one's allowed to read—not even themselves.",
    "Believes mercy is a currency with terrible exchange rates.",
    "Keeps a small shrine to luck, which they refuse to clean or question.",
    "Resigned once, only to find no one else wanted the job.",
    "Sees every argument as a form of long-term investment.",
    "Hides anxiety behind a perfect posture and polished boots.",
    "Prefers ledgers to people; ledgers lie less.",
    "Once banned sarcasm for a week—crime rates doubled.",
    "Still signs documents with a flourish learned from theater.",
    "Trusts no one who drinks water at council meetings.",
    "Claims to have met a god once and fined them for loitering.",
    "Has been re-elected six times by the same three families.",
    "Believes laughter keeps mutiny at bay.",
    "Insists on lighting their own hearth to 'remember labor.'",
    "Refuses to marry on principle and politics alike.",
    "Writes thank-you notes to rivals, each a veiled insult.",
    "Never forgets a favor—especially the ones they regret.",
    "Claims the town anthem was written about them, and no one argues.",
    "Once sold the naming rights of the main road to fund repairs.",
    "Believes reform begins with properly alphabetized laws.",
    "Uses politeness as both shield and weapon.",
    "Was an idealist once; the scars are still visible in the budget.",
    "Keeps a secret map of the town's hidden escape routes.",
    "Hates festivals, yet always ends up dancing last.",
    "Was trained by monks who valued silence and now weaponizes it.",
    "Believes nothing can't be solved with tea, time, and tactful lying.",
    "Once accidentally started a small revolution with a speech about punctuality.",
    "Carries a dagger inscribed with the words 'In Case of Democracy.'",
    "Regrets nothing except signing their own paycheck.",
    "Claims to own the town only metaphorically—then collects rent literally.",
    "Was adopted by the guild that later tried to overthrow them.",
    "Keeps a stuffed fox in their office for inspiration.",
    "Lost an election, then bought the winner's debts.",
    "Wrote a play under a pseudonym; it flopped spectacularly.",
    "Believes charm is a renewable resource.",
    "Used to teach arithmetic; still counts every silence.",
    "Fought corruption for years before realizing it paid better.",
    "Survived assassination once; thanked the assassin for improving reflexes.",
    "Was once a con artist—still claims it's a form of leadership.",
    "Keeps a collection of canceled treaties as bedtime reading.",
    "Claims to hate ceremony but never skips applause.",
    "Speaks three languages and lies fluently in all of them.",
    "Believes honesty works best when rationed.",
    "Once pardoned a thief for creativity.",
    "Treats compliments like bribes—carefully and with suspicion.",
    "Lost their voice shouting reforms; found power in whispering deals.",
    "Has rewritten the town motto four times in ten years.",
    "Believes forgiveness should come with paperwork.",
    "Once outlawed gambling, then placed a bet on enforcing it.",
    "Trusts the butcher more than the treasurer.",
    "Knows the exact number of lanterns in town—and why two are missing.",
    "Enjoys quoting law to the people who wrote it.",
    "Dreams of retirement, but the town keeps waking them up.",
    "Keeps a mirror on their desk to practice looking sincere.",
    "Regarded as fair, until fairness became inconvenient.",
    "Refers to scandals as 'administrative adventures.'",
    "Keeps coins from every bribe they refused—so far one jar full.",
    "Knows how to turn outrage into policy efficiently.",
    "Collects excuses the way others collect stamps.",
    "Believes democracy is a play best performed with strict choreography.",
    "Once abolished curfews, then reinstated them after one disastrous wedding.",
    "Hires rivals as advisors to ensure constant irritation.",
    "Claims to value justice but secretly prefers balance sheets.",
    "Fears no god, only auditors.",
    "Refuses portraits, insisting no painting captures hypocrisy accurately.",
    "Once threw a festival to celebrate punctual tax payments—it failed.",
    "Maintains an impeccable desk and a chaotic soul.",
    "Was found not guilty of corruption and took it personally.",
    "Writes anonymous letters to the editor correcting grammar.",
    "Claims morality is a regional dialect.",
    "Keeps track of enemies alphabetically and fondly.",
    "Ran for office to fix one issue; fixed ten others accidentally.",
    "Dreams in policy proposals and wakes in minor scandals.",
    "Was once beloved, until everyone got to know them better.",
    "Uses flattery as diplomacy and silence as verdict.",
    "Has a gift for sounding brave while retreating.",
    "Lost faith years ago but still funds the temple 'for insurance.'",
    "Refused a bribe once, then raised taxes out of spite.",
    "Carries a sealed letter labeled 'Open in Case of Heroism.'",
    "Believes every complaint hides an opportunity—and a threat.",
    "Once gave a speech so dull it started a fire.",
    "Claims their handwriting alone could settle disputes.",
    "Laughs too easily to be entirely trustworthy.",
    "Thinks mercy is just justice on a holiday.",
    "Uses their enemies' insults as campaign slogans.",
    "Was promoted because no one else could pronounce the title.",
    "Keeps their friends close and their ledgers closer.",
    "Broke a peace treaty once just to see if anyone was paying attention.",
    "Has a portrait that smiles even when they don't.",
    "Believes the secret to leadership is well-timed interruptions.",
    "Once fined themselves for hypocrisy and wrote it off as performance art.",
    "Hired an oracle to predict election results; now ignores them.",
    "Treats loyalty like a loan—repayable, with interest.",
    "Banned gossip for a week; productivity dropped by half.",
    "Refers to optimism as 'inexperience.'",
    "Uses pessimism as armor and charm as distraction.",
    "Won their office in a duel of words and volume.",
    "Believes truth is negotiable if you're polite enough.",
    "Keeps a diary written entirely in metaphors.",
    "Has outlived three scandals, two rivals, and one good reputation.",
    "Smiles only when they've already won.",
    "Carries an old key to a house that doesn't exist anymore.",
    "Dreams of peace but governs by chaos.",
    "Claims to lead by example but never specifies what kind.",
    "Believes in luck the way sailors believe in storms.",
    "Was educated abroad and came home fluent in excuses.",
    "Keeps a bottle of ink labeled 'Regret' for symbolic purposes.",
    "Once gave away their title for love, then took it back for the taxes.",
    "Swears they never wanted power—it just kept reapplying for them.",
    "Hates corruption mostly because others are better at it.",
    "Was the youngest mayor in memory; now wishes memory was shorter.",
    "Keeps a private collection of anonymous apologies.",
    "Can quote the law backward and does so for emphasis.",
    "Treats peace like glassware—displayed, rarely used.",
    "Believes every citizen is an investment portfolio.",
    "Used to be a playwright; still edits conversations for pacing.",
    "Once bribed a bandit chief to attack at a more convenient hour.",
    "Rebuilt the town after the fire, but not the trust.",
    "Thinks politics is theater and insists on good lighting.",
    "Fears only boredom and accurate historians.",
    "Refers to their rival as 'an ongoing research subject.'",
    "Keeps spare policies ready for emergencies and applause.",
    "Believes power corrupts beautifully, if done right.",
    "Claims their greatest achievement is never being entirely understood."
]

